### ISSUE TITLE
Python 3.10+ on Windows x86 architecture doesn't have the `Scripts` folder on path

### ISSUE THREAD

**Issue by Avasam** [actions/setup-python#1005]
**Description:**
When pip installing a library that adds console scripts on Python 3.10+ on Windows x86, I get the following message:
>   WARNING: The scripts <> and <> are installed in 'C:\Users\runneradmin\AppData\Roaming\Python\Python3XX-32\Scripts' which is not on PATH.
>  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

See this action run at this specific line for example: https://github.com/mhammond/pywin32/actions/runs/12664473637/job/35292676675?pr=2408#step:5:3578

This doesn't see to affect x64 self-hosted runners or Python 3.9 and under.

I'm not 100% certain where the issue lies, but I'm assuming that this path not being added to `PATH` lies with `setup-python`

**Action version:**
v5

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.10, x86
3.11, x86
3.12, x86
3.13, x86

**Repro steps:**  
Run the actions of this commit (permalink): https://github.com/Avasam/pywin32/blob/61e4698/.github/workflows/main.yml

**Expected behavior:**
`C:\Users\runneradmin\AppData\Roaming\Python\Python310-32\Scripts` to be present on path, no warning and scripts are accessible

**Actual behavior:**
```
Installing collected packages: pywin32
  WARNING: The scripts pywin32_postinstall.exe and pywin32_testall.exe are installed in 'C:\Users\runneradmin\AppData\Roaming\Python\Python310-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by aparnajyothi-y** [comment]
Hello @Avasam, Thank you for creating this issue and we will look into it :)

**Comment by Avasam** [comment]
I am temporarily working around this issue with the following step:
```yaml
      - name: Fix user Scripts missing from PATH
        if: matrix.architecture == 'x86'
        run: |
          # Work around https://github.com/actions/setup-python/issues/1005
          $ScriptsPath = python -c "import sysconfig,os; print(sysconfig.get_path('scripts', f'{os.name}_user'))"
          echo $ScriptsPath
          Add-Content $env:GITHUB_PATH $ScriptsPath
```
