### ISSUE TITLE
Running on self-hosted runners leaves files in GITHUB_WORKSPACE

### ISSUE THREAD

**Issue by russellcardullo** [actions/setup-python#101]
**Describe the bug**
The very first time setup-python is called for a specific version on a self hosted runner, the action will download files into the GITHUB_WORKSPACE and leave them there.

This causes issues for later steps, for instance if I have a step to run linters it runs on the temporary files setup-python downloads.  

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [x] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)

**To Reproduce**

This workflow file run on a self-hosted Ubuntu 18.04 linux server will reproduce:

```
name: Test setup-python workspace
on: push
jobs:
  test:
    name: Test setup-python
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: before
        run: |
          ls
          ls $GITHUB_WORKSPACE
          du -hc ./
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7.17
      - name: after
        run: |
          ls
          ls $GITHUB_WORKSPACE
          du -hc ./
```

After running this you should see a directory with a UUID that adds approximately ~130MB of files to the workspace.

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**
