### ISSUE TITLE
Cannot install PyPy on Linux arm64 hosted runners: "Error: PyPy version 3.10 (x) with arch arm64 not found"

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#1010]
**Description:**

Linux arm64 hosted runners now available for free in public repositories, and Python 3.9-3.14 install on the new ubuntu-24.04-arm and ubuntu-22.04-arm runners, but pypy3.10 fails.

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

**Action version:**
Specify the action version

actions/setup-python@v5
https://github.com/actions/setup-python/releases/tag/v5.3.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

PyPy3.10

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

https://github.com/hugovk/test/blob/6157105de6170017b8b4684cb4ac61a997e93661/.github/workflows/test.yml

```yml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.13"]
        os: [
          windows-latest,
          macos-latest,
          ubuntu-latest,
          ubuntu-22.04-arm,
          ubuntu-24.04-arm,
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
```

https://github.com/hugovk/test/actions/runs/12842873775/job/35814233523

**Expected behavior:**

pypy3.10 installs on ubuntu-24.04-arm and ubuntu-22.04-arm, just like on ubuntu-latest, macos-latest, and windows-latest.

**Actual behavior:**

```
Run actions/setup-python@v5
Installed versions
  PyPy version 3.[10](https://github.com/hugovk/tinytext/actions/runs/12842839625/job/35814162033#step:3:11) (x) was not found in the local cache
  Stable PyPy version 3.10 (x) with arch arm64 not found
  Trying pre-release versions
  Error: PyPy version 3.10 (x) with arch arm64 not found
```
