### ISSUE TITLE
"`GLIBC_2.38' not found" when installing Python 3.10 on container derived from `python:3.10-slim`

### ISSUE THREAD

**Issue by lpascal-ledger** [actions/setup-python#1013]
Hello there 👋  Thanks for the action, very useful! We've encountered a strange bug today:

**Description:**

We're using `setup-python` in a matrix to test our product on several Python versions.

The tests were running in a container derived from `python:3.9-slim`, where we previously installed all our tools. We were running tests with Python 3.8, 3.9, 3.10 and 3.11 and all was working fine.

Today we updated this image to `python:3.10-slim`, but now when we setup Python 3.10, `python` crashes when invoked.

Our tests also run with Python 3.11 setup which does not trigger this issue.

**Action version:**

`actions/setup-python@v5`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  

I've tried and cornered the issue in the following workflow which triggers the bug:

```yaml
name: Debug
on:
  workflow_dispatch:
  push:

jobs:
  not_working:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python
```

An example of this failing workflow can be found [here](https://github.com/LedgerHQ/speculos/actions/runs/12909426463/job/35997064044).

**Expected behavior:**

Python can be invoked without error.

**Actual behavior:**

When invoked, `python` crashes with the following errors:
```
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /__t/Python/3.10.16/x64/lib/libpython3.10.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /__t/Python/3.10.16/x64/lib/libpython3.10.so.1.0)
Error: Process completed with exit code 1.
```
