### ISSUE TITLE
incorrect installation of dependencies

### ISSUE THREAD

**Issue by j0nm1** [actions/setup-python#105]
**Describe the bug**
When using a `python-version` that is not installed on the runner, the dependencies seem to get installed differently. This is a problem when using `isort` because it will scan all dependencies as well. When using `3.8.2` isort fails, with `3.8.3` it works fine.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
Only tested with 3.8.2

**To Reproduce**
```
name: Standard Pipeline

on:
  pull_request:
    branches: '**'

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.2

    - name: pip install
      run: pip install -r requirements.txt

    - name: isort
      run: isort --check .
```

**Run/Repo Url**
https://github.com/osbdr/pipeline-python-demo/pull/16

**Screenshots**
With 3.8.2

![image](https://user-images.githubusercontent.com/26184587/86570796-ca548300-bf70-11ea-9d1a-438c3ad6b390.png)

With 3.8.3

![image](https://user-images.githubusercontent.com/26184587/86571018-156e9600-bf71-11ea-9bfa-d698e8753f33.png)
