### ISSUE TITLE
Fails to run on self hosted Windows runner if pip is not in PATH

### ISSUE THREAD

**Issue by lazka** [actions/setup-python#1050]
**Description:**

Downstream issue: https://github.com/msys2/msys2-autobuild/commit/fe4bcd08a9fbdd4a2874a67b4491991a76d784a7#commitcomment-153600091

Running the following on a self-hosted Windows runner leads to:

```yaml
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        architecture: 'x64'
        update-environment: false
```

```
[error]Command failed: pip cache dir
'pip' is not recognized as an internal or external command,
operable program or batch file.
```

The problematic thing being "update-environment" (which we need to set, so it doesn't set cmake and pkg-config variables interfering with our builds)

It looks like the cache code depends on pip being globally available, while it might not be: https://github.com/actions/setup-python/blob/9e62be81b28222addecf85e47571213eb7680449/src/cache-distributions/pip-cache.ts#L35-L41

In other places this is  handled correctly by explicitly going through the installed python, for example: https://github.com/actions/setup-python/blob/9e62be81b28222addecf85e47571213eb7680449/src/install-pypy.ts#L177-L182

**Action version:**
actions/setup-python@v5

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

3.13, but any really

**Repro steps:**  
See above

**Expected behavior:**
The action to run

**Actual behavior:**
It errors out
