### ISSUE TITLE
`python-version` ignored when `cache: 'pip'` is set

### ISSUE THREAD

**Issue by nisbet-hubbard** [actions/setup-python#1071]
**Description:**
We observed that when `cache: 'pip'` is set, the value of `python-version` is ignored & the latest version is used instead.  

**Action version:**
v5

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
- [x] RHEL

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.10
**Repro steps:**  
```yaml
- uses: actions/setup-python@v5
   with:
     python-version: '3.10'
     cache: 'pip'
```

**Expected behavior:**
Is this the expected behaviour?

**Actual behavior:**
```sh
Run actions/setup-python@v5
  with:
    python-version: 3.13
    cache: pip
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
    freethreaded: false
  env:
    GITHUB_PAGES: true
Installed versions
  Successfully set up CPython (3.13.2)
```
