### ISSUE TITLE
Versioned executables (e.g., python3.13.exe) missing on Windows

### ISSUE THREAD

**Issue by Rongronggg9** [actions/setup-python#1079]
**Description:**
Versioned executables (e.g., `python3.13.exe`) are not installed on Windows while `python313.dll`, `python-3.13.2-amd64.exe`, and `pip3.13.exe` are installed. However, this is not the case on Linux or macOS, where versioned executables (or symlinks) are always present. This is inconvenient when [using multiple versions at once](https://github.com/actions/setup-python/blob/v5.5.0/docs/advanced-usage.md#specifying-multiple-pythonpypy-versions).

**Action version:**
`v5`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
I tested 3.9 and 3.13.

**Repro steps:**  
```yaml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.13
```

**Expected behavior:**
Versioned executables (or symlinks) are present on all platforms.

**Actual behavior:**
Versioned executables (or symlinks) are missing on Windows.
