### ISSUE TITLE
Cannot set up Python v3.13.4.

### ISSUE THREAD

**Issue by LegoWolf** [actions/setup-python#1120]
**Description:**
Python 3.13.4 was released yesterday but it's not yet listed in [versions-manifest.json](https://github.com/actions/python-versions/blob/main/versions-manifest.json) and so any attempt to set up that version of Python with this action fails. Python 3.13.3 sets up fine.

NB: The latest [release of python-versions](https://github.com/actions/python-versions/releases/tag/3.13.4-15433317575) does contain binaries for Python 3.13.4 for the platform that I use (`python-3.13.4-linux-24.04-x64.tar.gz`), and so I suspect that the missing entry in the manifest is the only issue.

**Action version:**
setup-python v5.6

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

Python 3.13.4 on any platform or architecture, because none are listed yet in [versions-manifest.json](https://github.com/actions/python-versions/blob/main/versions-manifest.json).

**Repro steps:**
Include this step in a workflow and run the workflow:

```yaml
      - name: Install Python Toolchain
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.4"
          cache: 'pip'
```

**Expected behavior:**
I expect Python 3.13.4 to be installed and used in subsequent actions involving python.

**Actual behavior:**
I get this error message:

```
Version 3.13.4 was not found in the local cache
::error::The version '3.13.4' with architecture 'x64' was not found for Ubuntu 24.04.%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
