### ISSUE TITLE
'python3' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by aeisenberg** [actions/setup-python#123]
**Describe the bug**

I am migrating some existing CI scripts to actions. Throughout these scripts, the `python3` executable is being used. However, that executable is not available on the windows action runners.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
I have tried using the default python (3.8.2) as well as 3.7.5.

**To Reproduce**

This workflow should trigger the error:

```
name: CPP Checks
on: [push]

jobs:
  cpp-checks:
    name: CPP Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.5'

      - name: Run Windows CPP Checks
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          python3
```

I expected the executable to be available. Is there a particular version of python I need to be using?

**Comment by aeisenberg** [comment]
Fixed by creating a batch file named python3.bat.

**Comment by Axel-Jacobsen** [comment]
> Fixed by creating a batch file named python3.bat.

Where did you create this batch file? I am having the same issue. Thanks!

**Comment by sebthom** [comment]
@Axel-Jacobsen you can also simply create a symlink like this:

```yaml
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Configure Python 3
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: mklink "%pythonLocation%\python3.exe" "%pythonLocation%\python.exe"
```
