### ISSUE TITLE
Add PyPy3 to macOS 11

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#158]
**Describe the bug**

Add PyPy3 to the macOS 11 preview image.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)

PyPy3

**To Reproduce**

Set up with `python-version: pypy3`

```yml
        python-version: ["3.6", "3.7", "3.8", "3.9", "pypy3"]
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-11.0, macos-10.15]
...
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
```

```
Run actions/setup-python@v2
  with:
    python-version: pypy3
    token: ***
  env:
    FORCE_COLOR: 1
Error: PyPy 3 not found
```

**Run/Repo Url**

https://github.com/hugovk/tinytext/runs/1330925401?check_suite_focus=true
