### ISSUE TITLE
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info

### ISSUE THREAD

**Issue by oegedijk** [actions/setup-python#165]
**Describe the bug**

When I try to install the `shap` python package with actions/setup-python, I get the following error:

`ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-2o6_dq3n`

Shap installs fine on my local machine, and other packages also work fine on github actions. This behaviour started about two days ago. As a result I cannot run the test suite for my [explainerdashboard](http://github.com/oegedijk/explainerdashboard) package.

**Which version of the action are you using?**

- [ ] `v1`
- [ x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x ] Linux
- [x ] Windows
- [ x] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.6`, `3.7`, `3.8`)

**To Reproduce**
 Run the following github actions scripts:

```yaml
name: test_action

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install flake8 pytest
        pip install shap
```

Then you get the following output:

```
Run python -m pip install --upgrade pip wheel
Collecting pip
  Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Collecting wheel
  Downloading wheel-0.36.1-py2.py3-none-any.whl (34 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.3.1 wheel-0.36.1
Collecting flake8
  Downloading flake8-3.8.4-py2.py3-none-any.whl (72 kB)
Collecting pytest
  Downloading pytest-6.1.2-py3-none-any.whl (272 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting importlib-metadata
  Downloading importlib_metadata-3.1.1-py3-none-any.whl (9.6 kB)
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting packaging
  Downloading packaging-20.7-py2.py3-none-any.whl (35 kB)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Installing collected packages: zipp, pyparsing, importlib-metadata, toml, pyflakes, pycodestyle, py, pluggy, packaging, mccabe, iniconfig, attrs, pytest, flake8
Successfully installed attrs-20.3.0 flake8-3.8.4 importlib-metadata-3.1.1 iniconfig-1.1.1 mccabe-0.6.1 packaging-20.7 pluggy-0.13.1 py-1.9.0 pycodestyle-2.6.0 pyflakes-2.2.0 pyparsing-2.4.7 pytest-6.1.2 toml-0.10.2 zipp-3.4.0
Collecting shap
  Downloading shap-0.37.0.tar.gz (326 kB)
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-2o6_dq3n
Error: Process completed with exit code 1.
```
**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**
