### ISSUE TITLE
[Feature request] Expose a way to cache according to the installed Python version

### ISSUE THREAD

**Issue by JulienPalard** [actions/setup-python#170]
I'm caching a venv created by the current Python version so the `venv/bin/python` is a symlink to the python binary in the Python runner cache.

I'm not pinning a patch, just a minor, currently `3.9`, so I was getting `3.9.0` and now `3.9.1`. So today the venv is broken as the venv's `bin/python` symlink still points to 3.9.0.

Would it be possible to expose an environment variable or something that could be used by the actions/cache so the cache gets invalidated when a new Python is installed?

I can think of something like this, if the `which` funcion would exist:
```yaml
- uses: actions/cache@v2
        with: 
          path: '~/cpython/'
          key: ${{ hashFiles(which('python3')) }}

but without the `which` function I don't see how I can do it.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Comment by max-nicholson** [comment]
Had the same problem myself and came across your issue when looking for a solution.
I changed my action to the following and this now works (looks like your caching is similar, would just need to change the `path` and I guess remove the `hashFiles` portion of the key
 
```
            - name: Install Python
              id: setup-python
              uses: actions/setup-python@v2
              with:
                  python-version: X
           
            - name: Cache Dependencies
              id: cache-pip
              uses: actions/cache@v2
              with:
                  path: venv
                  key: pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements/base.txt', 'requirements/test.txt') }}
                  restore-keys: pip-${{ steps.setup-python.outputs.python-version }}-
```
Where `setup-python` in the `${{ steps.` expression is the `id` of the `setup-python` step of the job
