### ISSUE TITLE
Installing pypy3 failed with "Error: IS_WINDOWS is not defined"

### ISSUE THREAD

**Issue by alex** [actions/setup-python#171]
**Describe the bug**

https://github.com/pyca/cryptography/pull/5652/checks?check_run_id=1571744687

```yaml
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYTHON.VERSION }}
```

-> 

```
Error: IS_WINDOWS is not defined
```

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

`pypy3`

**Run/Repo Url**
https://github.com/pyca/cryptography/pull/5652/checks?check_run_id=1571744687
