### ISSUE TITLE
Incorect Python version on MacOS latest

### ISSUE THREAD

**Issue by NicolasGensollen** [actions/setup-python#179]
**Describe the bug**

On MacOS-latest, the version of Python is not the expected one. 
The following input:

```yaml
name: 'test'                                                                                                                                                                                               
                                                                                                                                                                                                            
 on:                                                                                                                                                                                                        
   push:                                                                                                                                                                                                    
     branches:                                                                                                                                                                                              
       - "main"                                                                                                                                                                                             
   pull_request:                                                                                                                                                                                            
     branches:                                                                                                                                                                                              
       - '*'                                                                                                                                                                                                
                                                                                                                                                                                                            
 jobs:                                                                                                                                                                                                      
   build:                                                                                                                                                                                                   
     runs-on: ${{ matrix.os }}                                                                                                                                                                              
     strategy:                                                                                                                                                                                              
       matrix:                                                                                                                                                                                              
         os: [ubuntu-latest, windows-latest, macos-latest]                                                                                                                                                  
         python-version: ["3.7"]                                                                                                                                                                            
     steps:                                                                                                                                                                                                 
       - uses: actions/checkout@v2                                                                                                                                                                          
       - name: Set up Python                                                                                                                                                                                
         uses: actions/setup-python@v2                                                                                                                                                                      
         with:                                                                                                                                                                                              
           python-version: ${{ matrix.python-version }}                                                                                                                                                     
       - shell: bash -l {0}                                                                                                                                                                                 
         name: 'Display Python version and location'                                                                                                                                                        
         run: |                                                                                                                                                                                             
             python --version                                                                                                                                                                               
             which python
```

yields the following output:

Ubuntu

```
Python 3.7.9
/opt/hostedtoolcache/Python/3.7.9/x64/bin/python
```

Windows

```
Python 3.7.9
/c/hostedtoolcache/windows/Python/3.7.9/x64/python
```

MacOS

```
Python 2.7.18
/usr/local/bin/python
```


**Which version of the action are you using?**

- [ ] `v1`
- [X] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [X] Mac


Am I missing something here?
Thanks!

**Comment by yuxiang-he** [comment]
Also adding on to the issue here, all dependencies in our tests were installed in `/Library/Frameworks/Python.framework/Versions/2.7/bin` which is not on `$PATH` of the test environment by default.

**Comment by maxim-lobanov** [comment]
Hello,
Your issue is caused by `-l` argument in `- shell: bash -l {0}`.

`actions/setup-python` prepends `$PATH` with folder where specified Python is located. But when you add `-l` argument, bash is run in `login` mode and bash itself prepends `$PATH` with a few more folders including `/usr/local/bin` that contains default Python on MacOS.
I can confirm that same behavior on my local macOS machine. If bash is run like `bash -l`, it contains additional folders to PATH and there is no way to avoid it.

I have done a few experiments:
```yml
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
       with:
         python-version: 3.7
     - run: |
         echo $PATH
         python --version
         which python
     - run: |
         echo $PATH
         python --version
         which python
       shell: bash {0}
     - run: |
         echo $PATH
         python --version
         which python
       shell: bash -l {0}
```

The first bash step output (specified Python is the first in PATH):
```
/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.7.9/x64:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64
Python 3.7.9
/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin/python
```
The second bash step output (specified Python is the first in PATH):
```
/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.7.9/x64:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64
Python 3.7.9
/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin/python
```
The third bash step output (bash is run with `-l` flag and bash adds additional folders to PATH):
```
/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.7.9/x64:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64
Python 2.7.18
/usr/local/bin/python
```

Unfortunately, there is no way to fix it from task side since it is by design.
I suggest using shell without `-l` argument or adds the following line to bash step to prepend PATH already after bash initialization:
```
export PATH="$pythonLocation:$PATH"
```
