### ISSUE TITLE
Periodic "bad interpreter" when caching virtual environments

### ISSUE THREAD

**Issue by olirice** [actions/setup-python#182]
**Describe the bug**
When testing large projects it is convenient to cache dependencies from pypi with a cache key based on the projects `setup.py`. I've been been using that pattern (yaml shown below) on several projects for > 6 months. It works great, but periodically (every 1-6 weeks) fails with the error:

<img width="1055" alt="Screen Shot 2021-01-21 at 6 00 02 AM" src="https://user-images.githubusercontent.com/12958657/105348690-51381880-5bae-11eb-97de-608ea9c0ae2a.png">

Once the error occurs once, it will appear consistently until I alter the cache key and force the virtual environment to rebuild.

I think what's happening is that every time the build/setup for the `setup-python` action changes, it invalidates the link between the virtual environment and the python binary.

Questions:
- Is there a recommended method for caching dependencies with `setup-python` that will not suffer from this issue
- Could you recommend file/something that can be hashed and added to the cache key to invalidate the cache when new python builds are pushed?

```yaml
    steps:

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: checkout
      uses: actions/checkout@v2

    - name: cache dependencies
      id: xyz-cache
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-0

    - name: install xyz
      if: steps.sl-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --U pip setuptools wheel
        pip install -e ".[dev]"
```

Thanks!

**Which version of the action are you using?**

- [x ] `v1`
- [ ] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
At least all versions of 3.7 and 3.8 but probably all of them

**Comment by olirice** [comment]
The folks over at poetry seem to have run into the same issue

They do this:
https://github.com/python-poetry/poetry/blob/master/.github/workflows/main.yml#L55

**Comment by rosik** [comment]
We usually encounter the same problem.

I guess it's connected to some external event, like Github runners update or something similar.
After that, the workflow starts to fail steadily with the same error mentioned above.

We usually fix it by updating the cache key, but it's really annoying.

**Comment by panticmilos** [comment]
Hi @marcosschroh,

Just to let you know we are taking a deeper investigation into what is exactly happening here. Regarding other solutions guys posted, are any of them relevant to your case?

Cheers

**Comment by marcosschroh** [comment]
Hi,

I am using `pip` and `actions/cache@v3` to cache the dependencies.

**Comment by vsafonkin** [comment]
Hi @marcosschroh, do you mean this workflow? 
https://github.com/marcosschroh/dataclasses-avroschema/blob/master/.github/workflows/python-package.yml

As I see, you are using cache key without exact python version. So `venv` has config file `pyvenv.cfg` with exact version and python path, for example:
```
home = /opt/hostedtoolcache/Python/3.10.4/x64/bin
include-system-site-packages = false
version = 3.10.4
```

Your workflow has only major.minor python version and after update python patch version, for example 3.10.4 -> 3.10.5 your venv cache will break.

You should create key with exact python version, for example:
```yaml
- uses: actions/setup-python@v4
  id: cp310
  with:
     python-version: "3.10"

- uses: actions/cache@v3
  id: cache  # name for referring later
  with:
    path: .venv
    key: ${{ runner.os }}-cache-${{ steps.cp310.outputs.version }}-${{ hashFiles('requirements.txt') }}
```

And after update of python patch version this cache will be rebuilt.
