### ISSUE TITLE
Matrix variable not formatting into step name

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#19]
# Actual result

I'm seeing this as the name for a step:

```
 ${{ format('Set up Python {0}', matrix.python-version) }}
```

![image](https://user-images.githubusercontent.com/1324225/64100066-776bd700-cd73-11e9-819f-b4df5c2080d1.png)

https://github.com/hugovk/pypistats/runs/208658458

# Expected result

I expect to see "Set up Python 3.7".

# Config

I'm using this workflow config:

```yml
name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Lint
      run: tox -e lint
```

Am I doing something wrong? Can `${{ matrix.python-version }}` be used in _step_ names?

An example in the [README](https://github.com/actions/setup-python/blob/d6e58394ed908568deed5aed9f9c49d743f9a3c5/README.md#usage) shows a similar var in the _job_ name, and I've confirmed that works:

```yml
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python: [ '2.x', '3.x', 'pypy3' ]
    name: Python ${{ matrix.python }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: python my_script.py
```
