### ISSUE TITLE
Is it possible to setup debug build of Python?

### ISSUE THREAD

**Issue by animalize** [actions/setup-python#190]
Debug build may help module developer to find assertion errors, is it possible to setup debug build of Python?

```shell
python_d.exe setup.py build --debug install
python_d.exe tests/test_xxxx.py
```

**Comment by aSemy** [comment]
I'm a beginner to Python and Github Workflows, so I'm not quite sure if this will help you, but you can enable custom flags to any shell command with https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell

```yml

name: My Workflow

on:
  workflow_dispatch:
    
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: python -m trace --trace {0}
    steps:
      - name: python runner
        run: | 
            variable = 'world'
            print(f'hello {variable}')

```

Output for `python runner`:

```
Run variable = 'world'
  variable = 'world'
  print(f'hello {variable}')
  shell: /usr/bin/python -m trace --trace {0}
 --- modulename: d5986e80-e013-452d-bf6f-37e62891f4c8, funcname: <module>
d5986e80-e013-452d-bf6f-37e62891f4c8.py(1): variable = 'world'
d5986e80-e013-452d-bf6f-37e62891f4c8.py(2): print(f'hello {variable}')
hello world
```

If I set

```yml
    defaults: 
      run: 
        shell: python
```

Then the output is 

```
Run variable = 'world'
  variable = 'world'
  print(f'hello {variable}')
  shell: /usr/bin/python {0}
hello world
```
