### ISSUE TITLE
Python version not set up properly on macos-latest

### ISSUE THREAD

**Issue by heavelock** [actions/setup-python#191]
**Describe the bug**
The runner after setting up python 3.x with this action is still using python 2.7. Only happens on `macos-latest`.

Seems to be similar to https://github.com/actions/setup-python/issues/22 but I'm not using here the python shell but the default one.

What is weird, echoing $PATH returns:
```
/Users/runner/hostedtoolcache/Python/3.7.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.7.9/x64:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.5.1/x64
```

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.7, 3.8, 3.9

**To Reproduce**
1. Have a simple workflow using matrix with setting up python on macos-latest
2. Run a script
3. Expect python 3, get python 2.

Excerpt of relevant part from the workflow config:
```
name: pull_request_tests
on: pull_request

jobs:
  test_code:
    runs-on: ${{ matrix.os }}
    needs: get_ci_config
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: print package info
        shell: bash -l {0}
        run: |
          python -m pip list
          python --version
```

**Run/Repo Url**
Relevant CI run:
https://github.com/obspy/obspy/runs/1935575901

**Screenshots**
![obraz](https://user-images.githubusercontent.com/10303802/108512445-86c14600-72c1-11eb-9dc1-c95f16cbf2ea.png)
