### ISSUE TITLE
PyPy 7.3.4 fails to install on Windows

### ISSUE THREAD

**Issue by nulano** [actions/setup-python#196]
**Describe the bug**
PyPy 7.3.4 doesn't work on Windows, likely because the action is trying to install the 32-bit version (which does not exist) even when 64-bit is specified (which does exist).

**Which version of the action are you using?**

- [ ] `v1`
- [X] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [X] Windows
- [ ] Mac

**Python Versions**
`pypy-3.7-v7.3.4`, `pypy-3.7-v7.3.4rc1`, `pypy-3.7-v7.3.4rc2`

**To Reproduce**
```yml
    strategy:
      matrix:
        architecture: ["x86", "x64"]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: pypy-3.7-v7.3.4rc1
        architecture: ${{ matrix.architecture }}
```

Gives the following error for both architectures:
```
Run actions/setup-python@v2
  with:
    python-version: pypy-3.7-v7.3.4rc1
    architecture: x64
    token: ***
PyPy version 3.7 (v7.3.4-rc.1) was not found in the local cache
Error: PyPy version 3.7 (v7.3.4-rc.1) with arch x86 not found
```

**Run/Repo Url**
https://github.com/nulano/Pillow/runs/2235978354?check_suite_focus=true

**Additional context**
This is likely caused by the fact this action assumes PyPy is 32-bit only on Windows, while in reality starting with version 7.3.4 PyPy is 64-bit only on Windows. 
Related to https://github.com/actions/setup-python/pull/168#issuecomment-747645831
