### ISSUE TITLE
Matrix Target "3.10" gets interpreted as "3.1"

### ISSUE THREAD

**Issue by raphael-riel** [actions/setup-python#198]
**Describe the bug**
Trying to setup Python 3.10 Alpha as a Tox target in a Matrix.
![image](https://user-images.githubusercontent.com/474697/113412691-f0377880-9386-11eb-9a25-4b51fc3d0f15.png)

Gets converted to "3.1"
![image](https://user-images.githubusercontent.com/474697/113412709-fcbbd100-9386-11eb-80bb-b4833359179d.png)

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.10

**To Reproduce**
Action:
```yaml
name: On Push

on: [push]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10]

      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
```
