### ISSUE TITLE
Escaped newlines in error message

### ISSUE THREAD

**Issue by ethomson** [actions/setup-python#2]
I provided an invalid `version` and `architecture` to the `setup-python` action:

```
    - name: 'Select Python version'
      uses: actions/setup-python@master
      with:
        version: $PYTHON_VERSION
        architecture: $PYTHON_ARCH
```

(I was attempting to make variable expansion happen.)  The error message was surprising, with what appear to be escaped `\r` and `\n`:

```
##[error]Version $PYTHON_VERSION with arch $PYTHON_ARCH not found%0D%0AAvailable versions:%0D%0A%0D%0A
```

I would expect either actual newlines or some other type of whitespace, not `%0D%0A`.
