### ISSUE TITLE
Add support for in-development Python versions

### ISSUE THREAD

**Issue by jhenstridge** [actions/setup-python#20]
When developing a Python library, it would be useful to know whether there are any incompatibilities with the upcoming release.  So it would be useful to be able to include the latest alpha or beta release in the version matrix used to run my test suite (currently 3.8.0b4).

**Comment by L1ghtn1ng** [comment]
I second this, hope this gets fixed quickly

**Comment by asottile** [comment]
(untested, just a suggestion) presumably you can use the same approach we're using on azure pipelines: install via [deadsnakes](https://github.com/deadsnakes)

here's some sample code:

```bash
# for "released" versions (for example 3.8.0b4) use `ppa:deadsnakes` instead of the nightly
sudo add-apt-repository ppa:deadsnakes/nightly
sudo apt-get update
sudo apt-get install -y --no-install-recommends python3.8-dev python3.8-distutils
```

**Comment by shadowmoose** [comment]
Came here to request this as well. Nightly builds would be awesome.

**Comment by L1ghtn1ng** [comment]
@madhurig Can we have an update on this please?

**Comment by madhurig** [comment]
We are still reviewing this and don't have a timeline unfortunately.

**Comment by L1ghtn1ng** [comment]
That is frustrating as would love to be able to get rid of Travis and would need support as well to allow failures of certain versions as well like Travis has. Then GH actions will then be a proper one stop shop for python then
________________________________

**Comment by cjolowicz** [comment]
Here is an approach using [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa), based on @asottile's comment [above](https://github.com/actions/setup-python/issues/20#issuecomment-535616868):

```yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.9
      if: matrix.python-version == '3.9'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3.9-dev python3.9-distutils
        python3.9 -m pip install --upgrade pip setuptools
        python3.9 -m pip install --upgrade virtualenv
        python3.9 -m virtualenv --python=3.9 $HOME/venv-python3.9
        echo "::set-env name=VIRTUAL_ENV::$HOME/venv-python3.9"
        echo "::add-path::$HOME/venv-python3.9/bin"
    - uses: actions/setup-python@v1
      if: matrix.python-version != '3.9'
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
```

**Comment by cclauss** [comment]
[Travis CI has `allow_failures`](https://docs.travis-ci.com/user/customizing-the-build#jobs-that-are-allowed-to-fail) but GitHub Actions [do not seem to have an equivlant](https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033).  How would I get tests on any other version of Python to fail the build but run `nightly` in an allow_failures mode.  We do not want contributors to close their PRs because of a bug that only appears in the Python nightly build.  It is interesting to know that nightly fails but it is not a _show stopper_ because nightly is not yet a shipping product.

**Comment by hugovk** [comment]
@cclauss Perhaps put all the commands in a bash script and run it like `nightly.sh || true`?

https://serverfault.com/a/228287

**Comment by isidentical** [comment]
This issue is here for a long time, it would be very nice of this to resolved so we dont have to repeat the workaround in every new repo.

**Comment by henryiii** [comment]
Version 2 now allows downloading custom versions, so it would be nice to add the 3.9 beta's to the list (maybe with the caveat that they may be removed after the full release?)

**Comment by asottile** [comment]
I decided to package this up into a github action which should make it easier to use -- you can check that out here: [deadsnakes/action@v1.0.0](https://github.com/deadsnakes/action#using-this-action)

if anyone knows how to call the default setup-python action as a fallback, that would be great (then it could seamlessly work without having to do the wacky `if: ` checks

**Comment by adamchainz** [comment]
@asottile thanks for that. I've updated my projects to all test on Python 3.9 using the deadsnakes action, works like a (shake) charm(er).

**Comment by asottile** [comment]
I've also added 3.10-dev support to the deadsnakes action

**Comment by jadchaar** [comment]
Any idea when this will come to `setup-python`? Python 3.9 has reached the beta stage and many libraries are now looking to test against it.

**Comment by konradpabjan** [comment]
We have added support for pre-release Python versions!

If you use `actions/setup-python@v2`, you can use the latest `3.9.0-beta.4`. All available versions can be seen here: https://github.com/actions/python-versions/blob/main/versions-manifest.json

The `readme` has also been updated with some information: https://github.com/actions/setup-python#usage

We currently only have the `3.9.0-beta.4` version available as it is the most recent: https://www.python.org/download/pre-releases/

In the future, once new pre-release versions are available, they will added to the available versions in [actions/python-versions](https://github.com/actions/python-versions)

**Comment by zooba** [comment]
@konradpabjan Awesome! What's the best way we can help get new prereleases into this? PR with URLs/versions? Just a ping?

**Comment by hugovk** [comment]
Great, and `3.9-dev` seems to work too and currently picks up `3.9.0-beta.4`!

* https://github.com/python-pillow/Pillow/pull/4799
* https://github.com/python-pillow/Pillow/pull/4799/checks?check_run_id=882879245#step:3:12

**Comment by agronholm** [comment]
This is great, but the `-dev` suffix is not documented even though it appears to work. What I would like is for `3.X-dev` to install any latest available release of `3.X`, and `3.x` to install the latest stable version if it exists, or the latest prerelease version if no stable release exists. This way I could avoid having to update my GA workflows when new Python versions are released.

**Comment by gaborbernat** [comment]
@agronholm that's a dangerous proposal, wouldn't it mean that when 3.x bumps you suddenly stop testing for 3.x-1? Feels like not a good place to be.

**Comment by agronholm** [comment]
I think there's a misunderstanding here. Right now the problem is Python 3.10. The specifier `3.10` doesn't work – I have to use `3.10-dev` instead and when 3.10 is released, I have to change it to `3.10`. Why couldn't I just use `3.10` so it gives me the latest beta/rc until a stable release, and from then on only stable releases?

**Comment by hugovk** [comment]
Something like this?

> Download and set up the latest available version of Python (includes both pre-release and stable versions):


```yaml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.9.0-alpha - 3.9.0' # SemVer's version range syntax
- run: python my_script.py
```

https://github.com/actions/setup-python#usage
