### ISSUE TITLE
Outdated Tkinter Version (macOS)

### ISSUE THREAD

**Issue by timothydillan** [actions/setup-python#218]
**Describe the bug**
Hey there, I'm using Github's Action feature to automatically build and create a release of my cross-platform (macOS & windows) Python tkinter project, using pyinstaller. However, when executing the app that was built for macOS, a deprecated warning that says: "DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning." was shown. When I checked the tkinter version of the macOS runner, it turns out the Tkinter version was 8.5, as opposed to the latest version, 8.6. 

**Which version of the action are you using?**
`v2`

**Environment**
Mac (macos-latest)

**Python Versions**
Python 3.8 & 3.9, haven't tested other Python versions.

**To Reproduce**
1. Create a Python script that prints out its version 
2. Create a YAML workflow that uses the macos-latest as the OS of the runner
3. Create a job that runs the python script
4. See tkinter version 8.5

**Screenshots**
<img width="913" alt="Screenshot 2021-06-14 at 1 12 40 PM" src="https://user-images.githubusercontent.com/55008869/121842049-35c2db00-cd12-11eb-8c64-b94c678d17e8.png">

**Comment by NiBa97** [comment]
Any updates on this, or a workaround? I cant seem to get Tkinter >= 8.6...

**Comment by timothydillan** [comment]
> Any news on this ? I have also a crash during macos build because of that.

Hi there. Managed to fixed the issue by manually installing the correct Tkinter version in the action file.

```
  build:
    name: Build packages
    needs: createrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                 brew install python-tk@3.9 && echo -n 'export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.zshrc && source ~/.zshrc && echo -n 'export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc && pip install -r requirements.txt && pyinstaller -F --noconfirm --onefile --windowed --add-data="databases:databases" --add-data="images:images" gui.py && cd dist/ && mv gui name-of-application
            OUT_FILE_NAME: name-of-application
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F --noconfirm --onefile --windowed --add-data="databases;databases" --add-data="images;images" gui.py && cd dist && Rename-Item -Path "gui.exe" -NewName "name-of-application.exe"
            OUT_FILE_NAME: name-of-application.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
```
