### ISSUE TITLE
Shell Python not updating.

### ISSUE THREAD

**Issue by JavidPack** [actions/setup-python#22]
I'm not sure if this is outside the intended scope of this action, but the updated Python version does not replace the Python used by the `shell: python` option in a step. This makes it so in-line scripts in my steps run on 2.7 instead of the intended 3.x.

Here are some steps I did to confirm the discrepancy:
```
    - run: python -c "import sys; print sys.version"
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python -c "import sys; print(sys.version)"  
    - shell: python
      run: |    
        import sys
        print(sys.version)
```

The logs from running these 4 steps show the python 2.7.15 running the first step as expected, and 3.7.4 running the 3rd step as expected (since step 2 installs it), but surprisingly 2.7.15 is once again running the 4th step.

If this is intended behavior, that's fine, it just might be worth mentioning somewhere in the readme.md since this feels like an inconsistency to me.
