### ISSUE TITLE
Installs x64 python when arch: Win32

### ISSUE THREAD

**Issue by ramcdona** [actions/setup-python#230]
It appears that setup-pythonv2 is installing x64 Python even when arch is Win32.

    matrix:
        python-version: [3.6] # specify more python versions here (i.e. 3.9)
        config:
        - {
            name: "Windows 32",
            os: windows-2019,
            arch: Win32,
          }

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

Ends up installing x64 version of Python instead of Win32.  CMake reports:

-- PYTHON_EXECUTABLE: C:/hostedtoolcache/windows/Python/3.6.8/x64/python.exe
-- PYTHON_LIBRARY: 
-- PYTHON_INCLUDE_DIR: C:/hostedtoolcache/windows/Python/3.6.8/x64/include
-- PYTHON_INCLUDE_PATH: 
-- PYTHON_VERSION:

**Comment by nulano** [comment]
You need to use `x86` not `Win32`, see the version manifest: https://github.com/actions/python-versions/blob/41e5bb2c77999811a99fa634bafe9537fee86548/versions-manifest.json#L35

**Comment by ramcdona** [comment]
Thanks for pointing that out.

Unfortunately, when I make that change, CMake seems unable to figure out what architecture it should be to tell MSVC what to do.  I tried every combination of

arch: x86,

arch: x86,
platform: win32,

arch: x86,
platform: Win32,

arch: x86,Win32,

And a few others.  No dice.

**Comment by nulano** [comment]
You need to have separate values for CMake arch and Python arch. Also, it seems you are not actually specifying any arch for setup-python AFAICT, so it defaults to x64 always.

For example:
```yml
matrix:
    python-version: [3.6] # specify more python versions here (i.e. 3.9)
    config:
    -   name: "Windows 32",
        os: windows-2019,
        arch: Win32,
        python-arch: x86

...

- name: Set up Python ${{ matrix.python-version }}
  uses: actions/setup-python@v2
  with:
    python-version: ${{ matrix.python-version }}
    architecture: ${{ matrix.python-arch }}
```
