### ISSUE TITLE
Conflicting communication about pip versions in action output

### ISSUE THREAD

**Issue by sondrelg** [actions/setup-python#233]
**Describe the bug**

Find this output a little confusing:

```
Upgrading PIP...
Looking in links: /tmp/tmpi5vup_pn
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.10.0-rc.1/x64/lib/python3.10/site-packages (56.0.0)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.10.0-rc.1/x64/lib/python3.10/site-packages (21.1.3)
Collecting pip
Downloading pip-21.2.4-py3-none-any.whl (1.6 MB)
Installing collected packages: pip
Successfully installed pip-21.2.4
Error: WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
```

Seems like the warning shouldn't be output here.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

This is on the Python 3.10 release candidate
```yaml
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0-rc.1
```

**Run/Repo Url**
https://github.com/sondrelg/container-retention-policy/runs/3325363194?check_suite_focus=true

**Screenshots**
![image](https://user-images.githubusercontent.com/25310870/129411863-a2ac4634-8277-47e3-b18e-15636455b38a.png)

**Comment by HunterAP23** [comment]
I'm experiencing this as well. At first I thought this error occurred later in my pipeline when I install some packages, where I attempted to add one more step to explicitly update pip, but that step says that pip is already on the latest version.

Occurs when using this action:
```
Error: WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
```

Occurs when trying to explicitly update pip after this action:
```
Run python -m pip install -U pip
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.10.0-rc.1/x64/lib/python3.10/site-packages (21.2.4)
```

**Comment by augustovanderley** [comment]
Hi, I'm having the same experience with python 3.8.10

```
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
```

![image](https://user-images.githubusercontent.com/4129445/132967909-30fbd97d-b10b-4e3c-8234-6f696678559d.png)


![image](https://user-images.githubusercontent.com/4129445/132967919-bae038df-fccc-4633-98ec-029e30adaa56.png)

**Comment by ReenigneArcher** [comment]
Same issue...

```yaml
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9.6

        - name: Install python requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
```

Error occurs during the `Setup Python` step.

**Comment by addisonklinke** [comment]
@MaksimZhukov @hugovk Despite the referenced PR, I am still experiencing this issue with v4.2.0

```yaml
    - uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.9.5'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
```

Specifically I'm getting

```
WARNING: You are using pip version 21.1.1; however, version 22.2.2 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.9.5/x64/bin/python -m pip install --upgrade pip' command.
```
