### ISSUE TITLE
Python 3.9.7 support

### ISSUE THREAD

**Issue by sobolevn** [actions/setup-python#237]
Right now the latest Python that gets installed on 

```yml
- uses: actions/setup-python@v2
   with:
        python-version: 3.9
```

is:

```
Run actions/setup-python@v2
Successfully setup CPython (3.9.6)
```

While the latest Python 3.9.x version is `3.9.7`. It was released a couple of days ago: https://github.com/python/cpython/releases/tag/v3.9.7
