### ISSUE TITLE
SSLError for pip installs when using inside container

### ISSUE THREAD

**Issue by jerry-git** [actions/setup-python#238]
`SSLError` for `pip install`s when using `actions/setup-python@v2` inside container.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
I have only tried 3.9, likely same behaviour for other versions.

**To Reproduce**
```
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m pip install request

```

**Run/Repo Url**
https://github.com/jerry-git/gh-actions-playground/runs/3544739724?check_suite_focus=true
