### ISSUE TITLE
Zero exit with empty input for python-version

### ISSUE THREAD

**Issue by jerry-git** [actions/setup-python#241]
**Describe the bug**
Not sure if this a bug or by design but the action does nothing and exists with `0` if the `python-version` input is empty. IMO nonzero exit would be better suited.

**To Reproduce**
```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version:
```

Example run: https://github.com/jerry-git/gh-actions-playground/runs/3600040805?check_suite_focus=true

![Screenshot 2021-09-14 at 17 53 52](https://user-images.githubusercontent.com/30327563/133281223-18e31d3a-fe0e-45bd-9f7e-67e2fef55daa.png)
