### ISSUE TITLE
Python 3.9 + Windows: Does not handle long paths like other versions

### ISSUE THREAD

**Issue by pradyunsg** [actions/setup-python#267]
**Description:**
Python 3.9 seems to behave differently from other Python versions, when handling long paths on Windows. This looks suspiciously like [non-LongPathAware behaviour](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?).

**Action version:**
Specify the action version: v2?

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.9

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

```yml
name: Release
on:
  push:

jobs:
  windows:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [Windows]
        python:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -c "from pathlib import Path; (Path.cwd() / ('a'*131) / ('a'*131)).mkdir(parents=True)"
```

- https://github.com/pradyunsg/testing-grounds/actions/runs/1452413343 for the run output/behaviour.
- https://github.com/pradyunsg/testing-grounds/tree/c409e864e107f9cfead32d440a569e96144fda0a for the GitHub actions configuration.

Noticed since this was causing errors in pip's test suite: https://github.com/pypa/pip/runs/4187290412?check_suite_focus=true

**Expected behavior:**
Python 3.9 behaves like other Python versions, and handles long paths on Windows.

**Actual behavior:**
Python 3.9 fails when handling long paths on Windows.
