### ISSUE TITLE
How to cache dependencies installed via setup.py

### ISSUE THREAD

**Issue by steveoh** [actions/setup-python#282]
cache: pip looks for a requirements.txt file. Is it possible to cache from pip when installing a module from a setup.py?

**Comment by dmitry-shibanov** [comment]
Hello @steveoh. Thank you for your report. If you want to use cache for pip, but you do not have `requirements.txt` you can use [cache-dependency-path](https://github.com/actions/setup-python/blob/main/action.yml#L17-L18) to override file is used for generating hash key. You can try to use this snippet.
```
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: pip
        cache-dependency-path: setup.py # or **/setup.py
```
