### ISSUE TITLE
Wrong python version installing

### ISSUE THREAD

**Issue by Phxntxm** [actions/setup-python#285]
**Description:**
The wrong python version is downloading

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
I have an action with these steps:

```
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2   
```

![image](https://user-images.githubusercontent.com/3664828/143662075-699be641-aaa7-4887-9436-bd9174455c43.png)

**Expected behavior:**
3.8 to be used

**Actual behavior:**
3.10 is being used
