### ISSUE TITLE
Built-in caching for poetry dependencies

### ISSUE THREAD

**Issue by floatingpurr** [actions/setup-python#298]
**Description:**
As per the doc, [here](https://github.com/actions/setup-python#whats-new) and [here](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows), `setup-python` supports built-in caching of pip and pipenv dependencies. It'd nice to have the same feature also for [Poetry](https://github.com/python-poetry/poetry) out-of-the-box.

**Justification:**
Poetry is one of the latest projects joining the party of Python dependency management systems. If you want to cache _inter_-run dependencies, you have to build your own caching step (e.g., [this](https://github.com/sdispater/pendulum/blob/master/.github/workflows/tests.yml)):

```yml
- name: Set up cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
```

I'd great if that were managed by setup-python!

**Are you willing to submit a PR?**
Please, note that I'm not familiar with TS. Looking for support / hints.
