### ISSUE TITLE
Add Python 3.8 support

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#30]
Python 3.8.0 was [released yesterday](https://discuss.python.org/t/python-3-8-0-is-now-available/2478), 2019-10-14:

* https://discuss.python.org/t/python-3-8-0-is-now-available/2478

Please could you also add support in GitHub Actions for Python 3.8? Thank you!

Also requested at GitHub Community Forum:

* https://github.community/t5/GitHub-Actions/Add-Python-3-8-support/td-p/34759

Thank you!

**Comment by webknjaz** [comment]
@damccorm ^

**Comment by damccorm** [comment]
@bryanmacfarlane who owns this now

**Comment by matthewfeickert** [comment]
cc @kratsg @lukasheinrich

**Comment by thoward27** [comment]
Is there an ETA for this? Really looking forward to having 3.8 available for my actions.

**Comment by loozhengyuan** [comment]
FWIW, since it is taking some time for the newer Python versions to be available in the `tool-cache`, here's a snippet in case anyone requires `>=3.8` in their existing workflow. You can use any [tags available from Docker Hub](https://hub.docker.com/_/python):

```yml
jobs:
  test:
    name: Test on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - python:3.8-slim
          - python:3.7-slim
          - python:3.6-slim

    steps:
    - uses: actions/checkout@v1
    - name: Check Python version
      run: |
        python -V
```
