### ISSUE TITLE
Automatically read version from runtime.txt

### ISSUE THREAD

**Issue by fregante** [actions/setup-python#305]
**Description:**

I'd like this action to automatically read `runtime.txt` to determine which version to set up. Perhaps:

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: auto
- run: python my_script.py
```

**Justification:**

It's common to use `runtime.txt` to specify a python version, especially on [heroku](https://devcenter.heroku.com/articles/python-runtimes). Having a single place where the version is read makes deployment consistent.

```sh
$ cat runtime.txt
python-3.10.0
```
