### ISSUE TITLE
tkinter is broken on macos-latest 3.10.1

### ISSUE THREAD

**Issue by Akuli** [actions/setup-python#314]
**Description:**
`import tkinter` fails on MacOS with Python 3.10.1.

**Action version:**
actions/setup-python@v2

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.10.1 on macos-latest

**Repro steps:**  
```yml
jobs:
  akuli-debug:
    runs-on: macos-latest
    strategy:
      matrix:
        version: ['3.9', '3.10.0', '3.10.1']
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - run: brew install tcl-tk
      - run: |
          ls /System/Library/Frameworks/{Tcl,Tk}.framework/Versions/
      - run: otool -L /Users/runner/hostedtoolcache/Python/*/x64/lib/*/lib-dynload/_tkinter.*.so
      - run: python3 -c 'import tkinter'
```

**Expected behavior:**
No errors.

**Actual behavior:**
In a private repo named Akuli/testing, it works.

In a public repo python/typeshed, 3.9 and 3.10.0 work, but I get this error on 3.10.1:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: dlopen(/Users/runner/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so, 2): Library not loaded: /usr/local/lib/libtk8.6.dylib
  Referenced from: /Users/runner/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so
  Reason: image not found
```

output of `otool -L /Users/runner/hostedtoolcache/Python/*/x64/lib/*/lib-dynload/_tkinter.*.so` is:

```
/Users/runner/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
/Users/runner/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so:
	/usr/local/lib/libtk8.6.dylib (compatibility version 8.6.0, current version 8.6.6)
	/usr/local/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.6)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
/Users/runner/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/lib-dynload/_tkinter.cpython-39-darwin.so:
	/System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
	/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

Why is Python 3.10.1 pointing into somewhere in `/usr/local/lib/` while all others point into `/System/Library/Frameworks/`? There are no files with `tk` in their name in `/usr/local/lib/`.
