### ISSUE TITLE
Python Virtualenv activate.bat Missing Under Windows

### ISSUE THREAD

**Issue by weegreenblobbie** [actions/setup-python#315]
**Description:**

Running a github action to setup a python 3.10 virtualenv fails to produce Scripts\activate.bat, so the new virtualenv can not be activated.

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [/] Windows

**Runner type:**
- [/] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.10

**Repro steps:**  

Using this windows yaml:

```
name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - uses: actions/setup-python@v2
      name: Install Python
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv C:\temp\venv
        dir C:\temp\venv\Scripts
        C:\temp\venv\Scripts\activate.bat
        pip3 install matplotlib scons
```

**Expected behavior:**

I expected `C:\temp\venv\Scripts\activate.bat` to exist or documentation to exist or a github provided action to setup a python virtualenv.

**Actual behavior:**

No activate.bat was written to the Scripts Directory ([see this build](https://github.com/weegreenblobbie/nsound/runs/4653484684?check_suite_focus=true))
```
Error: [WinError 2] The system cannot find the file specified

    Directory: C:\Temp\venv

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/28/2021  8:59 PM                Include
d----          12/28/2021  8:59 PM                Lib
d----          12/28/2021  8:59 PM                Scripts
-a---          12/28/2021  8:59 PM            109 pyvenv.cfg

    Directory: C:\Temp\venv\Scripts

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/28/2021  8:59 PM         242408 python.exe
-a---          12/28/2021  8:59 PM         232688 pythonw.exe
C:\temp\venv\Scripts\activate.bat: D:\a\_temp\3e612eff-996e-4fd2-82b8-a63def7f3b60.ps1:7
Line |
   7 |  C:\temp\venv\Scripts\activate.bat
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'C:\temp\venv\Scripts\activate.bat' is not recognized as a name of a cmdlet, function, script
     | file, or executable program. Check the spelling of the name, or if a path was included, verify that
     | the path is correct and try again.

Error: Process completed with exit code 1.
```

I did find a work around, by running `virtualenv` instead of `python -m venv` for the windows build.
