### ISSUE TITLE
PIP cache should cache the installed packages as well

### ISSUE THREAD

**Issue by crabhi** [actions/setup-python#330]
**Description:**
Currently, `setup-python` caches only the `~/.cache/pip` directory to avoid redownloads. However, it doesn't cache the installed packages. As some package have lengthy installation steps, this leads to delays in builds.

You can see the current behaviour for example in https://github.com/crabhi/setup-python-cache-test/actions/runs/1789016634 (or in attached [build.txt](https://github.com/actions/setup-python/files/7994132/build.txt)) - the `pip install` output shows "Collecting" and "Installing" instead of "Requirement already satisfied" for all packages.

**Justification:**
For example installing the `ansible` package takes well over a minute even if it's already downloaded.

**Are you willing to submit a PR?**
Yes, I can try.

**Comment by nikita-bykov** [comment]
Hello @crabhi, thanks for your request!
We will look at it.

**Comment by barbieri** [comment]
would be also nice to follow https://github.com/actions/cache#outputs and provide an output `cache-hit` so we can `if: steps.[id]. cache-hit != 'true'` to avoid calling `pip` altogether.

**Comment by barbieri** [comment]
which is done at https://github.com/actions/cache/blob/2d8d0d1c9b41812b6fd3d4ae064360e7d8762c7b/src/utils/actionUtils.ts#L25-L27 and https://github.com/actions/cache/blob/main/src/restore.ts#L55

**Comment by jbergstroem** [comment]
This pattern affects more languages (`actions/setup-node` works the same - only caches downloads, not installs) - would love to see a general consensus towards caching installs, not tarballs (perhaps behind a flag/attribute for future compat `cache: pip-install`).

**Comment by barbieri** [comment]
for `pip` I think it makes even more sense as there are no `postinstall` actions... with `setup-node` I'm also caching the `node_modules` instead of the packages, but it "broke" some flows where there was a `postinstall` script to configure other things (like pre-build some typescript scripts). The solution is simple, just run that script manually (or in my case, cache the built scripts)... but not "one size fits all".

For pip AFAIR there are no postinstall scripts, then this would not be an issue.

**Comment by jbergstroem** [comment]
> For pip AFAIR there are no postinstall scripts, then this would not be an issue.

I'm experimenting with this at the moment and caching site-packages (read: pip output) isn't straightforward either; for instance binary wrappers (black, ..) won't work (`python -m black` works fine tho).

**Comment by dhvcc** [comment]
> would be also nice to follow https://github.com/actions/cache#outputs and provide an output `cache-hit` so we can `if: steps.[id]. cache-hit != 'true'` to avoid calling `pip` altogether.

Hey, this feature was merged today and _should_ be a part of the near-future release

**Comment by barbieri** [comment]
but the `cache-hit` is just for the packages, not the installation, right? IOW: do I still need to call `pip install`?

**Comment by dhvcc** [comment]
> but the `cache-hit` is just for the packages, not the installation, right? IOW: do I still need to call `pip install`?

Oh you're talking `pip`. Well yeah, then you'll have to wait for this action to support caching venv's out of the box. It's a case for pipenv and poetry though. The best this for now is to manually cache

**Comment by belm0** [comment]
I have a case where building packages for pypy (grpcio, grpcio-tools) takes about 6 minutes-- it's way too slow to introduce a matrix.

If anyone has a manual example using actions/cache, please share it.

**Comment by rashidnhm** [comment]
I was creating a python venv and then caching that directory, however I hit an issue where that was broken once restored (behaviour was inconsistent).

I currently have a job that takes ~6 min to complete, 4 min of which is installation of pip packages. An effective caching of installed packages would be a great boost.

**Comment by dhvcc** [comment]
> I was creating a python venv and then caching that directory, however I hit an issue where that was broken once restored (behaviour was inconsistent).
> 
> I currently have a job that takes ~6 min to complete, 4 min of which is installation of pip packages. An effective caching of installed packages would be a great boost.

Could you share the workflow so the people can take a look at it? I think it's possible to hack around while this feature is not here

**Comment by rashidnhm** [comment]
> > I was creating a python venv and then caching that directory, however I hit an issue where that was broken once restored (behaviour was inconsistent).
> > I currently have a job that takes ~6 min to complete, 4 min of which is installation of pip packages. An effective caching of installed packages would be a great boost.
> 
> Could you share the workflow so the people can take a look at it? I think it's possible to hack around while this feature is not here

```yaml
- uses: actions/checkout@v3

- id: setup_python
  uses: actions/setup-python@v3
  with:
    python-version: 3.7

- id: python_cache
  uses: actions/cache@v3
  with:
    path: venv
    key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

- if: steps.python_cache.outputs.cache-hit != 'true'
  run: |
    python3 -m venv venv

- run: |
    venv/bin/python3 -m pip install -r requirements.txt
```

**Comment by dhvcc** [comment]
@rashidnhm have you tried debugging  this issue? It seems like the problem may be not in this action.

**Comment by rashidnhm** [comment]
> @rashidnhm have you tried debugging  this issue? It seems like the problem may be not in this action.

So weirdly enough, I have not been able to reproduce the issue. To fix I simply removed the venv code and recreated and re cached it. I'm not even sure what caused it in the first place.

My only thought was maybe somehow the cach got corrupted and it kept restoring that. Really can't say.

For now I've kept the code I sent above, it's been working well since and haven't hit any other issues

**Comment by dhvcc** [comment]
Ok, nice. The code seemed ok, so that was strange. I'd only advise you to may be not run pip install if cache was hit implying you don't want to modify cache in any way if it's hit to avoid corruption

**Comment by rashidnhm** [comment]
> Ok, nice. The code seemed ok, so that was strange. I'd only advise you to may be not run pip install if cache was hit implying you don't want to modify cache in any way if it's hit to avoid corruption

So I have done quite a deep dive into the venv corruption issue, and I believe I know what happened, and how to avoid it as well.

The version of Python between when my cache was created and when it was restored changed. And I had a generic restore key which matched the old cache key. See detailed explanation below.

This is how I had my yaml file was when I hit this error:
```yaml
# BAD CONFIG DO NOT USE (Illustrative purposes only)

- uses: actions/checkout@v3

- id: setup_python
  uses: actions/setup-python@v3
  with:
    python-version: 3.7

- id: python_cache
  uses: actions/cache@v3
  with:
    path: venv
    key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
    restore-keys: |
      pip-${{ steps.setup_python.outputs.python-version }}-
      pip-

- if: steps.python_cache.outputs.cache-hit != 'true'
  run: |
    python3 -m venv venv

- run: |
    venv/bin/python3 -m pip install -r requirements.txt
```
When this workflow initially ran and saved the venv to cache, the latest release of Python3.7 was 3.7.12 ... meaning the venv created had symlinks to 3.7.12.

However, few days later when the workflow ran again, the latest release of Python3.7 was 3.7.13. 

Notice in my workflow I don't pin my Python patch version, so `actions/setup-python` downloaded the latest available patch release of Python 3.7 (as expected).

However, my restore-key `pip-` matched the old cache, which restored the old venv created for Python 3.7.12 ... meaning all the symlinks inside were now broken! I have setup Python 3.7.13 but am trying to use a venv with symlinks to 3.7.12! Hence why when I tried to call the python executable from the venv, it could not find the file! 

The resolution is to really ensure that the output of setup python is always part of the cache key. So any change in python version (even a patch version bump) would create a new cache key.

This is the code I have now, it has been working well without any issues. I have updated the workflow with the advice @dhvcc gave in the above comment. The venv is not touched if there is a cache hit.

```yaml
- uses: actions/checkout@v3

- id: setup_python
  uses: actions/setup-python@v3
  with:
    python-version: 3.7

- id: python_cache
  uses: actions/cache@v3
  with:
    path: venv
    key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

- if: steps.python_cache.outputs.cache-hit != 'true'
  run: |
    # Check if venv exists (restored from secondary keys if any, and delete)
    # You might not need this line if you only have one primary key for the venv caching
    # I kept it in my code as a fail-safe
    if [ -d "venv" ]; then rm -rf venv; fi
    
    # Re-create the venv
    python3 -m venv venv

    # Install dependencies
    venv/bin/python3 -m pip install -r requirements.txt
```

**Comment by Axeln78** [comment]
Any news on how to flag to cache the installed packages, and not only the downloaded ones, with `actions/setup-python@v4`? I am not seeing any flags for that in the documentation

**Comment by dhvcc** [comment]
> Any news on how to flag to cache the installed packages, and not only the downloaded ones, with `actions/setup-python@v4`? I am not seeing any flags for that in the documentation

What do you exactly mean by that? A bit more context would be helpful to avoid misunderstandings

**Comment by Axeln78** [comment]
Sorry, @dhvcc if I didn't manage to make myself clear.  `actions/setup-python@v4` uses `actions/cache@v3` under the hood and users do not need to call on the `actions/cache@v3 module ` in an example such as: 
```
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 and caches
      id: setup and cache
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
```

It would be great if the installed packages could be cached as well (the purpose of this issue #330) through `actions/setup-python@v4`

**Comment by Avasam** [comment]
I wonder if it's actually worth it.
Here I cached the content of `${{ env.pythonLocation }}/lib/site-packages` and `${{ env.pythonLocation }}/Scripts` using `actions/cache`:

No caching:
![image](https://user-images.githubusercontent.com/1350584/203866340-e3c2e047-8523-41ab-ad80-446f8695e9bf.png)

Caching, no cache hit (+1m):
![image](https://user-images.githubusercontent.com/1350584/203866176-29dbea8e-6e75-4dc7-99c0-ace4047eb29f.png)

Caching, cache hit (+18s):
![image](https://user-images.githubusercontent.com/1350584/203866249-88357bf8-1107-4890-9e0a-62b080d93e3e.png)

**Comment by dhvcc** [comment]
@Avasam possibly at least less strain on pypi. Also we should test small and big amounts of dependencies

**Comment by adamjstewart** [comment]
Just wanted to add an anecdote of my own experience. [TorchGeo](https://github.com/microsoft/torchgeo) has a long list of dependencies:

* [requirements/required.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/required.txt)
* [requirements/datasets.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/datasets.txt)
* [requirements/text.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/tests.txt)

Install times without caching vary quite a bit by OS and Python version:

| Python | Linux | macOS | Windows
| --- | --- | --- | --- |
| 3.10 | 2m 30s | 2m 23s | 5m 4s |
| 3.9 | 2m 50s | 4m 50s | 5m 49s |
| 3.8 | 2m 29s | 2m 12s | 3m 19s |

We first tried using the cache feature of setup-python:

```yaml
    - name: Set up python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements/required.txt
          requirements/datasets.txt
          requirements/tests.txt
    - name: Install pip dependencies
      run: pip install -r requirements/required.txt -r requirements/datasets.txt -r requirements/tests.txt
```
Not only do install times not significantly improve, in many cases it's actually worse!

| Python | Linux | macOS | Windows |
| --- | --- | --- | --- |
| 3.10 | 2m 42s | 1m 53s | 5m 50s |
| 3.9 | 2m 50s | 2m 11s | 5m 46s |
| 3.8 | 2m 39s | 3m 21s | 2m 35s |

Finally, we tried the setup proposed in [this blog](https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d) that manually caches the entire Python installation:

```yaml
    - name: Set up python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      uses: actions/cache@v3.2.4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/required.txt') }}-${{ hashFiles('requirements/datasets.txt') }}-${{ hashFiles('requirements/tests.txt') }}
    - name: Install pip dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements/required.txt -r requirements/datasets.txt -r requirements/tests.txt
```
This resulted in significantly faster installation times, which could likely be further improved by only caching the site-packages directory:

| Python | Linux | macOS | Windows |
| --- | --- | --- | --- |
| 3.10 | 38s | 39s | 4m 11s |
| 3.9 | 53s | 45s | 4m 20s |
| 3.8 | 1m 2s | 1m 15s | 1m 21s |

Apparently slower Windows caching is a known issue: https://github.com/actions/cache/issues/752.

So yes, if setup-python also cached installed packages, that would be awesome!

**Comment by adamjstewart** [comment]
> which could likely be further improved by only caching the site-packages directory

In hindsight, this is a bad idea, many tools like black or flake8 also install files into bin so we'll at least need to cache bin too.

**Comment by jbergstroem** [comment]
> In hindsight, this is a bad idea, many tools like black or flake8 also install files into bin so we'll at least need to cache bin too.

I addressed this point a while ago (above) - recap here:

> I'm experimenting with this at the moment and caching site-packages (read: pip output) isn't straightforward either; for instance binary wrappers (black, ..) won't work (`python -m black` works fine tho). Might be one of thos YMMV cases that makes it hard to standardize for everyone.

So, instead of invoking `black`, do `python -m black`.

**Comment by adamjstewart** [comment]
That's a decent workaround, but I don't think it's realistic to expect all users to change how they invoke other steps later in their workflow. I think we would have to cache bin too. Possibly everything. Bonus of caching everything is that we have to install Python from a cache anyway.

**Comment by jbergstroem** [comment]
> That's a decent workaround, but I don't think it's realistic to expect all users to change how they invoke other steps later in their workflow. I think we would have to cache bin too. Possibly everything. Bonus of caching everything is that we have to install Python from a cache anyway.

Most definitely not a catch-all!

**Comment by CoreyGaunt** [comment]
> Just wanted to add an anecdote of my own experience. [TorchGeo](https://github.com/microsoft/torchgeo) has a long list of dependencies:
> 
> * [requirements/required.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/required.txt)
> * [requirements/datasets.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/datasets.txt)
> * [requirements/text.txt](https://github.com/microsoft/torchgeo/blob/main/requirements/tests.txt)
> 
> Install times without caching vary quite a bit by OS and Python version:
> 
> Python	Linux	macOS	Windows
> 3.10	2m 30s	2m 23s	5m 4s
> 3.9	2m 50s	4m 50s	5m 49s
> 3.8	2m 29s	2m 12s	3m 19s
> We first tried using the cache feature of setup-python:
> 
> ```yaml
>     - name: Set up python
>       uses: actions/setup-python@v4.5.0
>       with:
>         python-version: ${{ matrix.python-version }}
>         cache: 'pip'
>         cache-dependency-path: |
>           requirements/required.txt
>           requirements/datasets.txt
>           requirements/tests.txt
>     - name: Install pip dependencies
>       run: pip install -r requirements/required.txt -r requirements/datasets.txt -r requirements/tests.txt
> ```
> 
> Not only do install times not significantly improve, in many cases it's actually worse!
> 
> Python	Linux	macOS	Windows
> 3.10	2m 42s	1m 53s	5m 50s
> 3.9	2m 50s	2m 11s	5m 46s
> 3.8	2m 39s	3m 21s	2m 35s
> Finally, we tried the setup proposed in [this blog](https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d) that manually caches the entire Python installation:
> 
> ```yaml
>     - name: Set up python
>       uses: actions/setup-python@v4.5.0
>       with:
>         python-version: ${{ matrix.python-version }}
>     - name: Cache dependencies
>       uses: actions/cache@v3.2.4
>       id: cache
>       with:
>         path: ${{ env.pythonLocation }}
>         key: ${{ env.pythonLocation }}-${{ hashFiles('requirements/required.txt') }}-${{ hashFiles('requirements/datasets.txt') }}-${{ hashFiles('requirements/tests.txt') }}
>     - name: Install pip dependencies
>       if: steps.cache.outputs.cache-hit != 'true'
>       run: pip install -r requirements/required.txt -r requirements/datasets.txt -r requirements/tests.txt
> ```
> 
> This resulted in significantly faster installation times, which could likely be further improved by only caching the site-packages directory:
> 
> Python	Linux	macOS	Windows
> 3.10	38s	39s	4m 11s
> 3.9	53s	45s	4m 20s
> 3.8	1m 2s	1m 15s	1m 21s
> Apparently slower Windows caching is a known issue: [actions/cache#752](https://github.com/actions/cache/issues/752).
> 
> So yes, if setup-python also cached installed packages, that would be awesome!

This right here has been a life saver for me - I toiled over this caching for so long, but this got me there!! Thank you so so so much!!

**Comment by nicklausbrown** [comment]
> In hindsight, this is a bad idea, many tools like black or flake8 also install files into bin so we'll at least need to cache bin too.

@adamjstewart, thanks for your awesome post, it really reduced my build times.

You can achieve your idea of caching only the necessary items instead of the entire python build by caching the site-packages and bin (in order to get executable packages like black, ruff, etc..). In my case, my two dependency files are classic pip-tools `dev-requirements.txt` and `requirements.txt`.

```
  - name: Cache dependency libraries
    uses: actions/cache@v3.2.4
    id: cache-libraries
    with:
      path: ${{ env.pythonLocation }}/lib/python3.11/site-packages
      key: ${{ env.pythonLocation }}-${{ hashFiles('dev-requirements.txt') }}-${{ hashFiles('requirements.txt') }}

  - name: Cache dependency binaries
    uses: actions/cache@v3.2.4
    id: cache-binaries
    with:
      path: ${{ env.pythonLocation }}/bin
      key: ${{ env.pythonLocation }}-${{ hashFiles('dev-requirements.txt') }}-${{ hashFiles('requirements.txt') }}
```

Finally you can run your pip install step conditionally based on successful cache hits with the following:

```
  - name: Install pip-tools and dependencies
    if: steps.cache-libraries.outputs.cache-hit != 'true' || steps.cache-binaries.outputs.cache-hit != 'true'
    run: |
      python -m pip install --upgrade pip
      pip install pip-tools
      pip-sync dev-requirements.txt requirements.txt
```

**Comment by harpener** [comment]
@adamjstewart Thanks for the cache example, it really helps. :-)

I have one more suggestion that I decided to use, because I want to avoid downloading all pip dependencies everytime any of them changes - to introduce a second cache just for pip cache.

```yaml
            -   name: "Python: Setup Python"
                uses: actions/setup-python@v4.7.0
                with:
                    python-version: 3.10.13

            -   name: "Cache: Cache Python"
                id: python-cache
                uses: actions/cache@v3.3.1
                with:
                    path: ${{env.pythonLocation}}
                    key: ${{env.pythonLocation}}-${{hashFiles('requirements-dev.txt')}}-${{hashFiles('requirements.txt')}}

            -   name: "Shell: Get pip cache dir"
                id: pip-cache-dir
                if: steps.python-cache.outputs.cache-hit != 'true'
                run: |
                    python -m pip install -U pip
                    pip install -U wheel
                    echo "pip-cache-dir=$(pip cache dir)" >> ${GITHUB_OUTPUT}

            -   name: "Cache: Cache pip"
                if: steps.python-cache.outputs.cache-hit != 'true'
                uses: actions/cache@v3.3.1
                with:
                    path: ${{steps.pip-cache-dir.outputs.pip-cache-dir}}
                    key: 3.10-${{hashFiles('requirements-dev.txt')}}-${{hashFiles('requirements.txt')}}
                    restore-keys: |
                        3.10-${{hashFiles('requirements-dev.txt')}}-
                        3.10-

            -   name: "Shell: Install pip dependencies"
                if: steps.python-cache.outputs.cache-hit != 'true'
                run: pip install -r requirements-dev.txt
```

**Comment by itsme2980** [comment]
Unfortunately, the built-in [cache functionality](https://github.com/actions/setup-python#caching-packages-dependencies) only supports dependencies downloaded by package manger, not the whole Python as expected.

I made an example to cache both of download libraries and binaries (`python` + package manager like `pip`) via `actions/cache`

```yaml
    - name: Cache dependencies
      uses: actions/cache@v3.2.4
      id: cache
      with:
        path: ${{ inputs.runner-cache-dir }}/Python/${{ inputs.python-version }} # e.g /opt/hostedtoolcache/Python/3.11.6
        key: ${{ inputs.runner-cache-dir }}/Python/${{ inputs.python-version }}/${{ inputs.architecture }}-${{ hashFiles('requirements.txt') }}

    - name: Set up Python env
      uses: actions/setup-python@v4
      with:
        architecture: ${{ inputs.architecture }}
        python-version: ${{ inputs.python-version }}

    - name: Install pip dependencies
      shell: bash
      run: |
        pip install -r requirements.txt
```

The key is on the `cache` step standing before the `actions/setup-python`. It will restored the cache, includes: binaries and libraries then parse into `path`. `actions/setup-python` sees `x64.complete` 0-byte file existed under `path` so will not download Python binary again.

The console output with cache should be
```
Cache restored successfully
Cache restored from key: /opt/hostedtoolcache/Python/3.11.6/x64-95421aa4e4a3b4024058ea1f527f5a724a65d3408f2a8c64daad58bfa48fa33d
...
Run actions/setup-python@v4
  Successfully set up CPython (3.11.6)
...
Run pip install -r requirements.txt
Requirement already satisfied: requests==2.25.1 in /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: pyyaml==6.0.1 in /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (6.0.1)

```
