### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pip (from versions: none) on self-hosted runner

### ISSUE THREAD

**Issue by sukki37** [actions/setup-python#354]
**Description:**

**Action version:**
Specify the action version
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

3.8.10
**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
my action yaml is as follows:
```yaml
name: Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        
    - name: Test Python
      run: |
        python /mnt/datadisk0/tmp/test.py
```
**Expected behavior:**
A description of what you expected to happen.
no error
**Actual behavior:**
A description of what is actually happening.
<img width="985" alt="image" src="https://user-images.githubusercontent.com/77312370/158506238-4f7754a6-21e6-4ece-9e08-278747e0eca8.png">
