### ISSUE TITLE
No `VIRTUAL_ENV` variable available?

### ISSUE THREAD

**Issue by jenstroeger** [actions/setup-python#359]
**Description:**
In an activated Python [virtual environment](https://docs.python.org/3/library/venv.html) (venv), the environment variable `VIRTUAL_ENV` contains the path to the base of the venv. That variable doesn’t exists, and it doesn’t seem possible to activate the environment in the action either? I could pass in that variable but then I’d have to make an assumption about where [this Action](https://github.com/actions/setup-python) installs Python on the runner.

**Action version:**
v3, latest

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
I tried with 3.9 and 3.10 and it failed for both.

**Repro steps:**  
Failed activate:
 - https://github.com/jenstroeger/python-package-template/runs/5686105935
 - https://github.com/jenstroeger/python-package-template/runs/5686092462
 
No `VIRTUAL_ENV` variable:
 - https://github.com/jenstroeger/python-package-template/runs/5686059948

**Expected behavior:**
Either being able to activate the environment (which is tricky from an Action considering the differences between Windows (`Scripts/` folder) and Linux/Mac (`bin/` folder). Ideally, the `VIRTUAL_ENV` would be set?

**Actual behavior:**
The variable isn’t available.

**Comment by marko-zivic-93** [comment]
Hello @jenstroeger 
Thank you for pointing this issue out to us!
We will get back to you as soon as possible with some meaningful information on the progress.

**Comment by vsafonkin** [comment]
Hi @jenstroeger

We cannot set pre-defined `VIRTUAL_ENV` variable because we are not able to know which directory a customer will be use for `venv`.

If you use Windows and Linux runners you can use [if condition](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif) for `venv` activation step.

Workflow example:
```yaml
jobs:
  run_master:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ '3.9', '3.10' ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
        
    - name: venv activate Linux
      if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
      run: |
        mkdir test-venv
        cd test-venv
        python -m venv .
        source ./bin/activate
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"
        
    - name: venv activate Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        mkdir test-venv
        cd test-venv
        python -m venv .
        ./Scripts/Activate.ps1
        Write-Host "VIRTUAL_ENV: $env:VIRTUAL_ENV"
```
It works as expected and `VIRTUAL_ENV` is set: [example_workflow_run](https://github.com/vsafonkin/test-repo/actions/runs/2052593151)

**Comment by jenstroeger** [comment]
Hmm, thank you @vsafonkin!

I’m curious: why does the `setup-python` Action not provide a ready-to-go virtual environment, and instead the user is required to create it?

**Comment by vsafonkin** [comment]
@jenstroeger, the setting up and activation of `venv` are not in scope of `setup-python` action because using of `venv` is not mandatory for all python developers, someone can use the other tools and packages. The main goal of `setup-python` action is install required python version on the runner.

**Comment by jenstroeger** [comment]
Thanks @vsafonkin, that makes sense. Ok to close this issue?

**Comment by vsafonkin** [comment]
@jenstroeger, yes, I believe this issue can be closed.

**Comment by jenstroeger** [comment]
@vsafonkin Following up on the above conversation. Is it correct that every `step` of a workflow job runs inside of its own shell? For example
```yaml
jobs:
  foo:
    steps:
    - name: This.
      run: echo "This"
    - name: That.
      run: echo "That"
```
The two `echo`s above run in separate shells? And that means that activating a virtual environment in one step _**does not carry over**_ into the next step?
