### ISSUE TITLE
Support cache-dependency-paths outside the current directory

### ISSUE THREAD

**Issue by PeterJCLaw** [actions/setup-python#361]
**Description:**

I'm building a composite Action which uses `actions/setup-python` internally. When specifying the `requirements.txt` from the action setting up Python fails, though I thiiink I'm passing the right values.

Here's what I've got:
``` yaml
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
```

Here's the [error I get](https://github.com/srobo/sr2022-comp/runs/5711971554?check_suite_focus=true):
> No file in /home/runner/work/sr2022-comp/sr2022-comp matched to [/home/runner/work/_actions/PeterJCLaw/srcomp-validate-action/bd809ff12b77607cc2f0ebbd035d6f0a5c8d32fc/requirements.txt], make sure you have checked out the target repository

`sr2022-comp` is the repo I'm using to test the action, `srcomp-validate-action` is the action.

My specific use-case only has a couple of dependencies so #351 would likely work as a fix, though I can imagine that a more complex scenario would want this to work.

**Platform:** Ubuntu
