### ISSUE TITLE
Poetry caching fails because Poetry is not installed

### ISSUE THREAD

**Issue by nwjsmith** [actions/setup-python#369]
**Description:**
Poetry caching fails because Poetry is not installed.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
All Python versions.

**Repro steps:**  
Run a workflow with the `setup-python` action using the `cache: 'poetry'` argument. I have set up [a minimal reproduction in a public repository](https://github.com/nwjsmith/poetry-caching-repro). There is an example of [a failed workflow run in that project](https://github.com/nwjsmith/poetry-caching-repro/runs/5792380266?check_suite_focus=true).

**Expected behavior:**
I would expect Poetry dependencies to be restored if they exist.

**Actual behavior:**
The step fails due to a missing `poetry` executable.

**Comment by dmitry-shibanov** [comment]
Hello @nwjsmith. Thank you for your report. It's an expected behaviour because the setup-python action uses poetry to get its [configuration](https://github.com/actions/setup-python/blob/main/src/cache-distributions/poetry-cache.ts#L44-L73). Poetry should be preinstalled before using the setup-python action.

For now I'm going to close the issue.

**Comment by tony** [comment]
The reason I'm not filing a separate is I think it'd be closed on the same grounds as this issue.

But I'd like to note my workaround for python versions and poetry 1.x to work:

It looks like installing `poetry` before `actions/setup-python` causes `poetry` to use the earlier python version. e.g. if GH uses python 3.8 by default and poetry is installed in that, your poetry is going to run in 3.8, no matter what `actions/setup-python` is.

It looks like `poetry install` doesn't obey the python version that actions/setup-python uses.

Here's an example
- https://github.com/vcs-python/libvcs/runs/5801763507?check_suite_focus=true
  
  ![image](https://user-images.githubusercontent.com/26336/161400385-f390943a-87c0-44e0-a583-33fd2274a055.png)
- https://github.com/vcs-python/libvcs/blob/f2798b8d4e5199a88d16118f2ade74b328e860f6/.github/workflows/tests.yml

- It also happens when installing via `pipx install poetry`

My workaround is to use a matrix and `poetry env <version>`

```yaml
name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.1.12
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          # This is required to do as of @actions/checkout@v3 to prevent default action python (3.8) from being used
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Lint with flake8
        run: poetry run flake8

      - name: Print python versions
        run: |
          python -V
          poetry run python -V

      - name: Test with pytest
        run: poetry run py.test
```

You can replace "Install poetry` with `pipx install poetry`, or `pipx install poetry==1.1.12`, etc.
