### ISSUE TITLE
python 3.7 from setup/python lacking GLIBC_2.28 to run in container

### ISSUE THREAD

**Issue by oleks-popovych** [actions/setup-python#370]
**Description:**
I’m trying to launch a workflow inside container on self-hosted runner.

Part of the workflow is python setup via action’s setup/python.

But I’m getting an error after trying to launch anything with installed python:
```
python: /lib/x86_64-linux-gnu/libm.so.6: versionGLIBC_2.29’ not found (required by /__w/_tool/Python/3.7.12/x64/lib/libpython3.7m.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.28' not found (required by /__w/_tool/Python/3.7.12/x64/lib/libpython3.7m.so.1.0)
```
**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ x] Self-hosted

**Tools version:**
python 3.7

**Repro steps:**  
```
name: Testing

on:
  workflow_dispatch:

jobs:
  tests:
    container:
      image: ubuntu:18.04
    # ubuntu 20.04
    runs-on: self-hosted 

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dev dependencies & build package
      run: |
        wget -qO- https://bootstrap.pypa.io/get-pip.py | python
```

**Expected behavior:**
it doesn't throw the error

**Actual behavior:**
error
