### ISSUE TITLE
Version 3.10 with arch x64 not found

### ISSUE THREAD

**Issue by BlueskyFR** [actions/setup-python#401]
**Description:**
Version 3.10 with arch x64 is not found when running on self-hosted runner.

**Action version:** latest

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

3.10, altough it seems like all versions are affected

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
```yml
- name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
```

**Expected behavior:**
Version should be fetched correctly.

**Actual behavior:**
The 3.10 version for x64 exists but the error says otherwise.

**Comment by dsame** [comment]
hello @BlueskyFR , can you please provide addional info about the ubuntu version of self-hosted runner?

**Comment by BlueskyFR** [comment]
Sure, it is actually not Ubuntu but Debian Buster

**Comment by dsame** [comment]
@BlueskyFR while i am reproducing the problem can please try quick solution of the setting AGENT_TOOLSDIRECTORY to `/opt/hostedtoolcache` (i assume you still use Debian), namely:

```
- name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
       env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
```

If this helps the original issue should be solved as soon as   https://github.com/actions/setup-python/pull/394 merged

**Comment by TechDawg270** [comment]
I am still experiencing the issue. Tried both with the env var mentioned above, and also without
`- uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache`

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270 

It is confirmed the problem relates to Debian boosters

[Succees on Ubuntu-20](https://github.com/akv-demo/setup-python-test/actions/runs/2336510889)
[Fail on Debian 10.12](https://github.com/akv-demo/setup-python-test/actions/runs/2336525559)

We need a bit more time to investigate the problem with the specific distro

**Comment by deepankur797** [comment]
@dsame For me it is failing even on Ubuntu-20.04

Description:
Version 3.10 with arch x64 is not found when running on act locally.

Action version: latest

Platform:

- [x] Ubuntu

Runner type:

- [x] Locally

Tools version:

3.10, although it seems like all versions are affected

Repro steps:
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

`      - name: setup python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.x"
          cache: "pip"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache`

Expected behaviour:
The version should be fetched correctly.

Actual behaviour:
The 3.10 version for x64 exists but the error says otherwise.

**Comment by dsame** [comment]
@deepankur797 , thanks for you input, can you please add the exact step you use to setup python?

**Comment by deepankur797** [comment]
I have used the following code in my job
```

steps:
  -name: setup python
   uses: actions/setup-python@v3
   with:
     python-version: "3.x"
     cache: "pip"
   env:
     AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
```

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270

The short story: Debian is not supported, sorry

 So the only workaround is - either to use Ubuntu for self-hosted machine (any virtualisation works fine) or to install python from the Debian specific repositories. 

Long story: 
 The exact reason is the [parsing /etc/os-release and extracting VERSION_ID](https://github.com/actions/toolkit/blob/b5f31bb5a25d129441c294fc81ba7f92f3e978ba/packages/tool-cache/src/manifest.ts#L140): while we expect one of "18.04", "20.04" or "22.04" the debian provides "10" and there's no python matched to this version id. 

 The worst part is we hardly can to fix the code because the python from tool cache is built against the libraries specific to the distribution and there's no certainty that the python will work the libraries from the other distribution.

**Comment by dsame** [comment]
@deepankur797 

The step[ works without problem](https://github.com/akv-demo/setup-python-test/runs/6804470081?check_suite_focus=true) on Ubuntu 20.04

```
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
```

Can you please confirm you created `opt/hostedtoolcache` folder and grant the write permission to the user of the runner  on this folder?

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270

PR https://github.com/actions/toolkit/pull/1112 adds the debug message to clarify the reason the action fails. It is the best we can do for now according to the issue.

**Comment by dsame** [comment]
Hello @BlueskyFR i am going to close this issue because it seems to be resolved and there's no other comments so far. Feel free to open new issue or reopen this one in case of any problem

**Comment by Yarden-zmr** [comment]
To be clear, other distros are officially NOT supported?

**Comment by dsame** [comment]
Hello @Yarden-zmr ,

You are right. All the binaries are built against Ubuntu provided packages.

**Comment by floptical** [comment]
This is currently failing with Python3.10 and trying to use the latest ubuntu version (which I'm reading is 22.04) from Github-hosted runners. Tried the following:

With v3:
```
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
```
 
Error:

```
Version 3.1 was not found in the local cache
Error: Version 3.1 with arch x[6](https://github.com/CityOfPhiladelphia/voter_registration_address_analysis/actions/runs/6191546006/job/16809997757#step:2:7)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

With v4:

```
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
```

Error:

```
Version 3.1 was not found in the local cache
Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by francesco-ballarin** [comment]
> This is currently failing with Python3.10 and trying to use the latest ubuntu version (which I'm reading is 22.04) from Github-hosted runners. Tried the following:
> ...
> ```
> jobs:
>   deploy:
>     name: deploy
>     runs-on: ubuntu-latest
>     steps:
>       - name: Setup Python 3.10
>         uses: actions/setup-python@v4
>         with:
>           python-version: 3.10
> ```
> 
> Error:
> ```
> Version 3.1 was not found in the local cache
> Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.
> The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
> ```

The solution is to quote 3.10, i.e.
```
       - name: Setup Python 3.10
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
```
otherwise it gets interpreted as a floating point number, and 3.10 (or 3.100, for that matter) becomes 3.1.


Answering a few months later, because I had the same issue and searching on google for `"Version 3.1 was not found in the local cache"` has the above post as the first link in the results.
