### ISSUE TITLE
Python 3.7.13 macOS: tk.h version (8.6) doesn't match libtk.a version (8.5)

### ISSUE THREAD

**Issue by carlosperate** [actions/setup-python#402]
**Description:**
There seems to be a mistmatch between the tkinter versions with Python 3.7 on macOS.

**Action version:**
v3
Which at the time of writting is v3.1.2

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
- Python 3.7
    - Specically 3.7.13
- Current runner version: '2.291.1'
    - macOS (latest) 11.6.5  20G527

**Repro steps:**  

This simple script opens a tkinter window and closes it after 5 seconds:
```python
import tkinter as tk

root = tk.Tk()
label = tk.Label(root, text="Hello World!")
label.pack(padx=20, pady=20)
root.after(5000, root.destroy)    # Close the Window after 5 seconds
root.mainloop()
```

With this workflow:

```yml
name: Test Python Tk

on: [push, pull_request]

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    name: Py ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Run tk script (closes itself after 5 seconds) - Ubuntu
        if: runner.os == 'Linux'
        run: xvfb-run python tk_min.py
      - name: Run tk script (closes itself after 5 seconds)
        if: runner.os != 'Linux'
        run: python tk_min.py
```

Works in all Python versions and operating systems except 3.7 on macOS:
- https://github.com/carlosperate/pyinstaller-test/actions/runs/2281830156
- https://github.com/carlosperate/pyinstaller-test/commit/a216015790bed76f486725389be0f1d892a6b2d3

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/4189262/167145731-6eea5557-ea66-44e0-a2ba-4f5e7fdf71b4.png">

**Expected behavior:**
The Python script to run without throwing an exception

**Actual behavior:**
An exception thrown by Python:

```
 Traceback (most recent call last):
  File "tk_min.py", line 9, in <module>
    root = tk.Tk()
  File "/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tkinter/__init__.py", line 2025, in __init__
    self._loadtk()
  File "/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tkinter/__init__.py", line 2040, in _loadtk
    % (_tkinter.TK_VERSION, tk_version))
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

**Comment by dsame** [comment]
Hello @carlosperate 
Thanks for your note - i am able to reproduce and confirm the problem exists

@marko-zivic-93  please remove needs triage tags, this issue is confirmed bug

**Comment by QuLogic** [comment]
Based on [new latest test runs](https://github.com/matplotlib/matplotlib/runs/6432726665?check_suite_focus=true), this has no spread to Python 3.8 on GitHub Actions as well.

**Comment by kousu** [comment]
I just found this too, I have a reproducer [here](https://github.com/ivadomed/test-tk-ci/blob/a48ac2a406bcc0b4863e65238dfa36c8c01275e5/.github/workflows/tests.yml) with an [example run](https://github.com/ivadomed/test-tk-ci/actions/runs/2341951055). The pattern of failures looks like

* :green_circle:  [Matrix Test of Python 3.6 on macos-latest ](https://github.com/ivadomed/test-tk-ci/runs/6480195781?check_suite_focus=true)

* :red_circle:  [Matrix Test of Python 3.7 on macos-latest ](https://github.com/ivadomed/test-tk-ci/runs/6480195852?check_suite_focus=true)

* :red_circle:  [Matrix Test of Python 3.8 on macos-latest ](https://github.com/ivadomed/test-tk-ci/runs/6480195917?check_suite_focus=true)

* :green_circle: [Matrix Test of Python 3.9 on macos-latest ](https://github.com/ivadomed/test-tk-ci/runs/6480195966?check_suite_focus=true)

* :green_circle: [Matrix Test of Python 3.10 on macos-latest ](https://github.com/ivadomed/test-tk-ci/runs/6480196035?check_suite_focus=true)

* :green_circle: [Matrix Test of Python 3.6 on macos-10.15 ](https://github.com/ivadomed/test-tk-ci/runs/6480196122?check_suite_focus=true)

* :red_circle: [Matrix Test of Python 3.7 on macos-10.15 ](https://github.com/ivadomed/test-tk-ci/runs/6480196209?check_suite_focus=true)

* :red_circle: [Matrix Test of Python 3.8 on macos-10.15 ](https://github.com/ivadomed/test-tk-ci/runs/6480196291?check_suite_focus=true)

* :green_circle: [Matrix Test of Python 3.9 on macos-10.15 ](https://github.com/ivadomed/test-tk-ci/runs/6480196403?check_suite_focus=true)

* :red_circle: [Matrix Test of Python 3.10 on macos-10.15 ](https://github.com/ivadomed/test-tk-ci/runs/6480196513?check_suite_focus=true)


Except for the last one, all of the failures are 

> tk.h version (8.6) doesn't match libtk.a version (8.5)

(the last one is about `$DISPLAY`, which is a reasonable error, but I don't know why {macos-10.15}x{python3.10} hits that)

We started seeing this on our team [two weeks ago](https://github.com/ivadomed/ivadomed/issues/1132#issuecomment-1129391795), when it **only affected the 3.7 environment**, then **this week** it became 3.7 **and 3.8**, which makes me suspect strongly something got rebuilt and it's a bug in the runner environment.

Oddly, this exactly same error was fixed 7 years ago(!) in brew: https://github.com/Homebrew/legacy-homebrew/pull/41728. Did GitHub accidentally reproduce this bug? Are they using brew packages from way back then?

If this isn't the right place to report this bug, please direct me! And have a good day!

**Comment by dsame** [comment]
Current workaround is to fix the patch version of the python to 3.7.12

```
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7.12
```

Apparently we have some interference between system Tk `/System/Library/Frameworks/Tk.framework/Versions/8.5` and brew Tk `/usr/local/Cellar/tcl-tk/8.6.12_1` but the exact reason of the break change needs more investigation
