### ISSUE TITLE
python.exe does not exist for amd64

### ISSUE THREAD

**Issue by SergeiAP** [actions/setup-python#403]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

At least python 3.10, 3.9 for actions/checkout@v3

**Repro steps:**  

```
    strategy:
      # For debbug purposes
      fail-fast: false
      matrix:
        python-version: ["3.10.3", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
```

**Expected behavior:**
No errors during python installation (python-3.X.X-amd64.exe should be found but not python.exe)

**Actual behavior:**
For AMD64 it does not exist python.exe file after installation, but it exists python-3.X.X-amd64.exe if you directly check corresponding folder
`Error: New-Item : Cannot find path 'C:\Path\to\folder\actions-runner\_work\_tool\Python\3.9.12\x64\python.exe' because it does not exist.`
