### ISSUE TITLE
Action failed after configuring poetry on Windows

### ISSUE THREAD

**Issue by he0119** [actions/setup-python#407]
**Description:**
After configuring poetry on Windows, action failed with Error: Unexpected token # in JSON.

**Action version:**
v3.1

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.7, 3.8, 3.9, 3.10

**Repro steps:**  
<https://github.com/he0119/action-test/blob/main/.github/workflows/python.yml>

Configuring poetry before setup-python

```yml
    - name: Install poetry
      run: pipx install poetry --pip-args=--pre
    - run: poetry config virtualenvs.prefer-active-python true
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
```

**Expected behavior:**
run without error.

**Actual behavior:**
<https://github.com/he0119/action-test/runs/6602490267?check_suite_focus=true#step:5:19>
```log
Run actions/setup-python@v3
Successfully setup CPython (3.10.4)
"C:\Program Files (x8[6](https://github.com/he0119/action-test/runs/6602218881?check_suite_focus=true#step:5:7))\pipx_bin\poetry.exe" config --list
cache-dir = "C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache"
experimental.new-installer = true
installer.max-workers = null
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = true
Error: Unexpected token # in JSON at position 28
```
