### ISSUE TITLE
Error: Version pypy3.9 with arch x64 not found

### ISSUE THREAD

**Issue by AribYadi** [actions/setup-python#413]
**Description:**
pypy3.9 with arch x64 is not found.

**Action version:**
latest

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
pypy3.9

**Repro steps:**  
```yml
- name: Install Pypy
  uses: actions/setup-python@v3
  with:
    python-version: "pypy3.9"
```

**Expected behavior:**
Install the latest version of PyPy that supports Python 3.9.

**Actual behavior:**
```
Error: Version pypy3.9 with arch x64 not found
```
