### ISSUE TITLE
bug: using `python-version: 3.9-dev` installs `3.10.4`

### ISSUE THREAD

**Issue by mayeut** [actions/setup-python#416]
**Description:**

using `python-version: 3.9-dev` installs `3.10.4`

```
Run ./
  with:
    python-version: 3.9-dev
    token: ***
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.13/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.7.13/x64/lib/pkgconfig
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.13/x64/lib
Successfully set up CPython (3.10.4)
```

**Action version:**
v3, main

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
`3.9-dev`

**Repro steps:**  
c.f description

**Expected behavior:**
Set up the most recent CPython 3.9 version available including pre-releases i.e. in [node-semver](https://github.com/npm/node-semver), `~3.9.0-0, {includePrerelease: true}`

**Actual behavior:**
Set up CPython 3.10.4
