### ISSUE TITLE
Pypy versions need a dash in the name (Error: Version pypy3.x with arch x64 not found)

### ISSUE THREAD

**Issue by pirgeo** [actions/setup-python#419]
**Description:**
When trying to install Pypy versions with this action, I repeatedly got the error
```
Error: Version pypy3.7 with arch x64 not found
```

**Action version:**
`actions/setup-python@v3` (I assume it uses latest, which is 3.1.2 at the time of writing)

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Pypy3.7, Pypy3.8, Pypy3.9

**Repro steps:**  
I used the example from the readme, and got that error (I removed two more pypy versions, just wanted to get it running with one)
```
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version:
          - 'pypy3.7' # the latest available version of PyPy that supports Python 3.7
```

**Expected behavior:**
Install Pypy3.7.

**Actual behavior:**
Action shows an error: 
```
build (pypy3.7)
Version pypy3.7 with arch x64 not found The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Solution:**
Use `pypy-3.7` instead of `pypy3.7` to get it working. Seems like something changed in code that doesn't allow the versions without the `-` anymore. If that is the case, updating the examples would be very helpful
