### ISSUE TITLE
Multi-job workflow with cache & poetry fails 

### ISSUE THREAD

**Issue by Vichoko** [actions/setup-python#424]
**Description:**
I started migrating from `actions/cache@v2` to `setup-python`'s cache.

I followed the workflow schema for poetry [shown in the README.md](https://github.com/actions/setup-python#caching-packages-dependencies) to create a workflow with 3 jobs:
```yaml
steps:
- uses: actions/checkout@v3
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v4
  with:
    python-version: '3.9'
    cache: 'poetry'
- run: poetry install
- run: poetry run pytest
```

When running a workflow with more than 1 job that uses poetry with cache enabled, only the first job finishes successfully but subsequent jobs fails with the following error:

```
Run poetry install
The currently activated Python version 3.6.9 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Using python3 (3.8.[12](https://github.com/thenotcompany/user-management-console-api/runs/6816676285?check_suite_focus=true#step:6:13))
Installing dependencies from lock file
Package operations: 57 installs, 0 updates, 0 removals
  • Installing protobuf (3.20.1)
  • Installing pyasn1 (0.4.8)
  • Installing pyparsing (3.0.9)
  • Installing six (1.16.0)
  FileNotFoundError
  [Errno 2] No such file or directory: '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip': '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip'
  at /usr/lib/python3.6/subprocess.py:[13](https://github.com/thenotcompany/user-management-console-api/runs/6816676285?check_suite_focus=true#step:6:14)64 in _execute_child
      1360│                     if errno_num != 0:
      1361│                         err_msg = os.strerror(errno_num)
      1362│                         if errno_num == errno.ENOENT:
      1363│                             err_msg += ': ' + repr(err_filename)
    → 1364│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1365│                 raise child_exception_type(err_msg)
      1366│ 
      1367│ 
      1368│         def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
  FileNotFoundError
  [Errno 2] No such file or directory: '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip': '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip'
  at /usr/lib/python3.6/subprocess.py:1364 in _execute_child
      1360│                     if errno_num != 0:
      1361│                         err_msg = os.strerror(errno_num)
      1362│                         if errno_num == errno.ENOENT:
      1363│                             err_msg += ': ' + repr(err_filename)
    → 1364│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1365│                 raise child_exception_type(err_msg)
      1366│ 
      1367│ 
      1368│         def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
  FileNotFoundError
  [Errno 2] No such file or directory: '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip': '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip'
  at /usr/lib/python3.6/subprocess.py:1[36](https://github.com/thenotcompany/user-management-console-api/runs/6816676285?check_suite_focus=true#step:6:37)4 in _execute_child
      1360│                     if errno_num != 0:
      1361│                         err_msg = os.strerror(errno_num)
      1362│                         if errno_num == errno.ENOENT:
      1363│                             err_msg += ': ' + repr(err_filename)
    → 1364│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1365│                 raise child_exception_type(err_msg)
      1366│ 
      1367│ 
      1368│         def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
  FileNotFoundError
  [Errno 2] No such file or directory: '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip': '/home/runner/.cache/pypoetry/virtualenvs/user-management-console-api-UrIDKMyC-py3.8/bin/pip'
  at /usr/lib/python3.6/subprocess.py:1364 in _execute_child
      1360│                     if errno_num != 0:
      1361│                         err_msg = os.strerror(errno_num)
      1362│                         if errno_num == errno.ENOENT:
      1363│                             err_msg += ': ' + repr(err_filename)
    → 1364│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1365│                 raise child_exception_type(err_msg)
      1366│ 
      1367│ 
      1368│         def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
Error: Process completed with exit code 1.
```

**Action version:**
actions/setup-python@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

- actions/setup-python@v4
- poetry 1.1.13

**Repro steps:**  
This is happening in my linter workflow:
```yaml
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.0.0

      - name: Install poetry 📚
        run: pipx install poetry

      - name: Set up Python 3.8 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"

      - name: Install dependencies 🤖
        run: poetry install

      - name: Lint with Black
        run: poetry run black src --check

  isort:
    name: isort
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3.0.0

      - name: Install poetry 📚
        run: pipx install poetry

      - name: Set up Python 3.8 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"

      - name: Install dependencies 🤖
        run: poetry install

      - name: Lint with isort
        run: 	poetry run isort src/**/* --check --settings-path ./pyproject.toml --diff
```
**Expected behavior:**

The second job should run smoothly.

**Actual behavior:**
The second job is failing on `poetry install` step with the error stated in the description of this issue. It seems to be trying to install the dependencies, even though they should be cached from the first job. So apparently, the cache isn't working. Should it skip the poetry install step if the cache was restored?
