### ISSUE TITLE
Can't Specify `python-version-file` as Absolute Path

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/setup-python#430]
**Description:**
The `python-version-file` parameter currently only functions correctly with relative paths.

**Action version:**
v4.0.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
All

**Repro steps:**
See ScribeMD/slack-templates@e653014e1fcbd1284b8cff3fe0a6c9fc735793ca and [its accompanying workflow run](https://github.com/ScribeMD/slack-templates/actions/runs/2481683517) for a reproduction.

1. Create a composite action.
1. Create a `.python-version` file containing `3.10.4`.
1. Call the setup-python action using an absolute path for the `python-version-file`:

    ```yaml
    - name: Set up Python based on .python-version file.
      uses: actions/setup-python@v4.0.0
      with:
        python-version-file: "${{ github.action_path }}/.python-version"
    ```

**Expected behavior:**
I expected Python 3.10.4 to be set up.

**Actual behavior:**
The setup-python action crashes with:
`Error: The specified python version file at: /home/runner/work/<action_name>/<action_name>/home/runner/work/<action_name>/<action_name>/.python-version does not exist`

**Comment by vsafonkin** [comment]
Hi @Kurt-von-Laven we will take a look at this.

**Comment by vsafonkin** [comment]
@Kurt-von-Laven, as I see you have a typo: 
`"{{ github.action_path }}/.python-version"` -> `"${{ github.action_path }}/.python-version"`

It works as expected:
```yaml
- name: Set up Python based on .python-version file.
      uses: actions/setup-python@v4
      with:
        python-version-file: "${{ github.action_path }}/.python-version"
```

Successful run: https://github.com/vsafonkin/test-repo/runs/6858369737?check_suite_focus=true
