### ISSUE TITLE
[Question / Potential Bug] Pip install dependencies not shared between jobs

### ISSUE THREAD

**Issue by rudy-haryanto** [actions/setup-python#453]
Hi team

Hope you have a good day
I want to create a standalone job only to install multiple libraries for multiple code checking, then another job to run specific code checking in parallel. So I installed the safety lib using pip install and set the flag of cache to 'pip'. But in separate job, when I do run "safety check" it returned error "safety command not found". I check the log of Setup Python job, they cache key is similiar between jobs. Can you please advise?

```
name: Test Code Checking

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install_code_checking_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Test code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install code checking dependencies
      run: |
        pip install flake8 pytest safety

  vulnerability_scanning:
    runs-on: ubuntu-latest
    needs: install_code_checking_dependencies
    steps:
    - name: Checkout Test code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Run safety
      run: |
        safety check
```
