### ISSUE TITLE
pip on macos-12 does not support wheels built on the same platform (problem appeared on Jul 21)

### ISSUE THREAD

**Issue by slayoo** [actions/setup-python#469]
**Description:**
(seems similar to https://github.com/actions/setup-python/issues/279)
wheels built locally are not installable, `pip debug` does not list host platform as one of compatible tags

**Action version:**
worked OK up till today with `sys.version: 3.10.5 (main, Jun  7 2022, 06:48:49) [Clang 12.0.0 (clang-1200.0.32.29)]`
fails since today with: `sys.version: 3.10.5 (main, Jul 11 2022, 14:33:08) [Clang 12.0.0 (clang-1200.0.32.29)]`

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
```
Run actions/setup-python@v1
  with:
    python-version: 3.10
    architecture: x64
```
```
  macOS
  12.4
```

**Repro steps:**  
`pip debug --verbose`

this morning (when it worked OK, https://github.com/open-atmos/PyPartMC/runs/7449996034?check_suite_focus=true):
```
...
Compatible tags: 2083
  cp310-cp310-macosx_12_0_x86_64
  cp310-cp310-macosx_12_0_intel
  cp310-cp310-macosx_12_0_fat64
  cp310-cp310-macosx_12_0_fat32
...
```

a few hours later (https://github.com/open-atmos/PyPartMC/runs/7454643791?check_suite_focus=true):
```
...
Compatible tags: 1807
  cp310-cp310-macosx_10_16_x86_64
  cp310-cp310-macosx_10_16_intel
  cp310-cp310-macosx_10_16_fat64
  cp310-cp310-macosx_10_16_fat32
  cp310-cp310-macosx_10_16_universal2
...
```

**Expected behavior:**
A python package wheel built on a local machine should be installable on a local machine.

**Actual behavior:**
It is not, `pip` claims that `...macosx_12_0_x86_64.whl is not a supported wheel on this platform.`

**Comment by IvanZosimov** [comment]
Hi, @slayoo 👋 Thank you for the issue, as a workaround you can try to specify the env.variable `SYSTEM_VERSION_COMPAT: 0` on the job's level, as it was suggested [here](https://github.com/actions/setup-python/issues/279#issuecomment-1097704505):
```
build:
    needs: [todos_annotated]
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-12, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - platform: macos-12
            python-version: "3.7"
          - platform: macos-12
            python-version: "3.8"
          - platform: macos-12
            python-version: "3.9"
    runs-on: ${{ matrix.platform }}
    env:
      SYSTEM_VERSION_COMPAT: 0
    steps:
      - if: startsWith(matrix.platform, 'macos-')
```

Please, let us know if this workaround is working for you 💌
