### ISSUE TITLE
May I ask why?  pip cache is not found

### ISSUE THREAD

**Issue by duolabmeng6** [actions/setup-python#470]
```
jobs:
  
  build:
  
    runs-on: ${{ matrix.os }}
    environment: build
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ macos-12 ]

    steps:
     
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: "x64"
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
```

<img width="712" alt="image" src="https://user-images.githubusercontent.com/59047063/180574174-e8a2b63b-9fcb-47f7-88af-9e9350075a3e.png">

There is no cache for each build

I don't know why. Every build indicates that there is no cache
