### ISSUE TITLE
Fall back to directly download when rate limit

### ISSUE THREAD

**Issue by retzero** [actions/setup-python#486]
Hello.

In `setup-node` action, there exist `Falling back` routine as;

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 16.14.2
```

```
Attempting to download 16.14.2...
API rate limit exceeded for {{MY_IP}} (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Falling back to download directly from Node
Acquiring 16.14.2 - x64 from https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.gz
```

Do you support this kind of approach?
