### ISSUE TITLE
Inconsistent Python version between steps with `macos-latest`

### ISSUE THREAD

**Issue by jtpio** [actions/setup-python#487]
**Description:**

A couple of days ago some CI checks that run on `macos-latest` with older versions of Python (3.7, 3.8, 3.9) started failing.

**Action version:**

`actions/setup-python@v4`

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

```yaml
- name: Install Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.7'
    architecture: 'x64'
```

**Repro steps:**  

Here is a public example: https://github.com/jupyter/notebook/runs/7973591481

There is also this issue with screenshots comparing `macos` to `linux`: https://github.com/jupyterlab/jupyterlab/issues/12991

**Expected behavior:**

`pip` should correspond to the Python setup with `actions/setup-python` (in the example above), when invoked with `python -m pip` or `python3 -m pip`.

**Actual behavior:**

In https://github.com/jupyter/notebook/runs/7973591481 we notice a Python version mismatch:

![image](https://user-images.githubusercontent.com/591645/186361213-83b819d5-9e44-4a37-b4a0-5615117a18ae.png)

---

Thanks for your help!
