### ISSUE TITLE
Is it possible to support wsl?

### ISSUE THREAD

**Issue by zhan9san** [actions/setup-python#496]
WSL is installed by default in Github Windows runner. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#enabled-windows-optional-features

I'd like to install Python inside WSL.

**Description:**

Currently, the platform is detected by the following code.

https://github.com/actions/setup-python/blob/98c991d13f3149457a7c1ac4083885d0d9db98e1/src/utils.ts#L8-L10

A possible usage is like below. Feel free to make suggestions.

```yml
- uses: actions/setup-python@v4
  with:
    python-version: '3.9'
    platform: WSL
```

**Justification:**
Some test case needs running inside the WSL and access the service in Windows host.

**Are you willing to submit a PR?**

Yes. But I am not familiar with Typescript. It may take much more time.
