### ISSUE TITLE
Model Python interpreter separate from version

### ISSUE THREAD

**Issue by jaraco** [actions/setup-python#509]
While writing up #508, I had another idea.

Perhaps this project should consider decoupling the interpreter from the version (model "implementation" as PyPy or CPython and "version" as "3.9[-dev]"). Right now, the two concerns are mashed together into a single "version" variable.

If instead the values were allowed to be separate, it would allow for the implementation to be used in the matrix. It could also allow for things like `version: latest` to indicate the latest available version. I'd love to have this setting in my config:

```
strategy:
  matrix:
    python:
    - 3.9
    - "3.10"
    include:
    - implementation: PyPy
      version: latest
```
