### ISSUE TITLE
Specifying x86 (32-bit) pypy-nightly on Windows installs a 64-bit binary

### ISSUE THREAD

**Issue by alex** [actions/setup-python#518]
**Description:**

```
      - name: Setup python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "pypy-3.8-nightly"
          architecture: "x86"
```

**Action version:**

4.2.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

pypy-3.8-nightly, pypy-3.9-nightly

**Repro steps:**  

Use the action specified above. Look at the output and see:

```
Downloading PyPy from "https://buildbot.pypy.org/nightly/py3.8/pypy-c-jit-latest-win64.zip" ...
```

**Expected behavior:**

A 32-bit binary is installed.

**Actual behavior:**
A 64-bit binary!
