### ISSUE TITLE
Support for python 3.7.15

### ISSUE THREAD

**Issue by skirino** [actions/setup-python#522]
**Description:**
Add support for python [3.7.15](https://www.python.org/downloads/release/python-3715/), which was released 1 week ago. Currently https://github.com/actions/python-versions/blob/main/versions-manifest.json does not contain 3.7.15.

**Are you willing to submit a PR?**
Sorry I have no idea how to add support for a new version.

**Comment by vsafonkin** [comment]
Hi @skirino, thank you for your report, we will add it soon.

**Comment by vsafonkin** [comment]
@skirino, python 3.7.15 is available now. I should use `check-latest` option to install it:

```yaml
- name: Install Python
  uses: actions/setup-python@v4
  with:
    python-version: "3.7"
    check-latest: true
```
