### ISSUE TITLE
Python installation fails on one of the jobs, two of them goes through

### ISSUE THREAD

**Issue by rublon-aha** [actions/setup-python#523]
**Description:**
Hello, we have an issue with python installation in one of our jobs. We split the matrix to have windows-latest and ubuntu-latest and we have three jobs on both of the systems:
![image](https://user-images.githubusercontent.com/115076153/196430871-4b25b799-5356-48b8-846a-81c083c039cf.png)

In one of those jobs we hit error:
![image](https://user-images.githubusercontent.com/115076153/196430976-299b73a5-77ef-4cdd-9384-3eb5cf8ed83e.png)

On another one, that uses the same action.yml it goes through:
![image](https://user-images.githubusercontent.com/115076153/196431118-c00ddb05-641b-4a71-910e-e9e78b07531e.png)

**Action version:**
We have tried v2, v2.3.2, v3, v4 on every version it is the same.

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
We try to install python version 3.6.8

**Repro steps:**  
Create action.yml file:
```
name: Setup env
description: Setup python and install dependencies

inputs:
  reqs-file:
    description: Requirements file
    required: true
    default: "requirements-dev.txt"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.6.8"
    - run:  pip install -r ${{ inputs.reqs-file }}
      shell: bash
```

runner:
```
name: Pull Request Runner

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
  format:
    uses: ./.github/workflows/_format.yml
```

_lint.yml :
```
name: Lint

on: workflow_call

jobs:
  lint:
    name: Lint on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            reqs-file: requirements-dev.txt
          - name: windows-latest
            reqs-file: requirements-win-dev.txt
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
        with:
          reqs-file: ${{ matrix.os.reqs-file }}
      - name: Flake8
        if: always()
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 .
      - name: Pylint
        if: always()
        run: pylint --rcfile=.pylintrc --output-format=colorized .
      - name: mypy
        if: always()
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: mypy
          run: mypy
```
_format.yml :
```
name: Format

on: workflow_call

jobs:
  format:
    name: Format on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            reqs-file: requirements-dev.txt
          - name: windows-latest
            reqs-file: requirements-win-dev.txt
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
        with:
          reqs-file: ${{ matrix.os.reqs-file }}
      - name: isort
        if: always()
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort --check .
      - name: Black
        if: always()
        run: |
          black --check .
```

File tree:
![image](https://user-images.githubusercontent.com/115076153/196437342-76696f82-e58b-4d38-a217-8d66c5c6a55b.png)

**Expected behavior:**
Installation of python on all of the jobs

**Actual behavior:**
Python gets installed on two of the jobs, one just fails everytime
