### ISSUE TITLE
Install not works on Centos 7 container

### ISSUE THREAD

**Issue by DifferentialOrange** [actions/setup-python#527]
**Description:**
Install action returns success on `centos:7` container but the result is unusable.

**Action version:**
4

**Platform:**
- [x] Ubuntu (with `centos:7` container)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.6 to Python 3.10

**Repro steps:**  

```yml
  issue_candidate:
    runs-on: ubuntu-20.04

    container:
      image: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - 'centos:7'
        python:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Check that Python is ok
        run: python --version
```

**Expected behavior:**
Everything is alright or I get an error like "centos is not supported".

**Actual behavior:**
Call fails for all Python versions (example for 3.6):
```
Run python --version
  python --version
  shell: sh -e {0}
  env:
    pythonLocation: /__t/Python/3.6.15/x64
    PKG_CONFIG_PATH: /__t/Python/3.6.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /__t/Python/3.6.15/x64
    Python2_ROOT_DIR: /__t/Python/3.6.15/x64
    Python3_ROOT_DIR: /__t/Python/3.6.15/x64
    LD_LIBRARY_PATH: /__t/Python/3.6.15/x64/lib
python: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
python: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
python: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__t/Python/3.6.15/x64/lib/libpython3.6m.so.1.0)
Error: Process completed with exit code 1.
```
