### ISSUE TITLE
Spurious warnings when trying to set up python 3.5 on ubuntu/macos

### ISSUE THREAD

**Issue by anntzer** [actions/setup-python#532]
**Description:**
Trying to set up Python 3.5 on ubuntu or macos triggers the following warnings, which we can't do anything about:
- "You are using pip version 20.3.4, however version 22.3 is available.  You should consider upgrading via the 'pip install --upgrade pip' command."
- "Cache entry deserialization failed, entry ignored" (twice, and only on macos).

Obviously Python 3.5 is EOL and having a warning about EOL would be entirely fine, e.g. that's what's happen when setting up Python 2.7 ("DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support").  But the warnings regarding pip and cache deserialization are just confusing.
At least the pip version warning could perhaps be suppressed via `pip --disable-pip-version-check ...`(?)

**Action version:** v4

**Platform:**
- [X] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:** 3.5.10

**Repro steps:**  
```yaml
name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
```
(see e.g. https://github.com/anntzer/gha-playground/actions/runs/3340491406)

**Expected behavior:**
No warning regarding pip or cache deserialization, possibly a warning regarding Python 3.5 being EOL.

**Actual behavior:**
Warnings regarding pip and cache deserialization.

**Comment by dmitry-shibanov** [comment]
Hello @anntzer. Thank you for your report. We'll investigate the issue.

**Comment by dmitry-shibanov** [comment]
Hello @anntzer. We had a related [pull request](https://github.com/actions/python-versions/pull/117) in python-versions to add this option. 

For now you can set up `PIP_DISABLE_PIP_VERSION_CHECK` environment variable like this:
```yaml
    runs-on: ${{ matrix.os }}
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
```
