### ISSUE TITLE
pythonLocation no longer being set in v4

### ISSUE THREAD

**Issue by shadycuz** [actions/setup-python#537]
**Description:**
When upgrading from `setup-python@v3` to `setup-python@v4`, other jobs fail because `env.pythonLocation` is no longer being set.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
all?

**Repro steps:**  
Here is the [PR](https://github.com/DontShaveTheYak/jenkins-std-lib/pull/269). Here is the [failed build](https://github.com/DontShaveTheYak/jenkins-std-lib/actions/runs/3416705888/jobs/5687102149). 

**Expected behavior:**
python location to be available. 

**Actual behavior:**
It appears to be empty.

Here is the code that now fails with `v4`. 

```yml
- name: Set up Python
   uses: actions/setup-python@v4

- name: Python Cache
   uses: actions/cache@v3
     with:
       path: ${{ env.pythonLocation }}
       key: ${{ env.pythonLocation }}-${{ hashFiles('tests/requirements.txt') }}
```

**Comment by MaksimZhukov** [comment]
Hello @shadycuz! Thank you for reporting this!
We will investigate the issue and let you know as soon as we have updates.

**Comment by dsame** [comment]
Hello @shadycuz 
The problem appears because the step `Set up Python` does not have python version from the hosted toolcache.

You should point out some:
```
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
```

This build  (with python-version:) shows the the pipeline fixed: https://github.com/akv-demo/setup-python-test/actions/runs/3495220045/jobs/5851739586#step:5:14

And this build (without python-version:) repros the issues: https://github.com/akv-demo/setup-python-test/actions/runs/3495204909/jobs/5851706555#step:5:16

Please confirm the answer solves the issue.
