### ISSUE TITLE
Wrong version via pyenv

### ISSUE THREAD

**Issue by glensc** [actions/setup-python#538]
**Description:**

with this [workflow](https://github.com/Taxel/PlexTraktSync/blob/5379e238f61519f6ed99232b27d5bb6b8bd97084/.github/workflows/test.yml) file:

```yml
env:
  DEFAULT_PYTHON: 3.7

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip
      - name: Install dependencies (pip)
        run: python -m pip install -r requirements.txt -r requirements.pipenv.txt
      - name: Install dependencies (pipenv)
 ```

The job seems to be executed with python 3.11.0 instead of 3.7, note the "pyenv/versions/3.11.0/lib/python3.11" in the paths:

```
Run python -m pip install -r requirements.txt -r requirements.pipenv.txt
  python -m pip install -r requirements.txt -r requirements.pipenv.txt
  shell: /usr/bin/bash -e {0}
  env:
    DEFAULT_PYTHON: 3.7
    pythonLocation: /opt/hostedtoolcache/Python/3.7.15/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.7.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.15/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.15/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.15/x64/lib
ERROR: Invalid requirement: "/usr/local/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes." (from line 1 of requirements.txt)
Hint: It looks like a path. File '/usr/local/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.' does not exist.
```

- https://github.com/Taxel/PlexTraktSync/actions/runs/3419219313/jobs/5692464867

**Action version:**
 - `actions/setup-python@v4`

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted
