### ISSUE TITLE
PyPy3 runs CPython 2 instead

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#54]
# Config

Part of `.github/workflows/test.yml`:

```yml
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build system information
      run: |
        python .github/workflows/system-info.py
```

`.github/workflows/system-info.py`:

```python
"""
Print out some handy system info like Travis CI does.

This sort of info is missing from GitHub Actions.

Requested here:
https://github.com/actions/virtual-environments/issues/79
"""
import os
import platform
import sys

print("Build system information")
print()

print("sys.version\t\t", sys.version.split("\n"))
print("os.name\t\t\t", os.name)
print("sys.platform\t\t", sys.platform)
print("platform.system()\t", platform.system())
print("platform.machine()\t", platform.machine())
print("platform.platform()\t", platform.platform())
print("platform.version()\t", platform.version())
print("platform.uname()\t", platform.uname())
if sys.platform == "darwin":
    print("platform.mac_ver()\t", platform.mac_ver())
```

# Expected result

When:

* `matrix-os` is `"macOS-latest"`
* `matrix.python-version` is `"pypy3"` 

Runs with PyPy3, as it did two days ago.

https://github.com/python-pillow/Pillow/runs/379447500

# Actual result

When:

* `matrix-os` is `"macOS-latest"`
* `matrix.python-version` is `"pypy3"` 

Runs with CPython 2, since yesterday, and fails.

Works as expected on Linux/PyPy3, Linux/CPython and macOS/CPython.

https://github.com/python-pillow/Pillow/runs/380647169

# More info

Here's a diff of the logs of the [last passing build (PyPy3)] build](https://github.com/python-pillow/Pillow/runs/379447500) and [first failing build (CPython 2)](https://github.com/python-pillow/Pillow/runs/380647169):

![image](https://user-images.githubusercontent.com/1324225/72152967-3cc71a80-33b5-11ea-861e-34c864306065.png)

# Also

On macOS/PyPy3, `python` is CPython 2.7.17 and `python3` is CPython 3.7.6.

On Linux/PyPy3, Linux/CPython, macOS/CPython, both `python` and `python3` pointing to the same, correct version.

https://github.com/hugovk/Pillow/runs/383338343 shows output of:

```yml
    - name: Build system information
      run: |
        python --version
        python .github/workflows/system-info.py
        python3 --version
        python3 .github/workflows/system-info.py
```

---

Downstream issue: https://github.com/python-pillow/Pillow/issues/4350
