### ISSUE TITLE
Error: Version 3.9.11 with arch x64 not found

### ISSUE THREAD

**Issue by atayardimci** [actions/setup-python#541]
**Description:**
I've been using this action without an issue until a few days ago. Currently having this error while trying to setup Python 3.9.11. I have the same error with other Python versions.

```
Error: Version 3.9.11 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Saw this comment under another issue and it seems related https://github.com/actions/setup-python/issues/162#issuecomment-1312522561

**Action version:**
actions/setup-python@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

3.9.11
3.9.7

**Repro steps:**  
A job that `runs-on: ubuntu-latest`.  Using the action in a step as this

```
- name: Setup Python 
   id: setup-python
   uses: actions/setup-python@v4
   with:
     python-version: 3.9.11
```

**Expected behavior:**
Sets up Python without an issue

**Actual behavior:**
Receiving this error
```
Error: Version 3.9.11 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by atayardimci** [comment]
Pinning the runner image version to `ubuntu-20.04` resolved the issue

**Comment by MaksimZhukov** [comment]
Hello @bweisberger  !
The `ubuntu-latest` tag is being migrated to Ubuntu 22.04 (see details in the related [announcement](https://github.com/actions/runner-images/issues/6399)). We have not built Python `3.9.11` for Ubuntu 22.04. Python 3.9 is available for installation on Ubuntu 22.04 starting with Python 3.9.12. Could you please switch to the Python `3.9.12` (or higher) or specify Python version as `3.9` to install the latest available patch version?
```yml
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
```
