### ISSUE TITLE
Automatic Python version determination from pyproject.toml

### ISSUE THREAD

**Issue by BrandonLWhite** [actions/setup-python#542]
**Description:**
Automatically determine the best Python version to install by parsing pyproject.toml and using the `tool.poetry.dependencies.python` version constraint specifier.  The "best" version is the latest available Python version that satisfies the constraint.

**Justification:**
Though the recent support for .python-version file is very helpful, this requires duplication of the Python version declaration in the source project when using Poetry.  The version declaration is already in the pyproject.toml, and Poetry already uses it to select the best Python version as described above when working locally. It would be ideal for CI/CD to also use pyproject.toml to determine the best Python version, instead of requiring adding another file to the repo (.python-version) that contains the needed Python version.

**Are you willing to submit a PR?**
Yes!  Before embarking on such and endeavor, I would like to know if the setup-python maintainers are open to such a feature, and what the preferred configuration inputs might look like.

**Comment by MaksimZhukov** [comment]
Hello @BrandonLWhite! Thank you for the suggested idea!
We will consider adding this feature and will let you know as soon as we have any decision.

**Comment by Hongbo-Miao** [comment]
Just copy from my original request at #629 as supplement to this ticket 😃

---

Since Poetry has Python version defined in `pyproject.toml`

```toml
[tool.poetry.dependencies]
python = "3.11.x"
```

It would be great to support reading Python version from Poetry `pyproject.toml`.

Something like

```yaml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: path/to/pyproject.toml
```

FYI, today **actions/setup-go** supports similar way like [this](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file):

```yaml
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: path/to/go.mod
```

(Inside **go.mod**, it has Go version defined)

Thanks! 😃
