### ISSUE TITLE
Unable to setup 3.9.10

### ISSUE THREAD

**Issue by rjoelnorgren** [actions/setup-python#553]
**Description:**
We are unable to run GHA using version 3.9.10. Action reports 3.9.10 is not an available version:
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/68205730/205130669-8c099d05-c426-492d-b31f-2309ca0df5fe.png">

**Action version:**
actions/setup-python@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
workflow:
```yaml
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.10
          cache: 'poetry'
```

**Expected behavior:**
A description of what you expected to happen.
We can run GHA with python version 3.9.10.

**Actual behavior:**
A description of what is actually happening.
We are unable to setup python version 3.9.10.
