### ISSUE TITLE
Using poetry virtualenv `in-project = true` doesn't cache the venv?

### ISSUE THREAD

**Issue by yuvalshi0** [actions/setup-python#554]
**Description:**
HI everyone, I'm trying to cache in my poetry packages, I run a `setup-poetry` action as follows:
```yml
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - run: poetry show
      shell: bash

    - run: poetry install
      shell: bash

    - run: poetry self add "poetry-dynamic-versioning[plugin]"
      shell: bash

```
my project has the following config:
```
[virtualenvs]
create = true
in-project = true
```

When running the builds I see the virtualenv cache is hit, yet it doesn't hold any packages, am I doing something wrong?

**Action version:**
Running this action in every build

**Platform:**
- [ X ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
The local .venv should be cached
**Actual behavior:**
Installs are running on every run
