### ISSUE TITLE
Error: Version 3.9.5 with arch x64 not found

### ISSUE THREAD

**Issue by djmgit** [actions/setup-python#555]
**Description:**
Error: Version 3.9.5 with arch x64 not found

**Action version:**
v2

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**
python 3.9.5

**Repro steps:**  
Trying to setup python 3.9.5 using setup-python@v2

config: 
```
- uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5'
        cache: 'pip'
```

**Expected behavior:**
python 3.9.5 is installed

**Actual behavior:**
Facing error:

```
Run actions/setup-python@v2
  with:
    python-version: 3.9.5
    cache: pip
    token: ***
Version 3.9.5 was not found in the local cache
Error: Version 3.9.5 with arch x64 not found
```
The list of supported python versions at https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
does contain 3.9.5 for x64.

**Comment by abisek** [comment]
I'm seeing the same issue starting today.

My Action step is vanilla
```
      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"
```

Here's the error when running the step
```
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

The URL content shows there is support x86 for version 3.6

**Comment by MaksimZhukov** [comment]
Hello @djmgit  !
The `ubuntu-latest` tag is being migrated to Ubuntu 22.04 (see details in the related [announcement](https://github.com/actions/runner-images/issues/6399)). We have not built Python `3.9.5` for Ubuntu 22.04. Python 3.9 is available for installation on Ubuntu 22.04 starting with Python 3.9.12. Could you please switch to the Python `3.9.12` (or higher) or specify Python version as `3.9` to install the latest available patch version?
```yml
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
```
