### ISSUE TITLE
`python3.9.15` is not usable on `ubuntu:20.04` 

### ISSUE THREAD

**Issue by eugene-graft** [actions/setup-python#560]
**Description:**
I get errors trying to use `python3.9.15` on `ubuntu:20.04` 

```
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python3)
python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
```

**Action version:**
v4

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**
Python `3.9.15`

**Repro steps:**  
Trying to setup `python3.9.15` using `setup-python@v4` and `ubuntu:20.04`:
```
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: pip-${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}

      - name: python-check
        run: python3.9 -V
        shell: bash
```

**Expected behavior:**
`python3.9.15` is usable on `ubuntu:20.04`.

**Actual behavior:**
`python3.9.15` is **not** usable on `ubuntu:20.04`.
```
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python3)
python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/hostedtoolcache/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
```
