### ISSUE TITLE
PyPy 7.3.10 missing

### ISSUE THREAD

**Issue by radarhere** [actions/setup-python#565]
**Description:**
When running actions/setup-python@v4, "PyPy 7.3.9" is used instead of the more recent PyPy 7.3.10. Filing a bug here as per "[Please open an issue in actions/setup-python if any versions are missing.](https://github.com/actions/python-versions)"

Thanks for any help you can provide, or even just an ETA.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.8 and 3.9 are affected.

**Repro steps:**  
I've created https://github.com/radarhere/pypy_version as a simple example. This ran at https://github.com/radarhere/pypy_version/actions/runs/3670847630

**Expected behavior:**
PyPy 7.3.10 is setup.

**Actual behavior:**
PyPy 7.3.9 is setup instead.

**Comment by MaksimZhukov** [comment]
Hello @radarhere! 
Thanks for reporting this!
We will investigate the issue!

**Comment by dmitry-shibanov** [comment]
Hello @radarhere. Could you please try to set `check-latest: true`.
```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: pypy3.9
          check-latest: true
```
