### ISSUE TITLE
Unable to use asdf-vm based version-file

### ISSUE THREAD

**Issue by hjpotter92** [actions/setup-python#571]
I was using `setup-node` action, and didn't face this problem when using `.tool-versions` file; so i was surprised hitting this error in `setup-python` action.

**Description:**
When using the action, I expected it to work seamlessly with `.tool-versions` file that [asdf-vm generates](https://github.com/asdf-vm/asdf).

**Action version:**
Using `@v4`

**Platform:**
- [x] Ubuntu

**Runner type:**
- Github's runner

**Tools version:**

**Repro steps:**  
- Create a asdf based version file:

    ```sh
    asdf local python 3.10.9
    asdf local poetry 1.3.1
    ```
- Use the generated `.tool-versions` file in github action:

    ```yaml

    - uses: actions/setup-python@v4
      with:
        python-version-file: .tool-versions
        cache: poetry
    ```
- Fails to install python.

**Expected behavior:**

Parser should be smart to also identify other version managers

**Actual behavior:**
```
Resolved architecture/.tool-versions as python 3.10.9
poetry 1.3.1

Version python 3.10.[9](https://github.com/livepeer/livepeer-infra/actions/runs/3738908086/jobs/6345503064#step:4:10)
poetry 1.3.1
 was not found in the local cache
Error: The version 'python 3.[10](https://github.com/livepeer/livepeer-infra/actions/runs/3738908086/jobs/6345503064#step:4:11).9
poetry 1.3.1
' with architecture 'x64' was not found for Ubuntu 22.04.
```

**Comment by MaksimZhukov** [comment]
Hello @hjpotter92 ! Thank you for reporting this! 
We'll consider updating the parsing logic for the `python-version-file` input.

**Comment by elpic** [comment]
https://github.com/actions/setup-python/pull/588

**Comment by goetzc** [comment]
As a **workaround** you can add a small intermediate step:

```yml
    - name: Determine versions
      shell: bash -leo pipefail {0}
      id: get_versions
      run: |
        python="$(grep -v '#' .tool-versions | grep python | awk '{print $2}')"
        echo "python=${python}" >> $GITHUB_OUTPUT

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.get_versions.outputs.python }}
```
