### ISSUE TITLE
`python3.9.15` is not usable on `ubuntu:20.04`

### ISSUE THREAD

**Issue by jlariza** [actions/setup-python#572]
**Description:**
we get this error when trying to use 3.9.15 version in a self-hosted server:

```
python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python3.9)
python3.9: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /__w/_tool/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /__w/_tool/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /__w/_tool/Python/3.9.15/x64/lib/libpython3.9.so.1.0)
python3.9: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /__w/_tool/Python/3.9.[15](https://github.com/swappsco/backpro/actions/runs/3752048919/jobs/6373768429#step:4:16)/x64/lib/libpython3.9.so.1.0)
Error: Process completed with exit code 1.
```
This was already reported here https://github.com/actions/setup-python/issues/560 but the issue persists. 

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
actions/setup-python@v4

**Repro steps:**  
This is the configuration We are using:
```
name: py.test

on:
  push:
    branches:
      - "**"
      - "!integration"

jobs:
  test:
    runs-on: self-hosted
    container: ubuntu:20.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: python-check
        run: python3.9 -V
        shell: bash
```

**Expected behavior:**
show the python version

**Actual behavior:**
shows the error in the top

**Comment by dmitry-shibanov** [comment]
Hello @jlariza. Thank you for your report. What is the operation system of your self-hosted runner ? 

The root cause of the linked issue was that the runner was using the python version previously was cached on ubuntu-22.04 and after changing ubuntu-22.04 to ubuntu-20.04 the cached python was restored but the restored python was not suitable for ubuntu-22.04. After removing `actions/cache` the issue was resolved.

**Comment by jlariza** [comment]
Good day, @dmitry-shibanov 

Our self-hosted runner is using `Ubuntu 22.04.1 LTS` but the container we are using is Ubuntu 20.04.

We also tried using a container with ubuntu 22.04 but it fails because gh actions uses node 16 and ubuntu 22 image no longer supports it (that issue is related to the actions runner itself; not to this specific action)

**Comment by dmitry-shibanov** [comment]
Hello @jlariza. Its is an expected behaviour. You should use `ubuntu 22.04` because otherwise you get the different python versions in the hosted toolcache directory. As I know Ubuntu 22.04 supports node 16. I think the issue comes from your set up of self-hosted agent. For now I'm going to close the issue.

**Comment by Atlinx** [comment]
Hey all, I'm still getting this issue using `ubuntu-latest`.

Here's the relevant portion of my workflow:
```yaml
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Python Dependencies
        run: python -m pip install -r requirements.txt
```

And here's the error:
```
Run python -m pip install -r requirements.txt
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python)
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /__t/Python/3.10.[11](https://github.com/Fractural/FracturalCommons/actions/runs/5205930059/jobs/9391917050#step:5:12)/x64/lib/libpython3.10.so.1.0)
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /__t/Python/3.10.11/x64/lib/libpython3.10.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /__t/Python/3.10.11/x64/lib/libpython3.10.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /__t/Python/3.10.11/x64/lib/libpython3.10.so.1.0)
python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /__t/Python/3.10.11/x64/lib/libpython3.10.so.1.0)
```
