### ISSUE TITLE
setup-python@v4 randomly hangs

### ISSUE THREAD

**Issue by ringohoffman** [actions/setup-python#598]
**Description:**

Lately, my `setup-python` step of my CI build has been intermittently hanging:

```
Run actions/setup-python@v4
  with:
    python-version: 3.9
    cache: pip
    cache-dependency-path: pyproject.toml
    check-latest: false
    token: ***
    update-environment: true
  env:
    AWS_REGION: us-east-1
    DOCKER_BUILDKIT: 1
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
Installed versions
  Successfully set up CPython (3.9.16)
/opt/hostedtoolcache/Python/3.9.16/x64/bin/pip cache dir
/home/runner/.cache/pip
Received 88080384 of 30[2](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:2)71[3](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:3)9961 (2.9%), 83.1 MBs/sec
Received 23[4](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:4)881024 of 3027139961 (7.8%), 111.4 MBs/sec
Received 394264[5](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:5)7[6](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:6) of 302[7](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:7)139961 (13.0%), 124.[8](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:8) MBs/sec
Received 553648128 of 302713[9](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:9)961 (18.3%), 131.5 MBs/sec
Received 700448768 of 3027139961 (23.1%), 133.2 MBs/sec
Received 843055[10](https://github.com/protopia-ai/stained-glass-factory/actions/runs/4078301770/jobs/7028349650#step:4:10)4 of 3027139961 (27.8%), 133.7 MBs/sec
Received 973078528 of 3027139961 (32.1%), 132.3 MBs/sec
Received 1098907648 of 3027139961 (36.3%), 130.7 MBs/sec
Received 1233125376 of 3027139961 (40.7%), 130.4 MBs/sec
Received 1371537408 of 3027139961 (45.3%), 130.5 MBs/sec
Received 1493172224 of 3027139961 (49.3%), 129.2 MBs/sec
Received 1606418432 of 3027139961 (53.1%), 127.5 MBs/sec
Received 1715470336 of 3027139961 (56.7%), 125.6 MBs/sec
Received 1828716544 of 3027139961 (60.4%), 124.3 MBs/sec
Received 1954545664 of 3027139961 (64.6%), 124.0 MBs/sec
Received 2059403264 of 3027139961 (68.0%), 122.5 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 120.0 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 113.3 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 107.4 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 102.0 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 97.2 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 92.7 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 88.7 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 85.0 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 81.6 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 78.5 MBs/sec
Received 2143289343 of 3027139961 (70.8%), 75.6 MBs/sec
...
```

This one hung for 29m 1s before I cancelled it and restarted it, after which it completed in 49s...

**Action version:**
setup-python@v4

**Platform:**

Ubuntu 22.04.1 LTS

**Runner type:**
Hosted

**Tools version:**
3.9 ?

**Repro steps:**  
My repo is private. It's just part of a normal GitHub build.

```
name: Build Image

on: pull_request

permissions:
  id-token: write
  contents: read
jobs:
  build_image:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: clone the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: |
          python -m pip install .[cpu,test]
      ...

```

**Expected behavior:**
For the action not to hang or even restart itself if it is hanging.
