### ISSUE TITLE
Setup default shell

### ISSUE THREAD

**Issue by yaeji98** [actions/setup-python#607]
**Description:**
Shell cannot be changed when installing Python.

**Action version:**
actions/setup-python@v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
 3.10

**Repro steps:**  
workflows/main.yml
``` 
name: win-python-build-workflows
on:
  pull_request:
    types: [opened, reopened]
jobs:
  workflows-test:
    runs-on: self-hosted
    steps:
      - shell: pwsh
        run: |
          "C:\Program Files\PowerShell\7" >> $env:GITHUB_PATH
          $ErrorView = "NormalView"
          
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: print github env
        run : echo ${core.addPath}
        
      - name: Set up Python 3.10
        uses : actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          RUNNER_TOOL_CACHE: /opt/hostedtoolcache
          shell: pwsh -command ". '{0}'"
        
defaults:
  run:
    shell: pwsh

```

power shell version , power shell core version
![image](https://user-images.githubusercontent.com/65532694/218030708-13d397bb-3e32-4ffe-ba2a-fc0db0763347.png)

<img width="798" alt="제목 없음" src="https://user-images.githubusercontent.com/65532694/218026865-37954173-8490-4216-a7c9-eb6b011ffa15.png">

![image](https://user-images.githubusercontent.com/65532694/218027911-b19cdbd7-effe-4763-92b6-cc93ecdd0a30.png)

**Expected behavior:**
1. setup-python runs as  C:\WINDOWS\system32\windowsPowerShell\v1.0\powershell.exe
2. i want setup-python run as C:\Program Files\powerShell\7\pwsh.EXE - command ".'{0}'"
3. Why does this happen?
    ->"Remove-Item : Cannot find path 'C:\opt\hostedtoolcache\Python\3.10.10\x64.complete' because it does not exist."

**Actual behavior:**
A description of what is actually happening.
