### ISSUE TITLE
PyPy3 ImportError lzma

### ISSUE THREAD

**Issue by aamalev** [actions/setup-python#61]
platform linux -- Python 3.6.9[pypy-7.3.0-final]

......
    lzma = __import__('lzma')
/opt/hostedtoolcache/PyPy/3.6.9/x64/lib-python/3/lzma.py:27: in <module>
    from _lzma import *
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    import threading
    import functools
    import collections
    import weakref
    import sys
    import io
    import __pypy__
    
>   from _lzma_cffi import ffi, lib as m
E   ImportError: /opt/hostedtoolcache/PyPy/3.6.9/x64/lib_pypy/_lzma_cffi.pypy36-pp73-x86_64-linux-gnu.so: undefined symbol: lzma_index_stream_padding

/opt/hostedtoolcache/PyPy/3.6.9/x64/lib_pypy/_lzma.py:15: ImportError

**Comment by konradpabjan** [comment]
Hi @aamalev 

Could you create a minimally reproducible example with YAML along with a link to a failing workflow? It will be help debug the issue to determine if any action needs to be taken

**Comment by miketimofeev** [comment]
Hey @konradpabjan! We've faced the same issue with lzma. The repro is quite simple, but I guess the issue is with the PyPy3 itself(at least on Ubuntu, macOS works fine)
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "pypy3"
      - name: Import lzma
        run: python -c "import lzma"
```
