### ISSUE TITLE
Tool cache Python errors when run in a container

### ISSUE THREAD

**Issue by peter-evans** [actions/setup-python#62]
Is this expected behaviour when running inside a container? `/opt/hostedtoolcache` is volume mounted to `/__t`, so it seems like the intention is that tools in the cache *can* be used in a container.

```
on: push
jobs:
  pythonInContainer:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.x'
      - run: python --version
```

![image](https://user-images.githubusercontent.com/18365890/74401684-63211f80-4e65-11ea-96ea-14490e357999.png)
