### ISSUE TITLE
PyPi setup install is broken (again)

### ISSUE THREAD

**Issue by melroy89** [actions/setup-python#620]
**Description:**

Unable to install pypi Python using your setup action.. 

```
<html>
  <head><title>502 Bad Gateway</title></head>
  <body bgcolor="white">
  <center><h1>502 Bad Gateway</h1></center>
  <hr><center>nginx/1.14.0 (Ubuntu)</center>
  </body>
  </html>
```

**Action version:**

v4

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Repro steps:**  

Just use your `actions/setup-python@v4`  with `pypy-3.9`

```
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: pypy-3.9
          check-latest: true
          cache: "pip"
```

**Expected behavior:**

No 502 http errors.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/628926/223854649-6222f46e-6908-44a9-b718-5d9e6ce94a8e.png)

**Comment by MaksimZhukov** [comment]
Hello @melroy89 !
I have not been able to reproduce the issue with the steps you provided. Could you please provide us with the link to the public repository where the issue appears?
Please also try to specify version like this:
```yml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          check-latest: true
          cache: "pip"
```
