### ISSUE TITLE
python 3.11 not working when exporting to GITHUB_PATH

### ISSUE THREAD

**Issue by codectl** [actions/setup-python#623]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

I have the following which runs for python 3.11 on ubuntu-latest and macOS-latest:

```yaml
    - name: Update PATH
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
```

I am trying to update that path but it is not working.

It does work for older python versions (3.8, 3.9, 3.10).
