### ISSUE TITLE
Support reading Python version from Poetry `pyproject.toml`

### ISSUE THREAD

**Issue by Hongbo-Miao** [actions/setup-python#629]
Since Poetry has Python version defined in `pyproject.toml`

```toml
[tool.poetry.dependencies]
python = "3.11.x"
```

It would be great to support reading Python version from Poetry `pyproject.toml`.

Something like

```yaml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: path/to/pyproject.toml
```

FYI, today **actions/setup-go** supports similar way like [this](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file):

```yaml
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: path/to/go.mod
```

(Inside **go.mod**, it has Go version defined)

Thanks! 😃
