### ISSUE TITLE
Certificate has expired (Python 3.10.4, linux)

### ISSUE THREAD

**Issue by s-mcqueen** [actions/setup-python#631]
**Description:**
We're seeing a consistent "certificate has expired" on Ubuntu runners. We don't see this in the browser when we try to hit this link.

Here's the action we are using:

```
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          cache: "pipenv"
          cache-dependency-path: |
            infra/Pipfile.lock
```

And here's the error we see:

```
Run actions/setup-python@v3
  with:
    python-version: 3.10.4
    cache: pipenv
    cache-dependency-path: infra/Pipfile.lock
  
    token: ***
Version 3.10.4 was not found in the local cache
Version 3.10.4 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.10.4-2650226428/python-3.10.4-linux-22.04-x64.tar.gz"
certificate has expired
Waiting 16 seconds before trying again
certificate has expired
Waiting 14 seconds before trying again
Error: certificate has expired
```

**Action version:**
`actions/setup-python@v3`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
3.10.4

**Repro steps:**  
Run the setup-python@v3 we see above

**Expected behavior:**
Python should get downloaded and cached.

**Actual behavior:**
Python not downloaded
