### ISSUE TITLE
Running `python` on MacOS runner is always 2.7

### ISSUE THREAD

**Issue by stefmolin** [actions/setup-python#632]
**Description:**
Despite specifying the version of Python to be 3.x, the MacOS runner is interpreting `python` as Python 2.7.

**Action version:**
4

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

3.9, 3.10, 3.11

**Repro steps:**  
```yaml
jobs:
  build:
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
        fail-fast: false
        matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
            python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools --upgrade
          python -m pip install .

      - name: Diagnostics
        run: |
          which python
          python -m pip --version
```

**Expected behavior:**
The logic works on the Linux and Windows runners because `python` is properly set up. I would expect `python` on MacOS to also use the version that was set up with the action.

**Actual behavior:**
`python` on the MacOS runner is using 2.7:
```output
Run which python
  which python
  python -m pip --version
  shell: /bin/bash -el {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.11.[2](#step:5:2)/x64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/[3](#step:5:3).11.2/x6[4](#step:5:4)/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.2/x[6](#step:5:6)4
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.2/x64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.11.2/x64
/usr/local/bin/python
pip 20.3.4 from /Library/Frameworks/Python.framework/Versions/2.[7](#step:5:7)/lib/python2.7/site-packages/pip (python 2.7)
```
