### ISSUE TITLE
Rate limit token does not work on GHE

### ISSUE THREAD

**Issue by mvs5465** [actions/setup-python#638]
**Description:**
Using the `token` parameter for the Github Action, the token is not used. 

**Action version:**
v4

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Self-hosted

**Tools version:**
3.x

**Repro steps:**  
Add a Github Action workflow like this to your Github Enterprise repository:

```
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          token: ${{ secrets.DOTCOM_TOKEN }}
          python-version: '3.x'
```

Then also add https://github.com/actions/setup-python/pull/510#discussion_r982394709 using the same token variable.

We can tell by the rate-limit response that the token has not been used. 

**Expected behavior:**

Expect action to use token.

**Actual behavior:**

`API rate limit exceeded for <ip>`

We confirmed using the rate limit query that the rate limit quotas have not changed, and thus the token has not been used by the action.
