### ISSUE TITLE
Regression: Pypy version must be specified explicitly

### ISSUE THREAD

**Issue by toonn** [actions/setup-python#646]
**Description:**
Potentially a regression.
While Python versions can be specified ambiguously, e.g. `3.x`, at some point this behavior was lost for Pypy versions.

**Action version:**
v4 (Believe it's also the case for v3 and v2)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
To reproduce all you need is an action that tries to install an ambiguous Pypy version:

```
name: Pypy tests

on: push

jobs:
  test_pypy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [pypy2, pypy3]
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
 ```

I've also tried `pypy3.x`.

**Expected behavior:**
This used to work and is still possible for CPython version specifications.

**Actual behavior:**
```
test_pypy (pypy2)
Invalid format of Python version for PyPy. Python version should be specified in format 'x.y'. See README for examples and documentation.
```
