### ISSUE TITLE
macOS runners have different min versions for varying Python versions

### ISSUE THREAD

**Issue by pyrito** [actions/setup-python#654]
**Description:**
It seems that the python versions in the macOS runners have different min supported versions. This is important for some workflows which rely on this information when creating wheels that should be compatible with older macOS versions.

**Action version:**
4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
First have a CI job that allows upterm access.
```
name: build
on:
  pull_request:
    branches: [main]
jobs:
  build_wheel:
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --tags origin
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
```
You can then log into CI and see then take a look at the min versions via otool:

```bash
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.8.16/x64/python | grep 'minos'
    minos 10.15
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.9.16/x64/python | grep 'LC_VERSION_MIN_MACOSX'
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.9.16/x64/python | grep 'minos'
    minos 11.7
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.10.11/x64/python | grep 'minos'
    minos 11.7
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.11.3/x64/python | grep 'minos'
Mac-1681914259831:soda runner$ otool -l /Users/runner/hostedtoolcache/Python/3.11.3/x64/python 
      ....
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 12.1
      ....
```

**Expected behavior:**
I would expect the versions of python to be compatible back to macOS 10.9 or something along those lines, but that doesn't seem to be the case. When I create a conda environment and use otool I can see that the min macOS version is indeed 10.9.  
**Actual behavior:**
Backwards compatible versions of the python interpreter are newer than expected for 3.8, 3.9, 3.10, but then older again for 3.11.
