### ISSUE TITLE
Install with package manager 

### ISSUE THREAD

**Issue by Cologler** [actions/setup-python#659]
**Description:**

Currently, if we use poetry, we have to write two steps:

``` yaml
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ...
          cache: poetry
```

I hope this can be easier:

``` yaml
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ...
          package-manager: poetry@{version}
          cache: poetry
```
