### ISSUE TITLE
The version '3.6.15' with architecture 'x64' was not found for Ubuntu 22.04.

### ISSUE THREAD

**Issue by zrhoffman** [actions/setup-python#665]
**Description:**
All Python 3.6 and 3.5 versions fail to install on Ubuntu, and all versions except 3.5.9, 3.6.7 and 3.6.8 fail to install on Windows.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

- 3.6.15
- 3.6.14
- 3.6.13
- 3.6.12
- 3.6.11
- 3.6.10
- 3.6.9
- 3.6.8
- 3.6.7
- 3.5.10
- 3.5.9
- 3.5.4

**Repro steps:**  
1. Commit and push this workflow:
   
   ```yaml
   name: Workflow that sets up Python 3.6 and 3.5
   on: { push: }
   jobs:
     setup-python-36:
       strategy:
         matrix:
           os: [ ubuntu, macos, windows ]
           python-version: [ 3.6.15, 3.6.14, 3.6.13, 3.6.12, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.5.10, 3.5.9, 3.5.4 ]
       continue-on-error: true
       runs-on: ${{ matrix.os }}-latest
       steps:
         - name: Set up Python ${{ matrix.version }}
           uses: actions/setup-python@v4
           with:
             python-version: ${{ matrix.python-version }}
   ```

2. Check workflow run or see https://github.com/zrhoffman/setup-python-3.6/actions/runs/4942488853

**Expected behavior:**
Python 3.6 or 3.5 is set up

**Actual behavior:**
All versions fail on Ubuntu, all versions succeed on macOS, and versions except 3.5.9, 3.6.7 and 3.6.8 fail on Windows:

Python version | Ubuntu | macOS | Windows
---------------|--------|-------|--------
3.6.15 |❌      |✔️      |❌
3.6.14 |❌      |✔️      |❌
3.6.13 |❌      |✔️      |❌
3.6.12 |❌      |✔️      |❌
3.6.11 |❌      |✔️      |❌
3.6.10 |❌      |✔️      |❌
3.6.9 |❌      |✔️      |❌
3.6.8 |❌      |✔️      |✔
3.6.7 |❌      |✔️      |✔
3.5.10 |❌      |✔️      |❌️
3.5.9 |❌      |✔️      |❌️
3.5.4 |❌      |✔️      |✔️

Example failure output for Python version 3.6.15 and platform Ubuntu:

```
Run actions/setup-python@v4
  with:
    python-version: 3.6.15
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
Installed versions
  Version 3.6.15 was not found in the local cache
  Error: The version '3.6.15' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
