### ISSUE TITLE
Add Python 3.12.0 beta

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#677]
**Description:**

Python 3.12 beta has been released on 22 May 2023 but isn't yet available for GitHub Actions.

The Python release manager asked maintainers to test the beta, so it would be great to be able to test on CI:

> We **strongly encourage** maintainers of third-party Python projects to test with 3.12 during the beta phase and report issues found to [the Python bug tracker ([Issues · python/cpython · GitHub](https://github.com/python/cpython/issues)) as soon as possible. While the release is planned to be feature complete entering the beta phase, it is possible that features may be modified or, in rare cases, deleted up until the start of the release candidate phase (Monday, 2023-07-31). Our goal is to have no ABI changes after beta 4 and as few code changes as possible after 3.12.0rc1, the first release candidate. To achieve that, it will be **extremely important** to get as much exposure for 3.12 as possible during the beta phase.

* https://discuss.python.org/t/python-3-12-beta-1-and-feature-freeze-is-here/26982?u=hugovk

**Action version:**

v4 = v4.6.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

`3.12-dev`

https://github.com/actions/python-versions/blob/main/versions-manifest.json

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

Set up Python using `3.12-dev`:

```yml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [
          "3.12-dev",
        ]
        os: [
          windows-latest,
          macOS-latest,
          ubuntu-latest,
        ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
```

https://github.com/hugovk/test/actions/runs/5057309868/workflow

**Expected behavior:**

3.12.0 beta 1 is installed:

* https://peps.python.org/pep-0693/#schedule

**Actual behavior:**

3.12.0 alpha 7 is installed:

* https://github.com/hugovk/test/actions/runs/5057309868/jobs/9075908996
* https://github.com/hugovk/test/actions/runs/5057309868/jobs/9075909144
* https://github.com/hugovk/test/actions/runs/5057309868/jobs/9075909318

There's no 3.12 beta in https://github.com/actions/python-versions/blob/main/versions-manifest.json
