### ISSUE TITLE
Python3.9 on aarch64 for macOS 13.4.1.

### ISSUE THREAD

**Issue by tvorogme** [actions/setup-python#696]
**Description:**
  Error: The version '3.9' with architecture 'arm64' was not found for macOS 13.4.1.

**Action version:**
 'actions/setup-python@v4' (SHA:bd6b4b6205c4dbad673328db7b31b7fab9e241c0)

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
(aarch64, macOS, Python3.9)

**Repro steps:**  
```
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
```

**Expected behavior:**
Successfully installed python

**Actual behavior:**
Error message

**Comment by dusan-trickovic** [comment]
Hello, @tvorogme ! Thank you for creating this issue, we'll investigate it and see what can be done :)

**Comment by tvorogme** [comment]
@dusan-trickovic hey! When approximately can we expect a fix? I really need this container for cross-platform distribution of the package.

**Comment by dusan-trickovic** [comment]
Hello again, @tvorogme ! I just wanted to check in with you and ask you if you could please try using Python version such as `3.10.11` in your workflow? From the description of your problem, it seems as though that version of Python just simply doesn't exist for your specific architecture in the versions repository (while there is an `arm64` option for `3.10.11` for `darwin`).

Newer versions (such as `3.11` and `3.12` `alpha` and `beta`) also seem to have support for `arm64`, but I suggested `3.10.11` as it is the closest to the one you need. If it won't affect your own personal requirements for the project, I would suggest trying to use the suggested version and seeing if that fixes the error you've encountered.

If you encounter any more issues (similar to this or otherwise), please don't hesitate to reach out again. On the other hand, if this solved your issue, you can also let us know about it so that we can close it.

Thank you very much for your cooperation :)

**Comment by tvorogme** [comment]
@dusan-trickovic hey! Glad you right back.

Thanks for the idea, but it doesn't work for me. We are developing a package that should be available on: Windows / Linux / macOS. Since we work with pybind11 we are tied to the major python releases, so we support py3.9 / py3.10 / py3.11. If we make a package for py3.10 it means it won't work for py3.9.

As a temporary solution, I made a [separate workflow](https://github.com/disintar/tonpy/blob/main/.github/workflows/wheels.yml#L128) just for macOS *aarch64* / *x86_64* that installs python3.9 from brew, because it's not working from `actions/setup-python`. But it's very ugly. 

Your workflow works for all other versions, and it's very cool.

You also can look at [status of python versions](https://devguide.python.org/versions/), the Python3.9 is not `end-of-life` status.

<img width="910" alt="Screenshot 2023-07-15 at 11 01 42 AM" src="https://github.com/actions/setup-python/assets/19264196/b868d612-5239-4931-9941-92f34a12a200">

**Comment by dusan-trickovic** [comment]
Hello again @tvorogme ! I just wanted to drop an update here and say that, at this time, we only have `arm64` support for versions `3.10` and later. Therefore, although `3.10` and `3.11` fit this criteria, `3.9` unfortunately doesn't, though we will investigate that too in the future.

Thank you very much for your time and cooperation :)

**Comment by richard-scott** [comment]
I can't believe this is still a problem 3 years after Python started supporting the M1 architecture.

However, it's not just Apple hardware having problems as I have issues with major version numbers such as version '3.10' with architecture 'arm64' was not found for Debian 12.

**Comment by rwader-swi** [comment]
i'm getting the same for 3.9 on Debian 😞

**Comment by ianspektor** [comment]
For anyone else with this problem, we resolved to drop setup-python and just install python, pip, and poetry manually. Full working example here: https://github.com/google/temporian/blob/main/.github/workflows/publish.yaml

```
build-macos-arm:
    runs-on: macos-13-xlarge
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          brew update
          brew install python@${{ matrix.python-version }}

      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python${{ matrix.python-version }} get-pip.py

      - name: Install poetry
        run: pip install poetry
```
