### ISSUE TITLE
Error "Version 3.12 with arch x64 not found".

### ISSUE THREAD

**Issue by wchistow** [actions/setup-python#703]
In my file `.github/workflows/mypy.yml` I wrote:

```yml
...

jobs:
  build:

    runs-on: ubuntu-latest  # OS - Ubuntu Linux
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Python version - 3.12

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    ...
```

And got an error `Version 3.12 with arch x64 not found`:

```
Run actions/setup-python@v3
  with:
    python-version: 3.12
    token: ***
Version 3.12 was not found in the local cache
Error: Version 3.12 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
