### ISSUE TITLE
Add Python 3.12.0rc1

### ISSUE THREAD

**Issue by mr-c** [actions/setup-python#712]
**Description:**
Python 3.12 beta has been released on 2023-08-06 but isn't available for GitHub Actions.

**Justification:**
The Python release manager asked maintainers to test the RC, so it would be great to be able to test on CI:

> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0. Any binary wheels built against Python 3.12.0rc1 will work with future versions of Python 3.12. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).

**Comment by dmitry-shibanov** [comment]
Hello @mr-c. Thank you for your report. We'll take a look on it.

**Comment by dmitry-shibanov** [comment]
Hello @mr-c. The python 3.12.0-rc.1 was added. You can try to use it by this snippets:
```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.0-rc.1
```

or

```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          allow-prereleases: true
```
