### ISSUE TITLE
How cache key is computed

### ISSUE THREAD

**Issue by copdips** [actions/setup-python#732]
Hi

I'm not a ts developer, could anybody give a hint how the cache key is computed ?

With standard `actions/cache`, we can [compute the key manually](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action) by using the function `hashFiles()`, but `actions/setup-python` has its own way to compute it.

I'm using the action like this:

```yaml
- name: Set up Python ${{ env.python_version }}
  uses: actions/setup-python@v4
  with:
    python-version: ${{ env.python_version }}
    cache: pip

- name: pip install
  run: |
    pip install -U pip
    pip install -r requirements/requirements.txt
    pip install -r requirements/requirements-dev.txt
```

from the actions log, we can see that:

```bash
Cache restored from key: setup-python-Linux-22.04-Ubuntu-python-3.10.13-pip-308f89683977de8773e433ddf87c874b6bd931347b779ef0ab18f37ecc4fa914
````

I would like to know how the `308f89683977de8773e433ddf87c874b6bd931347b779ef0ab18f37ecc4fa914` is computed
