### ISSUE TITLE
Add Python 3.13.0 alpha 1 

### ISSUE THREAD

**Issue by ezio-melotti** [actions/setup-python#742]
**Description:**
Python 3.13.0 alpha 1 was recently released: https://www.python.org/downloads/release/python-3130a1/

**Justification:**
Maintainers can start testing their projects with it once it's added.

**Are you willing to submit a PR?**
Yes, if you tell how to do it.

**Comment by dmitry-shibanov** [comment]
Hello @ezio-melotti. We've added Python 3.13.0-alpha.1 to python-versions. You can try to use these snippets:
 - allow-prereleases input
```yaml
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13
        allow-prereleases: true
```
 - dev syntax
 
```yaml
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13-dev
```

 - Specify full version
 
 ```yaml
     - uses: actions/setup-python@v4
      with:
        python-version: 3.13.0-alpha.1
 ```
 
 For now I'm going to close the issue.
