### ISSUE TITLE
setup-python overrides PK_CONFIG_PATH

### ISSUE THREAD

**Issue by fizyk** [actions/setup-python#746]
**Description:**
I'm attempting to run tests on MacOs that require mysqlclient installed. Version 2.2 of mysqlclient relies on pkg-config, runs `pkg-config --exists mysqlclient` during installation.
However even if I point PK_CONFIG_PATH to the mysqlclient pk config configuration, setup-python overrides it's contents, which makes the mysqlclient installation fail on macos.

This issue is non existing on ubuntu

**Action version:**
v4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python (Any version)
mysqlclient 2.2.0

**Repro steps:**  
```
  tests-mysqlient-macosx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: 8.0
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Update PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/mysql@8.0/lib/pkgconfig" >> "$GITHUB_ENV"
    - name: Check MySQL Version
      run: mysqld --version
    - name: Check pkg-config --exists mysqlclient
      run: pkg-config --exists mysqlclient
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install mysqlclient
      run: pip install mysqlclient==2.2.0
```

**Expected behavior:**
Installation succedes,

**Actual behavior:**
Installation fails on pkg-config being unable to read mysqlclient configuration
