### ISSUE TITLE
The version '3.XX' with architecture 'x64' was not found for this operating system.

### ISSUE THREAD

**Issue by finda-yeongjo** [actions/setup-python#750]
**Description:**

The module cannot be used on Amazon Linux self-hosted runner.

**Action version:**

Current runner version: '2.304.0'

/etc/amazon-linux-release:Amazon Linux release 2023 (Amazon Linux)
/etc/os-release:NAME="Amazon Linux"
/etc/os-release:VERSION="2023"
/etc/os-release:ID="amzn"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="2023"
/etc/os-release:PLATFORM_ID="platform:al2023"
/etc/os-release:PRETTY_NAME="Amazon Linux 2023"
/etc/os-release:ANSI_COLOR="0;33"
/etc/os-release:CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
/etc/os-release:HOME_URL="https://aws.amazon.com/linux/"
/etc/os-release:BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
/etc/os-release:SUPPORT_END="2028-03-01"
/etc/system-release:Amazon Linux release 2023 (Amazon Linux)

**Platform:**
- [x] AmazonLinux
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
 Any Python3.XX version

    
**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

```
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-2

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"  #All versions from 3.6 to 3.13 are not the same.
          cache: "pip"

      - name: test
        run: |
          mkdir test
          pip install -t test requests
```

**Expected behavior:**
successful pip install

**Actual behavior:**
```
Run actions/setup-python@v4
Installed versions
  Version 3.12 was not found in the local cache
  Error: The version '3.12' with architecture 'x64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by dmitry-shibanov** [comment]
Hello @finda-yeongjo. Thank you for your report. I think it is an expected behaviour because Python versions 3.x was built for Ubuntu 18.04 - 22.04 that is why the action can't find the proper version. 

I'm going to close the issue because for now it is an expected behaviour and we have feature requests to add support for different distributions and architectures.

**Comment by kishaningithub** [comment]
@dmitry-shibanov Can you point towards where the feature request to support other linux flavours like amazon linux exists?

**Comment by kishaningithub** [comment]
I think i found it https://github.com/actions/setup-python/issues/460

**Comment by will-e-yams** [comment]
@kishaningithub,
I'm trying to run GitHub Actions locally with `act`, but I'm not able to use python 3.13 on ubuntu-latest (at the time 24.04.3). OS is Mac. Is this issue related?

```

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        platform: linux
        architecture: arm64

    # - name: Install uv
    #   uses: astral-sh/setup-uv@v6

    # - name: Test package
    #   run: |
    #     uv pip install pytest
    #     uv pip run pytest
```
