### ISSUE TITLE
Cannot run the action on Raspberrypi model 4b arm64

### ISSUE THREAD

**Issue by ashishjullia** [actions/setup-python#768]
**Description:**
I'm trying to run this action on my self-hosted GitHub runner, here the runner agent is running on my raspberrypi4b and i want to leverage the container's ephemeral property and that is why I'm further using an ubuntu arm64-based image (https://hub.docker.com/r/ashishjullia19/pi4-runner-image) but for some reason I cannot get it working, maybe the architecture is not supported and I also checked: [raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) and atm can't conclude whether the pi is supported or not, and here is my `uname -a`:
`Linux 9c68412d62e5 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 aarch64 aarch64 GNU/Linux`

And this is my workflow:
```yaml
on: 
  workflow_dispatch:
  push:
    branches: 
      - main

env:
  DEPLOY_STAGE: staging
  WORKING_CODE_REPO: ${{ github.event.repository.name }}

jobs:
  deploy-staging:
    runs-on: [self-hosted, pi42]
    container:
      image: ashishjullia19/pi4-runner-image 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
```

**Action version:**
Specify the action version
`uses: actions/setup-python@v4`

**Platform:**
- [x] Ubuntu (arm based container image)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
Need to have a pi or similar architecture based system/board and use the workflow specified^.

**Expected behavior:**
A description of what you expected to happen.
It should just directly work.

**Actual behavior:**
A description of what is actually happening.
Getting error:
```bash
Run actions/setup-python@v4
/usr/bin/docker exec  fcd3a7bdef6e9e1c1af90926d25a405a690187ecb181b99edf44aa7f72330a99 sh -c "cat /etc/*release | grep ^ID"
Installed versions
  Version 3.10.[11](https://github.com/geekylaneorgcf/sirfdeals.com/actions/runs/6912022410/job/18807298121#step:4:12) was not found in the local cache
  Error: The version '3.10.11' with architecture 'arm64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
