### ISSUE TITLE
Feature proposal: Integrate dependency support

### ISSUE THREAD

**Issue by alexjurkiewicz** [actions/setup-python#77]
I think a most users of this action run an "install dependencies" step immediately after. I think it would improve the developer experience if the "install dependencies" step was integrated into this action.

Current workflow:

```yaml
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
```

Option 1: Support installing packages with pip

```yaml
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        pip-install: -r requirements.txt

        # or if you use a different package manager...
        # pip-install: pipenv
    # - name: Install dependencies
      # run: pipenv install
```

Option 2: Add full support for all package managers
```yaml
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        # Pip
        package-manager: pip
        package-manager-args: -r requirements.txt
        # Pipenv
        package-manager: pipenv
        package-manager-args: --pre --dev --deploy
        # Poetry
        package-manager: poetry
        package-manager-args: --no-dev
```

What do you think? Option 1 is much smaller in scope than option 2, but I think both would be low maintenance (Python has a lot of package managers, but not _that_ many).

**Comment by zyv** [comment]
We would very much like to use this action, because it will be a huge speed improvement as compared to pulling our pre-baked CI docker image. However, we absolutely need dependency management support - and specifically poetry. So sadly we can't switch until some kind of poetry support is implemented...

**Comment by omBratteng** [comment]
I probably wouldn't install the project dependencies in the same step as setting up python, but it would be nice if the action included the major package managers. Like the node action includes yarn.
Although I think it would be better if the package manager was added at the image layer, which yarn is.
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by omBratteng** [comment]
I opened a PR that adds poetry to the virtual environments
https://github.com/actions/virtual-environments/pull/3293

**Comment by zyv** [comment]
We ended up creating an action to install Poetry after setting up Python - it's still faster than pulling a complete pre-baked docker image with the operating system:

https://github.com/moneymeets/action-setup-poetry

Adding poetry to the base action images would of course only make it better!

**Comment by omBratteng** [comment]
They closed my PR, as they think because poetry only takes a few seconds to install, it is not needed in the action image, and using actions is better.

**Comment by brcrista** [comment]
My usual take on this is that actions should follow the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy).  But in this case, by adding built-in dependency caching, we’ve already tightly coupled with the popular Python package managers.  We'd welcome a PR for this if anyone wants to take that on.

**Comment by v-gowridurgad** [comment]
Hi everyone,
We’ve raised [PR #1201](https://github.com/actions/setup-python/pull/1201) to address the above requirement by introducing support for a new pip-install input, allowing dependencies to be installed directly via `actions/setup-python`. This implementation currently supports only pip. Please validate it against the requirement and confirm. Any feedback or suggestions would be welcome.
Thanks in advance!

**Comment by v-gowridurgad** [comment]
Hi everyone,
We’re excited to to share that this feature has been implemented in [PR #1201](https://github.com/actions/setup-python/pull/1201). This update introduces support for a new pip-install input, allowing dependencies to be installed directly via actions/setup-python.
To start using this feature, you can use the `actions/setup-python@main` branch in your workflows for now, and the changes will be reflected in the upcoming releases.
We’ll be closing this issue. Please feel free to reach out if you have any further concerns or need additional assistance.

**Comment by zyv** [comment]
@gowridurgad It would be great to provide an example in the README of how to use the new input with `pyproject.toml`. I assume this should work without any issues. No one wants to deal with `requirements.txt` in 2025!

**Comment by v-gowridurgad** [comment]
Hi @zyv, Thanks for the feedback!
Currently, the pip-install input feature has been implemented to support only pip, and pip does not read or install dependencies directly from pyproject.toml (e.g. [tool.poetry.dependencies] ).

This behaviour is a known limitation. For reference, please see:

- [pypa/pip#8049](https://github.com/pypa/pip/issues/8049) 
- [pypa/pip#11584](https://github.com/pypa/pip/issues/11584)

Support for other package managers like Poetry or Pipenv is not included yet, but we’re definitely considering adding it in the future based on community demand.
For now, if you're using Poetry or another package manager, you’ll need to run those install commands in a separate step after setting up Python.

We appreciate your understanding and contributions.

**Comment by zyv** [comment]
> Currently, the pip-install input feature has been implemented to support only pip, and pip does not read or install dependencies directly from pyproject.toml (e.g. [tool.poetry.dependencies] ).
> 
> This behaviour is a known limitation.

@gowridurgad this is not correct; `pip` does support the installation from standard `pyproject.toml` key (`project.dependencies`) and was able to do so for a long time now. The only downside is that it installs the project itself in addition to the dependencies, but for most projects this actually isn't an issue. The issue of not installing the project itself is tracked here:

* https://github.com/pypa/pip/issues/11440

The syntax for `pip` to install the dependencies from `pyproject.toml` is `pip install .` - if you can support this, then most projects using the standard layout (e.g. because they use `uv`) will be automatically supported.

I only find it logical to allow `pip install .` with this action if `-r` has been implemented to avoid the need of pulling in more actions and/or writing more commands.

**Comment by v-gowridurgad** [comment]
Hi @zyv, thank you for following up. You are absolutely correct, pip can install dependencies specified in the standard `[project.dependencies] `section of pyproject.toml via `pip install .`.

My previous response was specifically referring to `[tool.poetry.dependencies]`, which pip does not natively support for reading or installing dependencies.

To clarify, the pip-install input does support `pip install . `and will install everything defined under` [project.dependencies]` in pyproject.toml.
The following step can be used in a workflow to install the dependencies:

```
name: Set up Python
uses: actions/setup-python@main
with:
  python-version: '3.11'
  cache: pip
  pip-install: .
```

If there are any further suggestions or feedback, please let us know.
