### ISSUE TITLE
How can we uninstall a python version?

### ISSUE THREAD

**Issue by SeaOtocinclus** [actions/setup-python#794]
Is it possible to install and uninstall python version with the setup-python action

I.e does the following will first install python 3.8, then remove it to install 3.11 or does both python version will be available on the GitHub machine?

I'm asking this since I would like to run some steps of a workflow with python 3.11 and then move to another python version for the rest

```
- name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

- name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
```

**Comment by aparnajyothi-y** [comment]
Hello @SeaOtocinclus, Thank you for creating this issue, we will investigate further and see what can be done :)

**Comment by priyagupta108** [comment]
Hi @SeaOtocinclus 👋,
The `setup-python` action in GitHub Actions allows you to specify and set up different versions of Python for your workflow. Specified Python versions (e.g., 3.8 and 3.11) will be available in the runner's environment during the workflow run.
To switch between Python versions within the same workflow, you can use the setup-python action multiple times in different steps. Each call to setup-python will set the specified Python version as the active version for the subsequent steps.
Here's an example of how you can achieve this:
```yaml
name: Python workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Run steps with Python 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  
      - name: Run tests
        run: pytest
        
      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Run steps with Python 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  
      - name: Run tests
        run: pytest
   ```
