### ISSUE TITLE
Is `python.h` missing when `allow-prereleases=true`?

### ISSUE THREAD

**Issue by LecrisUT** [actions/setup-python#798]
**Description:**
I have encountered an issue when trying to install `numpy` with `--pre` and `allow-prereleases`
```
            Program python found: YES (/__t/Python/3.13.0-alpha.3/x64/bin/python3)
            Found pkg-config: /usr/bin/pkg-config (1.8.0)
            Run-time dependency python found: YES 3.13
            Has header "Python.h" with dependency python-3.13: NO
      
            ../../meson.build:44:2: ERROR: Problem encountered: Cannot compile `Python.h`. Perhaps you need to install python-dev|python-devel
      
            A full log can be found at /tmp/pip-install-5mnm8us2/numpy_6ddaeaacec6a4d6683a0ccbf5c087aa1/.mesonpy-n575_lw_/build/meson-logs/meson-log.txt
```

Example run:
https://github.com/spglib/spglib/actions/runs/7594600344/job/20686299366?pr=362

**Action version:** `v5`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python version: `3.13`

**Other notes:**  
- I am running a Fedora container on top of this with:
  ```yaml
      - name: Patch /etc/lsb-release for experimental python
        # Mimic Ubuntu in order to be able to download experimental python
        run: |
          echo -en 'DISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=22.04\nDISTRIB_CODENAME=jammy\nDISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"' >> /etc/lsb-release
  ```
