### ISSUE TITLE
Feature request: Do not fail when caching on non-Python repositories

### ISSUE THREAD

**Issue by kdeldycke** [actions/setup-python#807]
**Description:**

I am trying to use `setup-python` in a non Python repository. But I soon as I activate the cache, it ends up with this error:

```
Run actions/setup-python@v5.0.0
  with:
    python-version: 3.12
    cache: pip
Installed versions
  Successfully set up CPython (3.12.1)
Error: No file in /home/runner/work/awesome-iam/awesome-iam matched to
[**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```

Thats because the project I check out just before has no `**/requirements.txt` or `**/pyproject.toml` file.

And the reason it has no such file is that the `actions/checkout` and `setup-python` steps are located in a reused workflow.

**Action version:**
`setup-python@v5.0.0`

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Any version of Python.

**Repro steps:**  

Here is the source code of my reused workflow: https://github.com/kdeldycke/workflows/blob/f50130aabec1fe713a548e3296f723732c79a178/.github/workflows/lint.yaml#L26-L35

And here is the result of this invokation: https://github.com/kdeldycke/awesome-iam/actions/runs/7592900227/job/20682781487#step:3:13

**Expected behavior:**
I expect `setup-python` not to fail in the absence of a `**/requirements.txt` or `**/pyproject.toml` file.

**Actual behavior:**
The step fails with the following message:

```
Run actions/setup-python@v5.0.0
  with:
    python-version: 3.12
    cache: pip
Installed versions
  Successfully set up CPython (3.12.1)
Error: No file in /home/runner/work/awesome-iam/awesome-iam matched to
[**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```

**Comment by kdeldycke** [comment]
Maybe this issue will be addressed by:
- https://github.com/actions/setup-python/issues/751
- https://github.com/actions/setup-python/pull/762

**Comment by kdeldycke** [comment]
To bypass current `setup-python` behavior, I created a step that is adding an empty `requirements.txt` if missing:

```yaml
      - name: Hack setup-python cache
        # XXX Create an empty requirements.txt if this file (or pyproject.toml) doesn't exist.
        # This work around and issue with setup-python for non-Python projects, which ends up with ends up
        # with this error:
        #
        #   Run actions/setup-python@v5.0.0
        #     with:
        #       python-version: 3.12
        #       cache: pip
        #   Installed versions
        #     Successfully set up CPython (3.12.1)
        #   Error: No file in /home/runner/work/awesome-iam/awesome-iam matched to
        #   [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
        #
        # This has been reported at: https://github.com/actions/setup-python/issues/807
        # In the future this might be addressed by: https://github.com/actions/setup-python/pull/762
        # or https://github.com/actions/setup-python/issues/751
        if: hashFiles('**/requirements.txt', '**/pyproject.toml') == ''
        run: |
          touch ./requirements.txt
```

Source: https://github.com/kdeldycke/workflows/commit/662a971ef26023b87498fae7613a740d9148f61b
