### ISSUE TITLE
Python <3.10 not available on new macOS M1 runners

### ISSUE THREAD

**Issue by agriyakhetarpal** [actions/setup-python#808]
**Description:**
Hello, we are trying to use `setup-python` with 3.8 and 3.9 on the new GitHub Actions macOS M1 runners (i.e., `runs on: macos-14`). It [does not appear to have Python 3.8 and 3.9](https://github.com/pybamm-team/PyBaMM/actions/runs/7715792984/job/21031128348) and the oldest darwin-arm64 Python version available in the [manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) is Python 3.10.11.

**Justification:**
Python 3.8 will not be EOLed until September/October this year, and Python 3.9 will be EOLed in 2025 therefore it should be a good idea to support these older Python versions, considering that they are supported on the darwin-x86_64 runner currently.

**Are you willing to submit a PR?**

I can try, thanks!

<hr>

Edit, 24/04/2024: at the time of writing, `macos-latest` now points to M1 arm64 runners (the architecture has changed) and this is being rolled out to GitHub Actions users. `macos-13` and `macos-12` still use amd64 (Intel).

For those looking for a quick workaround at this time, just exclude these from your matrices:

```yaml
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        runs-on: [ubuntu-latest, macos-13, macos-14, windows-latest]
        exclude:
          - python-version: "3.8"
            runs-on: macos-14
          - python-version: "3.9"
       		runs-on: macos-14
```
