### ISSUE TITLE
Optional ability to set the pypi repository and credentials to be used by pip on the runner

### ISSUE THREAD

**Issue by heckerdj** [actions/setup-python#814]
**Description:**
Add option with flags to allow users of the action to setup a pip.conf or pip.ini file with a private registry and credentials. 

Example usage:
```
 - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        repository: ${{ secrets.PYPI_REPO_URL }}
        username: ${{ secrets.PYPI_USER_TOKEN }}
        password: ${{ secrets.PYPI_PASS_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
```

**Justification:**
Using this action on ephemeral runners in environments where where companies have their own repository's to cache python dependencies. Great example (and my use case) is an enterprise nexus pypi repo where the open source pypi is blocked by firewall and dependencies need to be security scanned and placed in nexus prior to use internally. Having one setup-python action run and have the runner configured properly to use pip in any environment prevents the clutter having to manually write a pip.conf/pip.ini file every time we want to pip install. 

**Are you willing to submit a PR?**
Absolutely, I am new to typescript but would love to put in a PR if others agree the work is useful.
