### ISSUE TITLE
Bug: `"pip"` cache having nothing installed leads to post-run error

### ISSUE THREAD

**Issue by jamesbraza** [actions/setup-python#815]
**Description:**

I have this:

```yaml
        runs-on: 'ubuntu-latest'
        steps:
            -   uses: actions/setup-python@v5
                with:
                    python-version: '3.10'
                    cache: 'pip'
```

Bumping `python-version` from `'3.10'` to `'3.12'`, I am now getting this error during Post Run actions/setup-python@5:

```none
Post job cleanup.
Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip
```

**Action version:**

v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.10.13 to 3.12.1

**Expected behavior:**

I expect `setup-python` to somehow not error itself.

Seemingly related issues:
- https://github.com/actions/setup-python/issues/653
- https://github.com/actions/setup-python/issues/436

**Actual behavior:**

Here is the output of `Run actions/setup-python@v5`

```none
  with:
    python-version: 3.12
    cache: pip
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    ...
Installed versions
  Successfully set up CPython (3.12.1)
/opt/hostedtoolcache/Python/3.12.1/x64/bin/pip cache dir
/home/runner/.cache/pip
pip cache is not found
```

Here is the output of `Post Run actions/setup-python@5`:

```none
Post job cleanup.
Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip
```
