### ISSUE TITLE
pip not found for py > 3.10

### ISSUE THREAD

**Issue by braniii** [actions/setup-python#821]
Hi

I've rerun a workflow which passed 3mo ago and now it is failing. Using py3.11 or py3.12 I am not able to use `pip`. I've tried to upgrade to the latest action version, but this did not resolve the issue.

For all python version I receive the warnings described in #816 , so I guess that this is not the reason.

ps: sorry for this mess. GH mobile is terrible to create an issue.

**Action version:**
`v5`

**Platform:**
- [x] Ubuntu, docker
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

`3.11.x` and `3.12.x`

**Repro steps:**

The github action run can be found at https://github.com/braniii/prettypyplot/actions/runs/7985333672/job/21803629777

Using

``` yaml
name: Pytest with Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ctornau/latex
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -q --upgrade pip
        pip install -e .[testing]
```
it runs fine for py3.8-py3.10 and fails for py3.11 and py3.12 with

```yaml
Run python -m pip install -q --upgrade pip
python -m pip install -q --upgrade pip
pip install -e .[testing]
shell: sh -e {0}
env:
  PYTHON: 3.11
  pythonLocation: /__t/Python/3.11.8/x64
  PKG_CONFIG_PATH: /__t/Python/3.11.8/x64/lib/pkgconfig
  Python_ROOT_DIR: /__t/Python/3.11.8/x64
  Python2_ROOT_DIR: /__t/Python/3.11.8/x64
  Python3_ROOT_DIR: /__t/Python/3.11.8/x64
  LD_LIBRARY_PATH: /__t/Python/3.11.8/x64/lib
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/__w/_temp/c6a4603e-6961-4a87-813e-b1b19a9efd2e.sh: 2: pip: not found
Process completed with exit code 127.
```

**Expected behavior:**
Install pypi packages.

**Actual behavior:**
Raises
```
pip: not found
Process completed with exit code 127.
```
