### ISSUE TITLE
Support for `uv` Package Manager Caching

### ISSUE THREAD

**Issue by mgaitan** [actions/setup-python#822]
**Description**
Hey there! I'm suggesting we add caching support for the [uv package manager](https://github.com/astral-sh/uv) in setup-python. `uv` (`uv pip` command currently) is a drop-in replace for `pip`, using `requirements.txt` or any other input file that pip supports for dependencies definitions. The only difference is its cache directory: `setup-python` uses the output of `pip cache dir` to find the cache directory, but `uv` uses `uv cache dir` instead (see https://github.com/astral-sh/uv/pull/1734). It should be a straightforward addition that could help projects using `uv`.

**Justification**
uv is [10-100x faster](https://github.com/astral-sh/uv/blob/main/BENCHMARKS.md) than pip. There is a lot of interest from the community to use this new tool in CI environments (e.g https://github.com/astral-sh/uv/issues/1386) 

**Are you willing to submit a PR?**
Yep! Happy to help out and get my hands dirty with a PR to make this happen. However, I'm far of being a Typescript expert.

**Comment by nschloe** [comment]
You could also just cache the uv cache directory, e.g.,
```yaml
      - uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-uv
```

**Comment by akx** [comment]
Heh, I actually wrote a PR that implements this (before this issue, to boot), but no `actions/setup-python` maintainer seems to have seen it: https://github.com/actions/setup-python/pull/818

**Comment by alechouse97** [comment]
I've been playing with replacing `pip` with `uv` in our Gitlab CI pipeline, and it massively speeds up installing packages when you've got the cache. However, I've noticed that the `uv` cache is notably larger than the `pip` one (along with significantly more files), and the increase in Gitlab's cache time almost outweighs the shift to `uv`. Anyone else run into this?

**Comment by edgarrmondragon** [comment]
> I've been playing with replacing `pip` with `uv` in our Gitlab CI pipeline, and it massively speeds up installing packages when you've got the cache. However, I've noticed that the `uv` cache is notably larger than the `pip` one (along with significantly more files), and the increase in Gitlab's cache time almost outweighs the shift to `uv`. Anyone else run into this?

I think that's essentially the same that's reported in https://github.com/actions/setup-python/issues/822#issuecomment-1963717925

**Comment by kdeldycke** [comment]
Another strategy worth considering would be to cache the whole `.venv`, as demonstrated in this article: https://adamj.eu/tech/2023/11/02/github-actions-faster-python-virtual-environments/

**Comment by charliermarsh** [comment]
I did some analysis on the `uv-playground` repo described [here](https://github.com/actions/setup-python/issues/822#issuecomment-1963717925) by @acostapazo. Interestingly, the pip cache is even larger than the uv cache ([2.8 GB vs. 2.2 GB](https://github.com/charliermarsh/cache-playground/actions/caches)) though both are of course very large. Almost the entirety of the cache (at least in the uv case, I'm less familiar with pip's cache structure) are the enormous `torch` and `nvidia_cudnn_cu12` wheels.

My guess is that it's less efficient for uv to run through the cache in such cases (big pre-built wheels) than it is to install from scratch. The main case where this would _not_ be true is if you had to build things from source, where caching can have a huge impact. I'm experimenting with a uv command (https://github.com/astral-sh/uv/pull/5391) that would enable you to clear pre-built wheels from the cache, but retain anything that was built from source, to get the best of both worlds.

**Comment by EwoutH** [comment]
Example from our repo: Pandas doesn't have Python 3.13 wheels out yet, but Pandas 2.2.2 can be build on Python 3.13. So it now takes around ~4 minutes to build, either with `uv pip` or an uncached `pip`. While cached pip takes only 30 seconds, uv takes only 3 seconds on Python 3.12 where all wheels are available.

So in the case wheels are not yet up yet, caching would provide huge value if also supported for uv.

**Comment by eifinger** [comment]
I have created an action to install uv and modelled it so it can nearly be used as a drop in replacement: https://github.com/eifinger/setup-uv

A simple example workflow could look like this:

```yaml
- name: Checkout the repository
  uses: actions/checkout@main
- name: Install the latest version of uv
  uses: eifinger/setup-uv@v1
  with:
    enable-cache: true
- name: Test
  run: uv run --frozen pytest
```

**Comment by hugovk** [comment]
I've also been trying out https://github.com/hynek/setup-cached-uv

```yml
jobs:
  tests:
    runs-on: ubuntu-latest  # or macOS, or Windows
    steps:
      - uses: hynek/setup-cached-uv@v2

      - run: uv ...
```

**Comment by codespearhead** [comment]
Should this be closed in favor of [1]?

```yml
- name: Enable caching
  uses: astral-sh/setup-uv@v3
  with:
    enable-cache: true
```

[1] https://github.com/astral-sh/setup-uv?tab=readme-ov-file#enable-caching

**Comment by hugovk** [comment]
See also https://github.com/hynek/setup-cached-uv 

```yml
jobs:
  tests:
    runs-on: ubuntu-latest  # or macOS, or Windows
    steps:
      - uses: hynek/setup-cached-uv@v2

      - run: uv ...
```
