### ISSUE TITLE
python <3.10 fails on macos-14 with `dyld: Library not loaded`

### ISSUE THREAD

**Issue by mbway** [actions/setup-python#825]
**Description:**

When I run this pipeline:
```yaml
name: MacOsTest

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-14
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: "x64"
      - name: print python version
        shell: bash
        run: python --version
```

It fails with:
```
##[group]Run actions/setup-python@v5
with:
  python-version: 3.9
  architecture: x64
  check-latest: false
  token: ***
  update-environment: true
  allow-prereleases: false
##[endgroup]
##[group]Installed versions
Version 3.9 was not found in the local cache
Version 3.9 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.9.18-5997508477/python-3.9.18-darwin-x64.tar.gz"
Extract downloaded archive
[command]/usr/bin/tar xz -C /Users/runner/work/_temp/7b7aa7f9-b410-4ff2-b594-96144647b304 -f /Users/runner/work/_temp/5160d17b-778d-4d38-8d2e-ff031e5fc513
Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.9.18 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
##[error]dyld[3814]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: <E2FD7085-038F-3B8E-94C6-6649527BFDBE> /Users/runner/hostedtoolcache/Python/3.
##[error]9.18/x64/bin/python3.9
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
./setup.sh: line 52:  3814 Abort trap: 6           ./python -m ensurepip
##[error]The process '/bin/bash' failed with exit code 134
```

The pipeline succeeds for macos-13 or python > 3.9

**Action version:**
v5

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
python 3.8, 3.9

**Repro steps:**  
explained above

**Expected behavior:**
the pipeline to succeed

**Actual behavior:**
the pipeline fails
