### ISSUE TITLE
Can't install python 3.12 on linux x64

### ISSUE THREAD

**Issue by cembirler** [actions/setup-python#830]
**Description:**
Getting an error when trying to download Python 3.12 for Linux.
The version not found however 3.12 linux with x64 is listed in the versions-manifest.json file

**Action version:**
actions/setup-python@4
<img width="1116" alt="Screenshot 2024-03-13 at 09 44 03" src="https://github.com/actions/setup-python/assets/12101133/2eb95aab-ff43-4168-875f-2a4720e5eb11">

This is the contents of the .yml file:

```
name: Setup and Run Flask Server

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - master  # Run workflow on push to the master branch

jobs:
  build:
    runs-on: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Set Python version
```

**Platform:**
- [x] Linux

**Runner type:**
- [x] Hosted

**Comment by HarithaVattikuti** [comment]
Hello @cembirler 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by giladdi-tr** [comment]
The same is true for Python version 3.10

**Comment by till** [comment]
Same for 3.7

**Comment by arturgeller6** [comment]
I see the same issue for 3.8.10 when using actions/checkout@v3 with matrix strategy.
I see that semver is not detected properply

`##[debug]Semantic version spec of 3.8.10​ is 3.8.10​
##[debug]isExplicit: 
##[debug]explicit? false
##[debug]evaluating 0 versions
##[debug]match not found`

And when parsing manifest file it does not stop for 3.8.10 when checking arch and os.

**Comment by till** [comment]
My work around is to set an explicit version. 🙃

**Comment by till** [comment]
Maybe to add: it seems like every other run does not match a version and setup-python fails.

Not sure how to provide more details - it just fails to find the version and fails the job.

Can repro local (with act) and online.

**Comment by arturgeller6** [comment]
it is working now for me (perhaps some unicode symbol was in my version when I copied book code)

**Comment by gowridurgad** [comment]
Hii @cembirler I am able to install python 3.12 successfully.
Here's a screenshot for your reference:
<img width="1218" alt="Screenshot 2024-03-22 at 6 54 22 PM" src="https://github.com/actions/setup-python/assets/159780674/ff6b77f0-0eff-4403-b1d4-6e43faa752cc">

**Comment by gowridurgad** [comment]
Hello @cembirler 
Just a gentle reminder!
contents of the .yml file:
```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Set Python version 
```
