### ISSUE TITLE
Wrong python version installed

### ISSUE THREAD

**Issue by adrian-valente** [actions/setup-python#833]
**Description:**
In a github action, a call to setup-python@v3 requiring python-version 3.11 actually installs 3.12, causing crashes downstream when conda is called.

**Action version:**
v3

**Platform:**
- [ ] Ubuntu

**Runner type:**
- [ ] Hosted

**Tools version:**
3.11

**Repro steps:**  
Here is the workflow file:
```
name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        channels: conda-forge,defaults
        channel-priority: true
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python --version
        conda install -y python=3.11
        python --version
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        # conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # conda install pytest
        pytest
```

**Expected behavior:**
The first call to python --version should return a 3.11 release, and hence the conda reinstall of python have no effect. 

**Actual behavior:**
However we see on the first call that python 3.12 was installed, despite the requirement in the call to setup-python. Without the conda reinstall of python 3.11, this causes the subsequent conda install to crash with the error: `ImportError: cannot import name 'install' from 'conda.cli' (/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/__init__.py)`. This issue suddenly surfaced less than a month ago, without other modifications to the workflow. It was mentioned on the conda  repo in [this issue](https://github.com/conda/conda/issues/13560).

**Comment by HarithaVattikuti** [comment]
Hello @adrian-valente 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by MrLucifer-pro** [comment]
- name: Setup Node.js environment
  uses: actions/setup-node@v4.0.2
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional

**Comment by ChristopherRabotin** [comment]
Hi @HarithaVattikuti , is there any update on this issue? I'm encountering an issue where I'm specifying an exact version of Python (`3.11`) but the action also installs `3.12` and `3.13`. The subsequent step finds the Python 3.13 executable, and fails to proceed. This issue happens even when I specify a Python range of `python-version: '>=3.11 <3.13'`.

Build log: https://github.com/nyx-space/hifitime/actions/runs/8476347591/job/23225747105?pr=286

Thanks

**Comment by priya-kinthali** [comment]
Hello @adrian-valente 👋,
Thank you for your detailed description!
The `setup-python` action seems to be correctly setting up the specified Python version. The discrepancy observed might be attributed to how `conda` handles Python versions within its environments. A potential workaround could be to create a new environment. This approach permits conda to manage the dependencies within the confines of that specific environment, which results in a more isolated and manageable context for dependency resolution.
As for the crash error, it appears to be linked to an [issue](https://github.com/conda/conda/issues/13560) with `conda` itself, as you've noted in the description. Hope this clarifies!

**Comment by priya-kinthali** [comment]
Hello @adrian-valente 👋,
Just a gentle ping to see if there are any updates on your end regarding this issue.
Your response would be greatly appreciated. Thank you in advance:)

**Comment by adrian-valente** [comment]
Hello, in my latest workflow run from Tuesday, the problem persisted exactly as stated here. As mentioned it is not critical because one can easily appending `conda install -y python=3.11` to their workflow, but I thought at github actions you might want to look for a more permanent answer, which doesn't seem to be the case so far?

**Comment by adrian-valente** [comment]
Maybe I should give more details though, lest you stay stuck: The setup-python action apparently gives a correct result:
```
Run actions/setup-python@v5
  with:
    python-version: 3.11
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
Installed versions
  Successfully set up CPython (3.11.8)
```
However, the next steps of the workflow involve adding conda to the path:
```yaml
- name: Add conda to system path
  run: |
    # $CONDA is an environment variable pointing to the root of the miniconda directory
    echo $CONDA/bin >> $GITHUB_PATH
- name: Conda info
  run: conda info
- name: Conda list
  run: conda list
- name: Install dependencies
  run: |
    python --version
    conda install -y python=3.11
    python --version
```
Which immediately causes the python version to jump to 3.12. Keep in mind this is the worflow file as proposed directly by github, so one would expect it to work right away. I am not familiar enough with actions internals to understand how it is executed, but thought you might want to know about the issue.
