### ISSUE TITLE
setup-python@v4 fails for Python 3.10.14 on Mac OS 14 (latest) ARM 64 runner

### ISSUE THREAD

**Issue by sr-murthy** [actions/setup-python#865]
**Description:**
I use setup-python@v4 in a project CI pipeline which uses a matrix strategy including Mac OS - the action is now failing on a Mac OS 14 (latest) runner for Python 3.10.14.

**Action version:**
v4

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X ] Hosted
- [ ] Self-hosted

**Tools version:**
3.10.14

**Repro steps:**  
Trigger a CI job on a branch.

**Expected behavior:**
Stage passes.

**Actual behavior:**
Here's an excerpt of the pipeline log for the Python 3.10 setup action:
```shell

Run actions/setup-python@v4
  
Installed versions
  Version 3.10 was not found in the local cache
  Version 3.10 is available for downloading
  Download from "https://github.com/actions/python-versions/releases/download/3.10.14-9004012336/python-3.10.14-darwin-x64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz -C /Users/runner/work/_temp/97020fe3-61b8-4498-b95c-27d0285812c2 -f /Users/runner/work/_temp/439d758c-170b-414d-9135-788fa7f27745
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Create Python 3.10.14 folder
  Copy Python binaries to hostedtoolcache folder
  Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
  Upgrading pip...
  Error: dyld[4551]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <09857011-94D0-3FBA-9F9D-9FCE0E7366FF> /Users/runner/hostedtoolcache/Python/3.10.14/x64/bin/python3.10
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/
  Error: Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
  ./setup.sh: line 53:  4551 Abort trap: 6           ./python -m ensurepip
  Error: The process '/bin/bash' failed with exit code 134
```

The pipeline failure is on a PR - the last successful run was on April 18, and I haven't made any changes to the CI YML.

Here is the relevant section of the CI YML:
```yaml
name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        install-via: [pip]
        arch: [x64]
        include:
          - python-version: "3.11"
            os: ubuntu-latest
            install-via: script
            arch: x64
          - python-version: "3.11"
            os: windows-latest
            install-via: pip
            arch: x86

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      if: matrix.python-version != '3.10'
      with:
        python-version: "3.10"
        architecture: ${{ matrix.arch }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      if: matrix.python-version != '3.11'
      with:
        python-version: "3.11"
        architecture: ${{ matrix.arch }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
        allow-prereleases: false
...
...
```
