### ISSUE TITLE
Cannot load Python modules if they are in a directory named "test"

### ISSUE THREAD

**Issue by jzvikart** [actions/setup-python#874]
In the following workflow, the step "Run OK" succeeds, but the step "Run Fail" fails.

The only difference is the name of the directory (`test` vs. `test1`).

```
name: Bug

on: push
jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.8"
    - name: Set up
      run: |
        mkdir test
        echo "print('OK')" > test/a.py
        mkdir test1
        echo "print('OK')" > test1/a.py
    - name: Run OK
      run: python -m test1.a
    - name: Run Fail
      run: python -m test.a
```

As much as I tried, setting `PYTHONPATH` did not help to fix the last step.

Outputs:

```

Run python -m test1.a
  python -m test1.a
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.8/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib
OK

Run python -m test.a
  python -m test.a
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.8/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib
/opt/hostedtoolcache/Python/3.11.8/x64/bin/python: No module named test.a
Error: Process completed with exit code 1.
```

Needless to say, in normal Python installations the problem does not occur and both `test` and `test1` work.

**Comment by priyagupta108** [comment]
Hello @jzvikart 👋 , The issue you're experiencing arises from a naming conflict with Python's standard library. More specifically, `test` is a module in Python's standard library, and when you run `python -m test.a`, Python searches for `a.py` within the standard library's `test` module, not within your local test directory. On the other hand, `test1` isn't a standard library module, so Python treats it as your custom module and finds `a` within it.

The differences you're noticing between your local Python environment and the GitHub Actions environment are likely due to variations in how the Python interpreter is invoked and the specific environment configurations.
In a normal Python installation running directly on your machine, when you execute a script like `python -m test.a`, Python adds the current directory (i.e., the directory from where you ran the command) to the start of `sys.path`. This is why you can import modules from `test` or `test1` without any issues.
However, in the context of GitHub Actions, each run step starts in a new shell, and the Python interpreter may not automatically add the working directory to `sys.path`. Consequently, when you try to run a module using `python -m`, Python may not check the current directory unless it's explicitly added to `sys.path` or the directory is structured as a proper Python package (i.e., including `__init__.py`).

Although `PYTHONPATH` is used to specify additional directories for Python to check during imports, the `-m` option attempts to import a library module, and Python's standard library directories are always checked before directories in `PYTHONPATH`.

Here are a couple of potential workarounds:

1. Add an `__init__.py` file to the `test` directory. Python then recognizes `test` as a package and finds the `a` module within it.

```yaml
- name: Set up
  run: |
    mkdir test
    echo "print('OK')" > test/a.py
    touch test/__init__.py
```
With an `__init__.py` file in the `test` directory, Python checks the standard library and `PYTHONPATH` first, but since it doesn't find `test.a` in these locations, it checks the current directory, where it finds your `test` package and `a` module.

2. Change the working directory before running the module. Modify your workflow as follows:

```yaml
- name: Run Fail
  working-directory: ./test
  run: python -m a
```

3. Run the script directly. Instead of using `python -m test.a`, try `python test/a.py`.

Please note that these are potential workarounds. The underlying behavior is due to the specific mechanisms of Python's import system and how it interacts with the `-m` option and the `PYTHONPATH`. It's generally a good practice to avoid naming your directories and modules the same as Python's standard library modules to prevent such conflicts. You can check the list of Python standard library modules in the [Python documentation](https://docs.python.org/3/py-modindex.html).

I hope this provides a clearer explanation of the issue. Feel free to reach out if you need any further clarification.
