### ISSUE TITLE
Python 3.12.4: Extract downloaded archive; gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by frenck** [actions/setup-python#886]
**Description:**

![CleanShot 2024-06-10 at 07 51 57@2x](https://github.com/actions/setup-python/assets/195327/dc71784f-2c13-4593-8bc1-bcca738bfa5b)

https://github.com/home-assistant/core/actions/runs/9442844577/job/26006478894?pr=119255

**Action version:**
Specify the action version

actions/setup-python@v5.1.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.12 (resulting in 3.12.4 right now)

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

```yaml
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          check-latest: true
```

https://github.com/home-assistant/core/blob/159503b8d37fbc46a353287416a640ad07c2cced/.github/workflows/ci.yaml#L230-L235

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.
