### ISSUE TITLE
`python-version-file` does not support multiple versions

### ISSUE THREAD

**Issue by astro-stan** [actions/setup-python#894]
**Description:**
It is possible to specify multiple python versions like so:
```yaml
- uses: actions/setup-python@v5
  with:
    python-version: |
      3.8
      3.9
      3.10
```

However, specifying them like so breaks CI:

`.python-version`: 

```
3.8
3.9
3.10
```
```yaml
- uses: actions/setup-python@v5
   with:
     python-version-file: '.python-version'
```

**Action version:**
5

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
See description

**Expected behavior:**
Multiple python versions can be read from `.python-version`

**Actual behavior:**
Multiple python versions **cannot** be read from `.python-version`
