### ISSUE TITLE
Python version '3.12.x' with architecture 'arm64' was not found for Ubuntu 24.04

### ISSUE THREAD

**Issue by MarkusSintonen** [actions/setup-python#902]
**Description:**
In Github Action arm64 runners with Ubuntu 24.04 (`Ubuntu 24.04 by Arm Limited`) `actions/setup-python` gives errors such as `Error: The version '3.12.x' with architecture 'arm64' was not found for Ubuntu 24.04.`.

**Action version:**
v5.1.0

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**
3.12.x

**Repro steps:**  
Try to use `setup-python` in arm64 runners with Ubuntu 24.04 (`Ubuntu 24.04 by Arm Limited`).
```yaml
- name: Setup Python
  uses: actions/setup-python@v5.1.0
  with:
    python-version: 3.12.x
```

**Expected behavior:**
Python executable should be found for Ubuntu 24.04 for the arm64 runner.

**Actual behavior:**
Error happens
