### ISSUE TITLE
self-hosted tools cache setup not working automatically on Linux & Mac with v2

### ISSUE THREAD

**Issue by shoukoo** [actions/setup-python#92]
The issue is related to this PR https://github.com/actions/setup-python/issues/89
I am still getting an error when using setup-python v2 on self-hosted runners on ubuntu18.04

```
Run actions/setup-python@v2
Version 3.8 was not found in the local cache
Version 3.8 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.8.3-20200514.1/python-3.8.3-ubuntu-1804-x64.tar.gz"
Extract downloaded archive
/bin/tar xz --warning=no-unknown-keyword -C ./72938570-f04c-4e44-b107-26e5832ecd2d -f /home/runner/_work/_temp/72938570-f04c-4e44-b107-26e5832ecd2d
Execute installation script
##[error]Version 3.8 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/master/versions-manifest.json
```

I have set `AGENT_TOOLSDIRECTORY`  in the config file
```
- name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
        with:
          python-version: "${{ matrix.python-version }}"
```

I can see it created some folders and files under `/opt/hostedtoolcache` 
```
ubuntu@ip-xx-xx-xx-xx:/opt/hostedtoolcache/Python$ ls
3.7.7  3.8.3
```
