### ISSUE TITLE
Post Run fails when using "cache: pip" on v5.2.0

### ISSUE THREAD

**Issue by clovisp** [actions/setup-python#932]
**Description:**
The latest release makes the `Post Run actions/setup-python` fail systematically with the error message : 
```
Post job cleanup.
Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip
```
We use the following configuration in our workflows:
```
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"
```

Forcing the use of previous version `actions/setup-python@v5.1.1` solves the issue.

**Action version:**
5.2.0

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.11

**Repro steps:**  
Executing any action with the following step:
```
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"
```

**Expected behavior:**
The post run succeeds

**Actual behavior:**
The post run fails:
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/c075a762-2962-4b24-9487-cc5702203b2a">

**Comment by petemounce** [comment]
I see this within my own workflows exactly as reported. I used the same pin-to-5.1.1 workaround (but removing the `cache: pip` worked too). Related to https://github.com/actions/setup-python/issues/436?

**Comment by mahabaleshwars** [comment]
Hello @clovisp,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by aparnajyothi-y** [comment]
Hello @clovisp, Thank you for creating this issue once again. This is expected behavior because you are using cache: pip without installing any dependencies. We were able to reproduce the issue on versions 5.2.0, 5.1.1, and 4 without adding the pip installation because pip hasn't cached any packages yet, so the cache directory doesn't exist.

The setup-python action sets up a Python environment, but it does not create a pip cache directory by default. The pip cache directory is created when pip installs a package and needs to cache it.

We tested the same scenario by adding the pip installation job, and the pip cache file was generated in the /home/runner/.cache/pip location, caching the installed packages.

To fix the issue, please consider the following possibilities:
1.Install dependencies: Make sure all required dependencies are installed and committed.
2.Do not use cache: pip: If there are no dependencies to cache, remove the cache: pip configuration from your GitHub Actions workflow.

If the issue stills continues from your end, Can you please share the workflow runs of v5.1.1 and v5.2.0 to check and assist.

Please find the workflow snippet and screenshots for reference.
```
testjobv5_2_0:
    name: test cache pip
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"

  testjobv_5_1_1:
     name: test cache pip for v5.1.1
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5.1.1
         with:
           python-version: 3.11
           architecture: x64
           cache: "pip"

  testjobv_4:
     name: test cache pip for v4
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v4
         with:
           python-version: 3.11
           architecture: x64
           cache: "pip"
```

<img width="1439" alt="Screenshot 2024-08-30 at 11 18 31 AM" src="https://github.com/user-attachments/assets/5009d4fa-8829-40a1-8154-14d98e1994cc">


To fix the issue 
```
 steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
```
<img width="1439" alt="Screenshot 2024-08-30 at 11 19 37 AM" src="https://github.com/user-attachments/assets/60939e5a-f1f4-4c78-9b93-d9959fc1ed44">
