### ISSUE TITLE
What if I need to cache both pip and pipenv, is that possible?

### ISSUE THREAD

**Issue by nabheet** [actions/setup-python#934]
I would like to cache both pip and pipenv. Wondering how I would accomplish that.

**Comment by mahabaleshwars** [comment]
Hello @nabheet,
Thank you for creating this feature request. We will investigate it and provide feedback as soon as we have some updates.

**Comment by priyagupta108** [comment]
Hi @nabheet 👋,
The `setup-python` action supports caching for a single package manager at a time, either pip or pipenv. To cache both pip and pipenv dependencies, you can use two separate steps to cache each package manager independently within the same workflow. Here's an example of how you can achieve this:
```yaml
name: Cache pip and pipenv

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache pipenv packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --ignore-pipfile
```

In this example, the `actions/cache` action is used to cache the pip dependencies located in `~/.cache/pip` and the pipenv virtual environments located in `~/.local/share/virtualenvs`. Adjust the paths as necessary for your specific setup. The cache keys are generated based on the hash of the `requirements.txt` and `Pipfile.lock` files to ensure that the cache is updated when dependencies change. 

I hope this helps! Let us know if you have any further questions.
