### ISSUE TITLE
Failure to parse pyproject.toml file when run on Windows

### ISSUE THREAD

**Issue by nfelt14** [actions/setup-python#935]
**Description:**

The action is failing with this error message when run on a Windows runner.
```
Error: Control characters (codes < 0x1f and 0x7f) are not allowed in comments, use \u000d instead at row 19, col 61, pos 454:
18: omit = [
19>   "**/tm_devices/commands/**"  # TODO: remove this exclusion
                                                                ^
20: ]
```

**Action version:**
I believe that it is v5.2.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  

Workflow run: https://github.com/tektronix/tm_devices/actions/runs/10624903656/job/29454004640?pr=293

Here is a snippet of the toml file that is failing to be read:
```toml

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "raise NotImplementedError"
]
fail_under = 100
omit = [
  "**/tm_devices/commands/**"  # TODO: remove this exclusion
]
show_missing = true
skip_empty = true

[tool.poetry.dependencies]
python = "^3.8"  # This is the main Python version requirement
```

**Expected behavior:**

I expect it to parse the toml file the same way that it works on Ubuntu and MacOS.

**Actual behavior:**

The file is unable to be parsed due to a false failure for a character that doesn't seem to actually be there.
