### ISSUE TITLE
PyPy3.10 is v7.3.16 not the latest v7.3.17

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#936]
**Description:**

PyPy3.10 v7.3.17 was released last week on 22024-08-28:

* https://pypy.org/posts/2024/08/pypy-v7317-release.html
* https://github.com/pypy/pypy/releases/tag/release-pypy3.10-v7.3.17

This release also dropped PyPy3.9 (PyPy3.8 was dropped earlier).

`pypy3.10` from this action still installs v7.3.16.

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

```yml
name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: pypy3.10
      - run: python --version --version
```

https://github.com/hugovk/test/blob/pypy3.10/.github/workflows/test.yml
https://github.com/hugovk/test/actions/runs/10661800324

**Expected behavior:**

Installs PyPy3.10 7.3.17

**Actual behavior:**

`python --version --version` gives on the three operating systems:

```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 13:13:38)
[PyPy 7.3.16 with MSC v.1929 64 bit (AMD64)]
```
```
Python 3.10.14 (39dc8d3c85a7, Aug 27 2024, 20:40:24)
[PyPy 7.3.17 with GCC Apple LLVM 15.0.0 (clang-1500.3.9.4)]
```
```
Python 3.10.14 (75b3de9d9035, Apr 21 2024, 10:54:48)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
```
