### ISSUE TITLE
::error::Bad credentials

### ISSUE THREAD

**Issue by rgarrigue** [actions/setup-python#94]
Hi there

I'm using your action successfully on GitHub. But now and then when I'm testing stuff, I run my workflow with https://github.com/nektos/act. And I've an issue with it, I wanted to have some insight about it

```
[Tests/tests] Exec command '[node /actions/actions-setup-python@v2/dist/index.js]'
[Tests/tests]   💬  ::debug::Semantic version spec of 3.7 is 3.7
[Tests/tests]   💬  ::debug::isExplicit: 
[Tests/tests]   💬  ::debug::explicit? false
[Tests/tests]   💬  ::debug::evaluating 0 versions
[Tests/tests]   💬  ::debug::match not found
| Version 3.7 was not found in the local cache
[Tests/tests]   ❗  ::error::Bad credentials
[Tests/tests]   ❌  Failure - Setup Python 
```

I tried v1 v2 and master without success.

Note, here's the related issue for act https://github.com/nektos/act/issues/251

**Comment by konradpabjan** [comment]
Thanks for reporting opening this issue.

I tried reproducing this, but I haven't been able to hit this 🤔Here is the workflows that I tried.

```
name: Tests
jobs:
  test1:
    runs-on: ubuntu-latest
    container: ubuntu:19.10
    strategy:
      matrix:
        python: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
```

Does this happen consistently or is it rather sporadic? I see a few other users have reported this in the issue you linked.

**Comment by konradpabjan** [comment]
I've managed to get a local repo on another machine... standby

**Comment by rgarrigue** [comment]
It's consistent using `act`, locally.

Note, I'm not using `    container: ubuntu:19.10`, 19.10 is my personal workstation.

Here's the minimal workflow file

```
name: Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
```
