### ISSUE TITLE
The action fails if the `.python-version` (passed into `python-version-file` input) contains a comment

### ISSUE THREAD

**Issue by nitrocode** [actions/setup-python#949]
**Description:**
The workflow

```yaml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
```

The `.python-version` file

```
# This file is read by the terraform if var.runtime is unset
3.11
```

The error

```bash
  Version # This file is read by the terraform if var.runtime is unset
  3.11 was not found in the local cache
  Error: The version '# This file is read by the terraform if var.runtime is unset
  3.11' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Action version:**
Latest v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
See above

**Expected behavior:**
Ignores the comments and only grabs the version

**Actual behavior:**
It doesn't ignore the comments
