### ISSUE TITLE
`pip install --ignore-installed` is not updating the version string

### ISSUE THREAD

**Issue by retzero** [actions/setup-python#955]
**Description:**

This workflows installs the latest numpy version `2.0.2` but `pip` shows wrong version string!

```yaml
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9.19

      - name: install requirments
        run: |
          python -m pip install numpy==1.26.4
          python -m pip install numpy --ignore-installed

      - name: Check the numpy version
        run: |
          python -m pip freeze | grep numpy
          python -c 'import numpy as np
          print(np.__version__)'
```

- Output
```
numpy==1.26.4
2.0.2
```

**Action version:**
Specify the action version
`v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

`3.9.19`

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.
