### ISSUE TITLE
CPython < 3.11 x64 failing on m1 runners?

### ISSUE THREAD

**Issue by masklinn** [actions/setup-python#960]
As Github is shutting down the macos-12 workers, I figured I'd look at running x86 python on m1.

However, while it seems to work fine with the >= 3.11 universal binary (using `arch` to force running a specific architecture) as well as passing an explicit architecture to select the correct pypy or graal, the non-universal cpython binaries seem problematic e.g. 3.10 x64 fails with
```
  Error: dyld[2227]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <B5E916E8-01CA-35D0-8CA1-DB48CC803EB7> /Users/runner/hostedtoolcache/Python/3.10.15/x64/bin/python3.10
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file,
  Error: not in dyld cache)
```

Here's the workflow file I'm using: https://github.com/masklinn/ci-test/blob/main/.github/workflows/crossplatform.yml
```yaml
name: crossplatform

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-cross:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.x" # should be universal
          - "3.10" # should be *not* universal
          - "pypy-3.10"
          - "graalpy-24"
        archname: [x86_64, aarch64]
        include:
          - archname: x86_64
            arch: x86_64
            architecture: x64
            processor: i386
          - archname: aarch64
            arch: arm64
            architecture: arm64
            processor: arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: arch(1)
        env:
          ARCHPREFERENCE: ${{ matrix.arch }}
        run: |
          proc=$(arch python -c "import platform; print(platform.processor())")
          echo $proc
          test $proc = ${{ matrix.processor }}
```
here's the nearly successful run: https://github.com/masklinn/ci-test/actions/runs/11296863554/job/31422564472
