### ISSUE TITLE
pipx doesn't respect actions/setup-python version

### ISSUE THREAD

**Issue by juftin** [actions/setup-python#967]
**Description:**

I'm not sure if this is an issue with [actions/setup-python](https://github.com/actions/setup-python), `pipx`, or the runners themselves - but the behavior for this changed for me between 2024-10-15 and 2024-10-16 (if you think this should be reported elsewhere please let me know)

In the below workflow, the `setup-python-example` Python package requires Python >= 3.11

```yaml
name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Get Python version
        run: python --version
      - name: Get pipx version
        run: pipx --version
      - name: Install Python Package
        run: pipx install .
```

Before 2024-10-16 the example package was installed using Python 3.12, but after it uses Python 3.10 and the workflow fails.

```
creating virtual environment...
determining package name from '/home/runner/work/setup-python-example/setup-python-example'...
ERROR: Package 'setup-python-example' requires a different Python: 3.10.[12](https://github.com/juftin/setup-python-example/actions/runs/11471145881/job/31921582259#step:6:13) not in '>=3.11'
Cannot determine package name from spec
'/home/runner/work/setup-python-example/setup-python-example'. Check package
spec for errors.
```

**Action version:**

`v5`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
`3.12`

**Repro steps:**  

1) Use `ubuntu-latest` runner
2) Run `actions/setup-python@v5` with version `3.12`
3) Install a package the requires Python >= 3.11

The action will fail because `pipx` is trying to use Python 3.10.

**Expected behavior:**

I expect `pipx` to use whatever version is setup with `actions/setup-python`

**Actual behavior:**

I believe `pipx` is using the runner's default Python version

**Comment by juftin** [comment]
Here is an example repo to reproduce this: https://github.com/juftin/setup-python-example

and the failing workflow: https://github.com/juftin/setup-python-example/actions/runs/11471145881/job/31921582259

**Comment by juftin** [comment]
I was able to confirm that the following resolved the issue - but I'm still not clear why the behavior changed ~ a week ago

```yaml
name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python Package
        run: pipx install .
        env:
          PIPX_DEFAULT_PYTHON: ${{ steps.python.outputs.python-path }}
```

**Comment by priyagupta108** [comment]
Hi @juftin 👋,
Thank you for your report. We'll investigate the issue and get back to you with the details!

**Comment by zariiii9003** [comment]
Same problem here.

**Comment by priya-kinthali** [comment]
Hello @juftin 👋,
The `pipx` utility is provided by the runner image. It appears that the change in behaviour you observed is due to the `ubuntu-latest` label reverting from `Ubuntu-24` ([Default python 3.12.3](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#language-and-runtime)) to `Ubuntu-22` ([Default python 3.10.12](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime)) on Oct 16 as per this [comment](https://github.com/actions/runner-images/issues/10636#issuecomment-2417303444). It seems like the `pipx` is using the runner's default Python version unless explicitly configured otherwise.
As you correctly mentioned, using the `PIPX_DEFAULT_PYTHON` environment variable allows specifying the Python version that `pipx` should use.
Additionally, You might also consider using the following workaround to ensure pipx uses the specified Python version:
```yaml
- name: Setup Python
  id: python
  uses: actions/setup-python@v5
  with:
    python-version: "3.12"
- name: Install pipx
  run: python -m pip install --user pipx
- name: Ensure pipx uses the correct Python
  run: python -m pipx ensurepath
- name: Install Python Package
  run: pipx install .
```
This setup explicitly installs pipx, which then installs the desired Python package using the specified Python version. Please find the successful run [here](https://github.com/setup-actions-demo/test-samplepython/actions/runs/11717326927/job/32636805106).
Hope this helps!
Since this is related to the runner rather than the setup-python action, we recommend raising a ticket in the [runner-images repository](https://github.com/actions/runner-images/issues) for any further concerns.
Thankyou!

**Comment by zariiii9003** [comment]
@priya-kinthali Would it be possible for `actions/setup-python` to configure pipx to use the selected python version? Maybe you could set `PIPX_DEFAULT_PYTHON` so the user doesn't have to?

**Comment by priya-kinthali** [comment]
Hello @zariiii9003 👋,
The `setup-python` action does not manage or configure tools like `pipx`. The configuration of `pipx` is handled by the runner environment itself. Managing `pipx` within the action could lead to conflicts or unexpected behaviour in different environments.
Therefore, we kindly recommend setting the `PIPX_DEFAULT_PYTHON` environment variable in your workflow or manually installing `pipx` using `python -m pip install --user pipx`. 
Thank you for your understanding.

**Comment by priya-kinthali** [comment]
Hello @juftin 👋,
Just a gentle reminder!

**Comment by priya-kinthali** [comment]
Hello @juftin 👋,
Just following up to see if you have any other concerns or need any assistance. Please let us know if there's anything else we can help with.
Thank you!

**Comment by juftin** [comment]
Apologies @priya-kinthali - thanks for all of your hard work digging in on this, much appreciated! You were right that the issue was actually `ubuntu-latest` being reverted back to `Ubuntu-22` from `Ubuntu-24`

IMO this is the best way to handle this:
```
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python Package
        run: pipx install .
        env:
          PIPX_DEFAULT_PYTHON: ${{ steps.python.outputs.python-path }}
```
