### ISSUE TITLE
All packages with CLI failing with '/home/runner/.local/bin' which is not on PATH

### ISSUE THREAD

**Issue by heitorlessa** [actions/setup-python#99]
**Describe the bug**

Packages entrypoints/CLI are not available in PATH e.g. `flake8`, `poetry`, `pytest`.

When investigating Github Action logs I can see two noticeable warnings that explains the issue:

- `Defaulting to user installation because normal site-packages is not writeable`
- `WARNING: The script flake8 is installed in '/home/runner/.local/bin' which is not on PATH.`

As I have [another repo using this same action](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/python.yml), and it is working just fine, I wonder if something happened recently to cause this - Virtualenv manipulation, PATH manipulation, etc.

**Which version of the action are you using?**

Tried both - same issue

- [x] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux (ubuntu latest)
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)

**3.6, 3.7, 3.8**

**To Reproduce**

Create a new Github action using the following steps:

```yaml
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip poetry
          poetry install
```

It will fail when it attempts to run `poetry` command. Same happens with any other package.

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

https://github.com/aws-samples/cookiecutter-aws-sam-pipeline/pull/10/checks?check_run_id=730151630

**Screenshots**

![image](https://user-images.githubusercontent.com/3340292/83498391-c639cf00-a4b3-11ea-9522-dea8ee0b882f.png)

**Additional context**

**PATH content** - Captured via `tmate` session

```shell
echo $PATH
/opt/hostedtoolcache/Python/3.6.10/x64/bin:/opt/hostedtoolcache/Python/3.6.10/x64:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.dotnet/tools

```

**Debug logs**

```python
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in /opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages (20.1.1)
runner@fv-az78:~/work/cookiecutter-aws-sam-pipeline/cookiecutter-aws-sam-pipeline$ pip install flake8
Defaulting to user installation because normal site-packages is not writeable
Collecting flake8
  Downloading flake8-3.8.2-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 1.7 MB/s
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/runner/.local/lib/python3.6/site-packages (from flake8) (1.1.3)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 796 kB/s
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 9.7 MB/s
Requirement already satisfied: zipp>=0.5 in /home/runner/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->flake8) (3.1.0)
Installing collected packages: mccabe, pycodestyle, pyflakes, flake8
  WARNING: The script pycodestyle is installed in '/home/runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyflakes is installed in '/home/runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flake8 is installed in '/home/runner/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by reillysiemens** [comment]
For what it's worth, I think I ran into a similar issue. Looks like for some reason [Python 2 is being used in the container](https://github.com/reillysiemens/greet/runs/1266547785?check_suite_focus=true#step:4:21) even when I specified another version. Maybe that's related? :thinking:

**Comment by indirectlylit** [comment]
I'm reproducing a very similar issue. I have the same Python action running in two repos, and it succeeds in one while failing in another.

In this case I'm trying to run `flake8`, but get the same "command not found" issue with `black` and `pytest`:

```yaml
name: Python tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - run: |
        # Hack to get setup-python to work on act
        # https://github.com/nektos/act/issues/251#issuecomment-706412948
        if [ ! -f "/etc/lsb-release" ] ; then
          echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 .
```

In the repo where this doesn't work, it gives the warning:

```
WARNING: The script flake8 is installed in '/opt/hostedtoolcache/Python/3.6.12/x64/lib/my_project' which is not on PATH.
```

In the repo where it does work, there is no warning.

Interestingly, I can reproduce this both in the github runner, and also locally using the [`act` local Docker runner](https://github.com/nektos/act) on mac. This implies that there's something about the structure of the two repos which is causing different behaviors. Will try to narrow it down to a reproducible scenario.

**Comment by indirectlylit** [comment]
Update:

I've narrowed down the issue to a [`setup.cfg`](https://docs.python.org/3/distutils/configfile.html) file in the root directory of the affected repo. There was a config like:

```cfg
[install]
install-scripts=...
```

which was affecting the location to which pip installed the commands

**Comment by indirectlylit** [comment]
@heitorlessa looks like your repo might have a similar issue:

https://github.com/aws-samples/cookiecutter-aws-sam-pipeline/blob/f50dfee4f1dd2e618bd3c23098ce0e8b679d5c77/setup.cfg#L1-L2

```cfg
[install]
prefix= 
```

**Comment by abitrolly** [comment]
Same here. `/home/runner/.local/bin` is not added to `$PATH`. This dir is not present on Fedora 33 either, but this doesn't really make sense for a build system.
```
  Creating /home/runner/.local/bin
  changing mode of /home/runner/.local/bin/coverage to 755
  changing mode of /home/runner/.local/bin/coverage-3.8 to 755
  changing mode of /home/runner/.local/bin/coverage3 to 755
```

**Comment by januszm** [comment]
It may happen in the case where python dependencies are mistakingly referenced BEFORE `Set Up Python` step, i.e. `/home/runner/.local/bin not in PATH` error will happen with the following:

```yml
    - name: Install dependencies
      run: |
        sudo apt-get -y install ...stuff...
        python -m pip install --upgrade pipenv
        pipenv sync --dev
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}       
```

But when you install Python dependencies after setting-up Python it'll be OK:

```yml
    - name: Install dependencies
      run: sudo apt-get -y ...stuff...
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv sync --dev
```

I just tested with ubuntu-latest and `matrix: python-version: ['3.9']` and it works fine.
