### ISSUE TITLE
Combination of Python 3.12 on Ubuntu arm64 fails

### ISSUE THREAD

**Issue by paulrobello** [actions/setup-python#990]
**Description:**
Matrix test in github action is failing with combo of Python 3.12 on Ubuntu-latest arm64 arch

**Action version:**
actions/setup-python@v5

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.12

**Repro steps:**  

```yaml
jobs:
  build:
    name: Build distribution 📦
    runs-on: ${{ matrix.os }}
    if: ${{ ! contains(github.event.head_commit.message, 'no-build') }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
        arch: [arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
```

**Expected behavior:**
Python should install

**Actual behavior:**
```
Version 3.12 was not found in the local cache
  Version 3.12 is available for downloading
  Download from "https://github.com/actions/python-versions/releases/download/3.[12](https://github.com/paulrobello/par_ai_core/actions/runs/12506270403/job/34890940519#step:3:13).8-12154062663/python-3.12.8-linux-22.04-arm64.tar.gz"
  Extract downloaded archive
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/7db71ffa-ecc2-476b-a589-d3c995a97ac4 -f /home/runner/work/_temp/059542d5-210f-4f0a-a58c-697246fd7e84
  Execute installation script
  Check if Python hostedtoolcache folder exist...
  Deleting Python 3.12.8
  Create Python 3.12.8 folder
  Copy Python binaries to hostedtoolcache folder
  Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
  Upgrading pip...
  Error: ./setup.sh: line 54: ./python: cannot execute binary file: Exec format error
  Error: The process '/usr/bin/bash' failed with exit code 126
```
